/**
 * Generated by scripts/generate-api-types.mjs from openapi.json and route-owners.json; do not edit.
 */
import type { components as core } from '../../../api/generated/core';

export interface paths {
    "/api/assets/{asset_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Image Asset File */
        get: operations["image_asset_file_api_assets__asset_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/image-generation/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Image Assets */
        get: operations["image_assets_api_image_generation_assets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/image-generation/assets/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Image Asset */
        delete: operations["delete_image_asset_api_image_generation_assets__asset_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/image-generation/assets/{asset_id}/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete Image Asset */
        post: operations["delete_image_asset_api_image_generation_assets__asset_id__delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/image-generation/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Image Jobs */
        get: operations["image_jobs_api_image_generation_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/image-generation/jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Image Job */
        post: operations["retry_image_job_api_image_generation_jobs__job_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/image-generation/model/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Download Image Model */
        post: operations["download_image_model_api_image_generation_model_download_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/image-generation/model/ensure-loaded": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ensure Image Model Loaded
         * @description Start the managed service and make the requested model resident.
         */
        post: operations["ensure_image_model_loaded_api_image_generation_model_ensure_loaded_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/image-generation/model/load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Load Image Model */
        post: operations["load_image_model_api_image_generation_model_load_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/image-generation/model/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Image Model Status */
        get: operations["image_model_status_api_image_generation_model_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/image-generation/model/unload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unload Image Model */
        post: operations["unload_image_model_api_image_generation_model_unload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/image-generation/references": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Image References */
        get: operations["image_references_api_image_generation_references_get"];
        put?: never;
        /** Upload Image Reference */
        post: operations["upload_image_reference_api_image_generation_references_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/image-generation/service/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Image Service */
        post: operations["start_image_service_api_image_generation_service_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssetContentResponse */
        AssetContentResponse: core["schemas"]["AssetContentResponse"];
        /** AssetLegacyRootScan */
        AssetLegacyRootScan: core["schemas"]["AssetLegacyRootScan"];
        /**
         * AssetType
         * @enum {string}
         */
        AssetType: core["schemas"]["AssetType"];
        /**
         * AssistantToolAction
         * @description Backend-owned action definition for an assistant tool.
         */
        AssistantToolAction: core["schemas"]["AssistantToolAction"];
        /**
         * AssistantToolRegistryPayload
         * @description Serializable backend mirror of assistant tools and actions.
         */
        AssistantToolRegistryPayload: core["schemas"]["AssistantToolRegistryPayload"];
        /**
         * AssistantToolSpec
         * @description Backend-owned assistant tool metadata and actions.
         */
        AssistantToolSpec: core["schemas"]["AssistantToolSpec"];
        /** AuthSessionListResponse */
        AuthSessionListResponse: core["schemas"]["AuthSessionListResponse"];
        /** AuthSessionResponse */
        AuthSessionResponse: core["schemas"]["AuthSessionResponse"];
        /** AuthSessionSummary */
        AuthSessionSummary: core["schemas"]["AuthSessionSummary"];
        /** CancelJobRequest */
        CancelJobRequest: core["schemas"]["CancelJobRequest"];
        /** CancelState */
        CancelState: core["schemas"]["CancelState"];
        /** ChatMessage */
        ChatMessage: core["schemas"]["ChatMessage"];
        /** ChatSession */
        ChatSession: core["schemas"]["ChatSession"];
        /** ChatSessionListResponse */
        ChatSessionListResponse: core["schemas"]["ChatSessionListResponse"];
        /** ChatSessionSummary */
        ChatSessionSummary: core["schemas"]["ChatSessionSummary"];
        /**
         * ChatTextAttachment
         * @description A small, UTF-8 text file attached to a chat turn.
         *
         *     Binary files are deliberately not accepted through the JSON chat API.  The
         *     browser reads supported text documents before sending them, which keeps the
         *     stored transcript and every provider prompt self-contained.
         */
        ChatTextAttachment: core["schemas"]["ChatTextAttachment"];
        /**
         * CheckpointBundleRequest
         * @description Extensible state bundle with explicit checkpoint control fields.
         */
        CheckpointBundleRequest: core["schemas"]["CheckpointBundleRequest"];
        /** CheckpointEnvelope */
        CheckpointEnvelope: core["schemas"]["CheckpointEnvelope"];
        /** ClaimJobRequest */
        ClaimJobRequest: core["schemas"]["ClaimJobRequest"];
        /** ClaimJobResponse */
        ClaimJobResponse: core["schemas"]["ClaimJobResponse"];
        /** ClientErrorAccepted */
        ClientErrorAccepted: core["schemas"]["ClientErrorAccepted"];
        /** ClientErrorReport */
        ClientErrorReport: core["schemas"]["ClientErrorReport"];
        /** CodexAuthStatus */
        CodexAuthStatus: core["schemas"]["CodexAuthStatus"];
        /** CoinMarketCapCredentialStatus */
        CoinMarketCapCredentialStatus: core["schemas"]["CoinMarketCapCredentialStatus"];
        /** CoinMarketCapCredentialUpdate */
        CoinMarketCapCredentialUpdate: core["schemas"]["CoinMarketCapCredentialUpdate"];
        /** CompatibilityHandoffPayload */
        CompatibilityHandoffPayload: core["schemas"]["CompatibilityHandoffPayload"];
        /** CompleteJobRequest */
        CompleteJobRequest: core["schemas"]["CompleteJobRequest"];
        /**
         * CreateChatSessionRequest
         * @description Client selection; trusted identity/profile content is intentionally absent.
         */
        CreateChatSessionRequest: core["schemas"]["CreateChatSessionRequest"];
        /** CreateJobRequest */
        CreateJobRequest: core["schemas"]["CreateJobRequest"];
        /** DeleteChatSessionResponse */
        DeleteChatSessionResponse: core["schemas"]["DeleteChatSessionResponse"];
        /** DiagnosticsPayload */
        DiagnosticsPayload: core["schemas"]["DiagnosticsPayload"];
        /**
         * EventReaderDiagnostics
         * @description Live job events in this process (WP-5.4).
         */
        EventReaderDiagnostics: core["schemas"]["EventReaderDiagnostics"];
        /** FailJobRequest */
        FailJobRequest: core["schemas"]["FailJobRequest"];
        /** GatewayHealth */
        GatewayHealth: core["schemas"]["GatewayHealth"];
        /**
         * GatewayReadinessPayload
         * @description Stable readiness fields plus deployment-specific diagnostic fields.
         */
        GatewayReadinessPayload: core["schemas"]["GatewayReadinessPayload"];
        /** GpuResidencyPolicy */
        GpuResidencyPolicy: core["schemas"]["GpuResidencyPolicy"];
        /** HTTPValidationError */
        HTTPValidationError: core["schemas"]["HTTPValidationError"];
        /** HermesDiagnosticsPaths */
        HermesDiagnosticsPaths: core["schemas"]["HermesDiagnosticsPaths"];
        /**
         * HermesStatusResponse
         * @description Sidecar reachability and the runtime configuration that reaches it.
         */
        HermesStatusResponse: core["schemas"]["HermesStatusResponse"];
        /** IbkrSettingsPayload */
        IbkrSettingsPayload: core["schemas"]["IbkrSettingsPayload"];
        /** IbkrSettingsStatus */
        IbkrSettingsStatus: core["schemas"]["IbkrSettingsStatus"];
        /** IbkrSettingsUpdate */
        IbkrSettingsUpdate: core["schemas"]["IbkrSettingsUpdate"];
        /** ImageAssetDeleteResponse */
        ImageAssetDeleteResponse: {
            /** Asset Id */
            asset_id: string;
            /** Deleted */
            deleted: boolean;
            /** File Deleted */
            file_deleted: boolean;
            /** File Error */
            file_error?: string | null;
            /** Ok */
            ok: boolean;
        };
        /** ImageModelActionRequest */
        ImageModelActionRequest: {
            /**
             * Provider
             * @default flux_klein
             */
            provider?: string;
        };
        /** ImageModelDownloadProgress */
        ImageModelDownloadProgress: {
            /** Bytes Downloaded */
            bytes_downloaded: number;
            /** Bytes Total */
            bytes_total: number;
            /** Indeterminate */
            indeterminate: boolean;
            /** Percent */
            percent: number | null;
            /** Status */
            status: string;
        };
        /** ImageModelDownloadRequest */
        ImageModelDownloadRequest: {
            /** Hf Token */
            hf_token?: string | null;
            /**
             * Provider
             * @default flux_klein
             */
            provider?: string;
        };
        /** ImageModelEntry */
        ImageModelEntry: {
            download_progress?: components["schemas"]["ImageModelDownloadProgress"] | null;
            /** Downloaded */
            downloaded?: boolean | null;
            /** Gated */
            gated?: boolean | null;
            /** Key */
            key?: string | null;
            /** Label */
            label?: string | null;
            /** License */
            license?: string | null;
            /** Loaded */
            loaded?: boolean | null;
            local_model?: components["schemas"]["ImageModelLocalStatus"] | null;
            /** Minimum Diffusers */
            minimum_diffusers?: string | null;
            /** Minimum Torch */
            minimum_torch?: string | null;
            /** Model */
            model?: string | null;
            /** Provider */
            provider?: string | null;
            /** Repo Id */
            repo_id?: string | null;
            /** State */
            state?: string | null;
            /** Supports Download */
            supports_download?: boolean | null;
            /** Supports Image To Image */
            supports_image_to_image?: boolean | null;
        } & {
            [key: string]: unknown;
        };
        /** ImageModelLocalStatus */
        ImageModelLocalStatus: {
            /** Complete */
            complete?: boolean | null;
            /** Exists */
            exists?: boolean | null;
            /** Gated */
            gated?: boolean | null;
            /** License */
            license?: string | null;
            /** Local Dir */
            local_dir?: string | null;
            /** Missing */
            missing?: string[] | null;
            /** Ok */
            ok?: boolean | null;
            /** Repo Id */
            repo_id?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** ImageModelStatusResponse */
        ImageModelStatusResponse: {
            download_progress?: components["schemas"]["ImageModelDownloadProgress"] | null;
            /** Downloaded */
            downloaded?: boolean | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Error */
            error?: string | null;
            /** Explicit Load Required */
            explicit_load_required?: boolean | null;
            /** Gated */
            gated?: boolean | null;
            /** Key */
            key?: string | null;
            /** Label */
            label?: string | null;
            /** License */
            license?: string | null;
            /** Loaded */
            loaded?: boolean | null;
            local_model?: components["schemas"]["ImageModelLocalStatus"] | null;
            /** Minimum Diffusers */
            minimum_diffusers?: string | null;
            /** Minimum Torch */
            minimum_torch?: string | null;
            /** Model */
            model?: string | null;
            /** Models */
            models?: components["schemas"]["ImageModelEntry"][] | null;
            /** Ok */
            ok?: boolean | null;
            /** Provider */
            provider?: string | null;
            /** Repo Id */
            repo_id?: string | null;
            /** Service */
            service?: string | null;
            /** State */
            state?: string | null;
            /** Supports Download */
            supports_download?: boolean | null;
            /** Supports Image To Image */
            supports_image_to_image?: boolean | null;
        } & {
            [key: string]: unknown;
        };
        /** ImageReferenceUploadResponse */
        ImageReferenceUploadResponse: {
            asset: components["schemas"]["PublicAssetRecord"];
            /** Ok */
            ok: boolean;
        };
        /** JobError */
        JobError: core["schemas"]["JobError"];
        /** JobError */
        "JobError-Input": core["schemas"]["JobError-Input"];
        /** JobLease */
        JobLease: core["schemas"]["JobLease"];
        /**
         * JobListResponse
         * @description A page of jobs, newest first (WP-5.5).
         */
        JobListResponse: core["schemas"]["JobListResponse"];
        /** JobProgress */
        JobProgress: core["schemas"]["JobProgress"];
        /** JobProgress */
        "JobProgress-Input": core["schemas"]["JobProgress-Input"];
        /** JobRecord */
        JobRecord: core["schemas"]["JobRecord"];
        /** JobStage */
        JobStage: core["schemas"]["JobStage"];
        /** JobStage */
        "JobStage-Input": core["schemas"]["JobStage-Input"];
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: core["schemas"]["JobStatus"];
        /** LegacyGenerateTitleRequest */
        LegacyGenerateTitleRequest: core["schemas"]["LegacyGenerateTitleRequest"];
        /** LegacyGenerateTitleResponse */
        LegacyGenerateTitleResponse: core["schemas"]["LegacyGenerateTitleResponse"];
        /** LegacySessionCreateResponse */
        LegacySessionCreateResponse: core["schemas"]["LegacySessionCreateResponse"];
        /** LegacySessionListItem */
        LegacySessionListItem: core["schemas"]["LegacySessionListItem"];
        /** LegacySessionListResponse */
        LegacySessionListResponse: core["schemas"]["LegacySessionListResponse"];
        /** LegacySessionResponse */
        LegacySessionResponse: core["schemas"]["LegacySessionResponse"];
        /** LegacySessionUpdateRequest */
        LegacySessionUpdateRequest: core["schemas"]["LegacySessionUpdateRequest"];
        /** LegacySuccessResponse */
        LegacySuccessResponse: core["schemas"]["LegacySuccessResponse"];
        /** LocalLoginRequest */
        LocalLoginRequest: core["schemas"]["LocalLoginRequest"];
        /** ModelResidencyDiagnostics */
        ModelResidencyDiagnostics: core["schemas"]["ModelResidencyDiagnostics"];
        /** ModelResidencyRecord */
        ModelResidencyRecord: core["schemas"]["ModelResidencyRecord"];
        /** ModelResidencyRecord */
        "ModelResidencyRecord-Input": core["schemas"]["ModelResidencyRecord-Input"];
        /**
         * ModelResidencyStatus
         * @enum {string}
         */
        ModelResidencyStatus: core["schemas"]["ModelResidencyStatus"];
        /** ModelSummary */
        ModelSummary: core["schemas"]["ModelSummary"];
        /** PersistenceInventory */
        PersistenceInventory: core["schemas"]["PersistenceInventory"];
        /** PromptRenderRequest */
        PromptRenderRequest: core["schemas"]["PromptRenderRequest"];
        /** PromptTemplate */
        PromptTemplate: core["schemas"]["PromptTemplate"];
        /**
         * ProviderCapability
         * @enum {string}
         */
        ProviderCapability: core["schemas"]["ProviderCapability"];
        /** ProviderFacadePayload */
        ProviderFacadePayload: core["schemas"]["ProviderFacadePayload"];
        /** ProviderModelCacheEntry */
        ProviderModelCacheEntry: core["schemas"]["ProviderModelCacheEntry"];
        /** ProviderModelCachePayload */
        ProviderModelCachePayload: core["schemas"]["ProviderModelCachePayload"];
        /** ProviderModelRefreshRequest */
        ProviderModelRefreshRequest: core["schemas"]["ProviderModelRefreshRequest"];
        /** ProviderSummary */
        ProviderSummary: core["schemas"]["ProviderSummary"];
        /** PublicAssetLegacyImportDryRun */
        PublicAssetLegacyImportDryRun: core["schemas"]["PublicAssetLegacyImportDryRun"];
        /**
         * PublicAssetListResponse
         * @description ``AssetListResponse`` as the API returns it.
         */
        PublicAssetListResponse: core["schemas"]["PublicAssetListResponse"];
        /** PublicAssetMigrationPreview */
        PublicAssetMigrationPreview: core["schemas"]["PublicAssetMigrationPreview"];
        /**
         * PublicAssetRecord
         * @description An asset as the API returns it: ids and URLs, never where its bytes are
         *     stored (WP-4.10). Built from an ``AssetRecord``: the storage path and key
         *     and the legacy ``compat`` block are left out, absolute paths in metadata
         *     become file names.
         */
        PublicAssetRecord: core["schemas"]["PublicAssetRecord"];
        /** RenderedPrompt */
        RenderedPrompt: core["schemas"]["RenderedPrompt"];
        /** ReplayPrimitive */
        ReplayPrimitive: core["schemas"]["ReplayPrimitive"];
        /** ReplayPrimitiveList */
        ReplayPrimitiveList: core["schemas"]["ReplayPrimitiveList"];
        /** ReportArtifact */
        ReportArtifact: core["schemas"]["ReportArtifact"];
        /** ReportListResponse */
        ReportListResponse: core["schemas"]["ReportListResponse"];
        /** ResearchBudgetStatus */
        ResearchBudgetStatus: core["schemas"]["ResearchBudgetStatus"];
        /** ResearchCompatibilityStatus */
        ResearchCompatibilityStatus: core["schemas"]["ResearchCompatibilityStatus"];
        /** ResearchCredentialUpdate */
        ResearchCredentialUpdate: core["schemas"]["ResearchCredentialUpdate"];
        /** ResearchProviderStatus */
        ResearchProviderStatus: core["schemas"]["ResearchProviderStatus"];
        /** ResearchReleaseAvailability */
        ResearchReleaseAvailability: core["schemas"]["ResearchReleaseAvailability"];
        /** ResearchReleaseStatus */
        ResearchReleaseStatus: core["schemas"]["ResearchReleaseStatus"];
        /** ResearchRetentionStatus */
        ResearchRetentionStatus: core["schemas"]["ResearchRetentionStatus"];
        /** ResearchRuntimeStatus */
        ResearchRuntimeStatus: core["schemas"]["ResearchRuntimeStatus"];
        /**
         * ResourceClass
         * @enum {string}
         */
        ResourceClass: core["schemas"]["ResourceClass"];
        /**
         * RetentionRunDiagnostics
         * @description The newest retention run; the error is reported by class only.
         */
        RetentionRunDiagnostics: core["schemas"]["RetentionRunDiagnostics"];
        /** RetiredWorkerProtocolResponse */
        RetiredWorkerProtocolResponse: core["schemas"]["RetiredWorkerProtocolResponse"];
        /** RetryState */
        RetryState: core["schemas"]["RetryState"];
        /** RetryState */
        "RetryState-Input": core["schemas"]["RetryState-Input"];
        /** RevokeSessionsRequest */
        RevokeSessionsRequest: core["schemas"]["RevokeSessionsRequest"];
        /** RevokeSessionsResponse */
        RevokeSessionsResponse: core["schemas"]["RevokeSessionsResponse"];
        /**
         * RuntimeDiagnostics
         * @description One process's runtime view (WP-10.9); sections are documented in docs/operations/DIAGNOSTICS.md.
         */
        RuntimeDiagnostics: core["schemas"]["RuntimeDiagnostics"];
        /** RuntimeStatusPayload */
        RuntimeStatusPayload: core["schemas"]["RuntimeStatusPayload"];
        /** SendChatMessageRequest */
        SendChatMessageRequest: core["schemas"]["SendChatMessageRequest"];
        /** SendChatMessageResponse */
        SendChatMessageResponse: core["schemas"]["SendChatMessageResponse"];
        /** SettingsPatch */
        SettingsPatch: core["schemas"]["SettingsPatch"];
        /** SettingsPayload */
        SettingsPayload: core["schemas"]["SettingsPayload"];
        /**
         * SettingsProfileSaveRequest
         * @description A Settings Control Center save: a profile patch plus the provider sections it changed.
         *
         *     ``base_revision`` is the profile revision the patch was made against; a
         *     newer profile refuses the save. Provider sections are merged into the
         *     stored settings, and an ``api_key`` in them goes to the secret store
         *     (a masked ``***`` value leaves the stored key unchanged).
         */
        SettingsProfileSaveRequest: core["schemas"]["SettingsProfileSaveRequest"];
        /** SettingsSaveResponse */
        SettingsSaveResponse: core["schemas"]["SettingsSaveResponse"];
        /** StateHashRequest */
        StateHashRequest: core["schemas"]["StateHashRequest"];
        /** StateHashResponse */
        StateHashResponse: core["schemas"]["StateHashResponse"];
        /** ValidationError */
        ValidationError: core["schemas"]["ValidationError"];
        /** VersionDiagnostics */
        VersionDiagnostics: core["schemas"]["VersionDiagnostics"];
        /** WorkerHealth */
        WorkerHealth: core["schemas"]["WorkerHealth"];
        /** WorkerHealthPayload */
        WorkerHealthPayload: core["schemas"]["WorkerHealthPayload"];
        /** WorkerHealthSummary */
        WorkerHealthSummary: core["schemas"]["WorkerHealthSummary"];
        /** WorkerPayloadPolicy */
        WorkerPayloadPolicy: core["schemas"]["WorkerPayloadPolicy"];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    image_asset_file_api_assets__asset_id__file_get: {
        parameters: {
            query?: {
                download?: boolean;
                preview?: boolean;
            };
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Image asset bytes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/gif": string;
                    "image/jpeg": string;
                    "image/png": string;
                    "image/svg+xml": string;
                    "image/webp": string;
                };
            };
            /** @description The cached image is current */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The image asset was not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The asset is not a supported image */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    image_assets_api_image_generation_assets_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicAssetListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_image_asset_api_image_generation_assets__asset_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageAssetDeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_image_asset_api_image_generation_assets__asset_id__delete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageAssetDeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    image_jobs_api_image_generation_jobs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_image_job_api_image_generation_jobs__job_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_image_model_api_image_generation_model_download_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImageModelDownloadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageModelStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ensure_image_model_loaded_api_image_generation_model_ensure_loaded_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImageModelActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageModelStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    load_image_model_api_image_generation_model_load_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImageModelActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageModelStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    image_model_status_api_image_generation_model_status_get: {
        parameters: {
            query?: {
                provider?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageModelStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unload_image_model_api_image_generation_model_unload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImageModelActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageModelStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    image_references_api_image_generation_references_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicAssetListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_image_reference_api_image_generation_references_post: {
        parameters: {
            query?: {
                filename?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
                "image/jpeg": string;
                "image/png": string;
                "image/webp": string;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageReferenceUploadResponse"];
                };
            };
            /** @description The upload is empty, invalid, or unsupported */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    start_image_service_api_image_generation_service_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImageModelActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageModelStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
