"""Assistant web research contracts and services."""

from .contracts import (
    DeepResearchResult,
    QuickSearchResult,
    RESEARCH_JOB_MODULE,
    RESEARCH_JOB_TYPE,
    RESEARCH_STAGE_IDS,
    ResearchAnswerSection,
    ResearchDiagnostics,
    ResearchEvidence,
    ResearchMessageMetadata,
    ResearchMode,
    ResearchModeResolution,
    ResearchQuery,
    ResearchResult,
    ResearchSource,
    ResearchSourceSnapshot,
    ResearchWarning,
    normalize_research_mode,
    resolve_research_mode,
)
from .source_store import (
    RecordedResearchSources,
    ResearchSourceManifest,
    ResearchSourceStore,
    canonicalize_source_url,
    default_research_source_store,
    stable_source_record_id,
)

__all__ = [
    "DeepResearchResult",
    "QuickSearchResult",
    "RESEARCH_JOB_MODULE",
    "RESEARCH_JOB_TYPE",
    "RESEARCH_STAGE_IDS",
    "RecordedResearchSources",
    "ResearchAnswerSection",
    "ResearchDiagnostics",
    "ResearchEvidence",
    "ResearchMessageMetadata",
    "ResearchMode",
    "ResearchModeResolution",
    "ResearchQuery",
    "ResearchResult",
    "ResearchSource",
    "ResearchSourceManifest",
    "ResearchSourceSnapshot",
    "ResearchSourceStore",
    "ResearchWarning",
    "canonicalize_source_url",
    "default_research_source_store",
    "normalize_research_mode",
    "resolve_research_mode",
    "stable_source_record_id",
]
