// The Pine template corpus (TVP-11.0): every indicator's "view as Pine" source, with the chart's default inputs
// filled in. src/tests/trading/test_trading_scripts_corpus.py runs each through the Omnix Scripts interpreter and
// compares its plots with the server's native indicator. Run with UPDATE_PINE_CORPUS=1 to rewrite the fixture.
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import type { CoreIndicatorId } from './coreIndicators';
import { allIndicatorPineSources, indicatorPineSource } from './indicatorPine';
import { newIndicatorInstance } from '../tradingStore';

// Tests run from the web package directory.
const FIXTURE = resolve(process.cwd(), 'src/features/trading/indicators/fixtures/pineTemplateCorpus.json');

describe('Pine template corpus (TVP-11.0)', () => {
  it('records each template with the inputs of the chart default instance', () => {
    const entries = Object.keys(allIndicatorPineSources()).sort().map((id) => {
      const instance = newIndicatorInstance(id as CoreIndicatorId);
      return {
        id,
        inputs: {
          period: instance.period,
          fastPeriod: instance.fastPeriod ?? null,
          slowPeriod: instance.slowPeriod ?? null,
          signalPeriod: instance.signalPeriod ?? null,
          standardDeviations: instance.standardDeviations ?? null,
        },
        source: indicatorPineSource(instance),
      };
    });
    const corpus = { note: 'Generated by indicatorPineCorpus.test.ts; do not edit.', entries };
    if (process.env.UPDATE_PINE_CORPUS === '1') writeFileSync(FIXTURE, `${JSON.stringify(corpus, null, 1)}\n`);
    expect(JSON.parse(readFileSync(FIXTURE, 'utf-8'))).toEqual(corpus);
  });
});
