import { CaptureDefaults } from './CaptureDefaults';
import { SettingsField, SettingsSection } from './SettingsPrimitives';
import { useSettingsProfileContext } from './SettingsProfileContext';

export function ImageSpeechSettings() {
  const { state, dispatch } = useSettingsProfileContext();
  const image = state.draft.image;
  return <div><h2>Images & Speech Input</h2><SettingsSection title="Image generation" scope="module"><div className="settings-form-grid"><SettingsField label="Width"><input type="number" min="128" max="4096" step="64" value={image.width} onChange={(event) => dispatch({ type: 'update', path: 'image.width', value: Number(event.currentTarget.value) })} /></SettingsField><SettingsField label="Height"><input type="number" min="128" max="4096" step="64" value={image.height} onChange={(event) => dispatch({ type: 'update', path: 'image.height', value: Number(event.currentTarget.value) })} /></SettingsField><SettingsField label="Aspect ratio"><select value={image.aspectRatio} onChange={(event) => dispatch({ type: 'update', path: 'image.aspectRatio', value: event.currentTarget.value })}><option value="1:1">1:1</option><option value="4:3">4:3</option><option value="3:4">3:4</option><option value="16:9">16:9</option></select></SettingsField><SettingsField label="Portrait preset"><input value={image.portraitPreset} onChange={(event) => dispatch({ type: 'update', path: 'image.portraitPreset', value: event.currentTarget.value })} /></SettingsField><SettingsField label="Scene preset"><input value={image.scenePreset} onChange={(event) => dispatch({ type: 'update', path: 'image.scenePreset', value: event.currentTarget.value })} /></SettingsField></div><div className="settings-toggle-list"><label><input type="checkbox" checked={image.unloadAfterGeneration} onChange={(event) => dispatch({ type: 'update', path: 'image.unloadAfterGeneration', value: event.currentTarget.checked })} /><span>Unload model after generation</span></label></div></SettingsSection><CaptureDefaults /></div>;
}
