import { useEffect } from 'react';
import { saveStoryReadSettings } from '../storyteller/storyReadSettings';
import { SettingsField, SettingsSection } from './SettingsPrimitives';
import { useSettingsProfileContext } from './SettingsProfileContext';

export function NarrativeSettings() {
  const { state, dispatch } = useSettingsProfileContext();
  const story = state.draft.storyteller;
  const episode = state.draft.podcast;
  useEffect(() => saveStoryReadSettings({ pronunciationDictionary: '', pauseAfterParagraphMs: story.pauseParagraphMs, pauseAfterChapterMs: story.pauseChapterMs, readChapterTitles: story.readChapterTitles, speed: story.readSpeed, stylePreset: story.readStylePreset }), [story]);
  return <div><SettingsSection title="Narrative defaults" scope="module"><div className="settings-form-grid"><SettingsField label="Tone"><input value={story.tone} onChange={(event) => dispatch({ type: 'update', path: 'storyteller.tone', value: event.currentTarget.value })} /></SettingsField><SettingsField label="Writing style"><input value={story.writingStyle} onChange={(event) => dispatch({ type: 'update', path: 'storyteller.writingStyle', value: event.currentTarget.value })} /></SettingsField><SettingsField label="Reading speed"><input type="number" value={story.readSpeed} onChange={(event) => dispatch({ type: 'update', path: 'storyteller.readSpeed', value: Number(event.currentTarget.value) })} /></SettingsField><SettingsField label="Paragraph pause"><input type="number" value={story.pauseParagraphMs} onChange={(event) => dispatch({ type: 'update', path: 'storyteller.pauseParagraphMs', value: Number(event.currentTarget.value) })} /></SettingsField></div></SettingsSection><SettingsSection title="Episode defaults" scope="module"><div className="settings-form-grid"><SettingsField label="Format"><input value={episode.format} onChange={(event) => dispatch({ type: 'update', path: 'podcast.format', value: event.currentTarget.value })} /></SettingsField><SettingsField label="Duration"><input type="number" value={episode.durationMinutes} onChange={(event) => dispatch({ type: 'update', path: 'podcast.durationMinutes', value: Number(event.currentTarget.value) })} /></SettingsField><SettingsField label="Tone"><input value={episode.tone} onChange={(event) => dispatch({ type: 'update', path: 'podcast.tone', value: event.currentTarget.value })} /></SettingsField><SettingsField label="Language"><input value={episode.language} onChange={(event) => dispatch({ type: 'update', path: 'podcast.language', value: event.currentTarget.value })} /></SettingsField></div></SettingsSection></div>;
}
