import { useEffect } from 'react';
import { saveStoryReadSettings } from '../storyteller/storyReadSettings';
import { SettingsField, SettingsSection } from './SettingsPrimitives';
import { useSettingsProfileContext } from './SettingsProfileContext';

export function StoryDefaultsSettings() {
  const { state, dispatch } = useSettingsProfileContext();
  const value = state.draft.storyteller;
  useEffect(() => saveStoryReadSettings({ pronunciationDictionary: '', pauseAfterParagraphMs: value.pauseParagraphMs, pauseAfterChapterMs: value.pauseChapterMs, readChapterTitles: value.readChapterTitles, speed: value.readSpeed, stylePreset: value.readStylePreset }), [value]);
  return <><SettingsSection title="Storyteller" scope="module"><div className="settings-form-grid"><SettingsField label="Tone"><select value={value.tone} onChange={(event) => dispatch({ type: 'update', path: 'storyteller.tone', value: event.currentTarget.value })}><option>Cozy</option><option>Hopeful</option><option>Gentle</option><option>Mystery</option></select></SettingsField><SettingsField label="Writing style"><select value={value.writingStyle} onChange={(event) => dispatch({ type: 'update', path: 'storyteller.writingStyle', value: event.currentTarget.value })}><option>Lyrical & Descriptive</option><option>Fast-paced</option><option>Dialogue-heavy</option><option>Cinematic</option><option>Literary</option></select></SettingsField></div></SettingsSection><SettingsSection title="Story reading" scope="local"><div className="settings-form-grid"><SettingsField label="Reading speed"><input type="number" min="0.5" max="2" step="0.05" value={value.readSpeed} onChange={(event) => dispatch({ type: 'update', path: 'storyteller.readSpeed', value: Number(event.currentTarget.value) })} /></SettingsField><SettingsField label="Paragraph pause (ms)"><input type="number" min="0" value={value.pauseParagraphMs} onChange={(event) => dispatch({ type: 'update', path: 'storyteller.pauseParagraphMs', value: Number(event.currentTarget.value) })} /></SettingsField><SettingsField label="Chapter pause (ms)"><input type="number" min="0" value={value.pauseChapterMs} onChange={(event) => dispatch({ type: 'update', path: 'storyteller.pauseChapterMs', value: Number(event.currentTarget.value) })} /></SettingsField><SettingsField label="Style preset"><input value={value.readStylePreset} onChange={(event) => dispatch({ type: 'update', path: 'storyteller.readStylePreset', value: event.currentTarget.value })} /></SettingsField></div><div className="settings-toggle-list"><label><input type="checkbox" checked={value.readChapterTitles} onChange={(event) => dispatch({ type: 'update', path: 'storyteller.readChapterTitles', value: event.currentTarget.checked })} /><span>Read chapter titles</span></label></div></SettingsSection></>;
}
