"""Compatibility facade for RPG ability tree and effect helpers.

The implementation is split across focused modules so every RPG source file stays
below the architecture line-limit gate.
"""
from __future__ import annotations

from app.rpg.session.ability_catalog import (
    ABILITY_TEMPLATES,
    BUILD_IDENTITY_DEFAULTS,
    GENRE_CLASS_NAMES,
    GENRE_NORMALIZATION,
    TEMPLATE_FAMILIES,
)
from app.rpg.session.ability_models import (
    ALLOWED_CAPABILITIES,
    ALLOWED_COST_RESOURCES,
    ALLOWED_DIMENSIONS,
    ALLOWED_EFFECT_OPS,
    ALLOWED_KINDS,
    ALLOWED_POWER_SOURCES,
    ALLOWED_PURPOSES,
    ALLOWED_XP_SOURCES,
    DEFAULT_SKILL_XP_PER_ABILITY_USE,
    AbilityKind,
    AbilityPurpose,
    Capability,
    GameplayDimension,
    PowerSource,
    RpgAbilityDefinition,
    RpgAbilityStateResult,
    RpgAbilityUseResult,
    RpgAbilityValidationResult,
    RpgCharacterIdentity,
    RpgEffectOp,
    RpgProgressionResult,
)
from app.rpg.session.ability_runtime import (
    apply_ability_to_state,
    assign_ability_to_hotbar,
    execute_effect_ops,
    grant_player_xp,
    grant_skill_xp,
    hotbar_preview_from_state,
    remove_hotbar_slot,
    skill_modifier_for_check,
    tick_ability_state,
    unlock_ability_in_state,
    upgrade_ability_rank_in_state,
)
from app.rpg.session.ability_tree import (
    build_ability_tree,
    build_initial_ability_state,
    build_progression_package,
    infer_character_identity,
    normalize_capability,
    normalize_genre,
    normalize_power_source,
    validate_ability,
    validate_ability_tree,
)

__all__ = [
    "ABILITY_TEMPLATES",
    "ALLOWED_CAPABILITIES",
    "ALLOWED_COST_RESOURCES",
    "ALLOWED_DIMENSIONS",
    "ALLOWED_EFFECT_OPS",
    "ALLOWED_KINDS",
    "ALLOWED_POWER_SOURCES",
    "ALLOWED_PURPOSES",
    "ALLOWED_XP_SOURCES",
    "AbilityKind",
    "AbilityPurpose",
    "BUILD_IDENTITY_DEFAULTS",
    "Capability",
    "DEFAULT_SKILL_XP_PER_ABILITY_USE",
    "GENRE_CLASS_NAMES",
    "GENRE_NORMALIZATION",
    "GameplayDimension",
    "PowerSource",
    "RpgAbilityDefinition",
    "RpgAbilityStateResult",
    "RpgAbilityUseResult",
    "RpgAbilityValidationResult",
    "RpgCharacterIdentity",
    "RpgEffectOp",
    "RpgProgressionResult",
    "TEMPLATE_FAMILIES",
    "apply_ability_to_state",
    "assign_ability_to_hotbar",
    "build_ability_tree",
    "build_initial_ability_state",
    "build_progression_package",
    "execute_effect_ops",
    "grant_player_xp",
    "grant_skill_xp",
    "hotbar_preview_from_state",
    "infer_character_identity",
    "normalize_capability",
    "normalize_genre",
    "normalize_power_source",
    "remove_hotbar_slot",
    "skill_modifier_for_check",
    "tick_ability_state",
    "unlock_ability_in_state",
    "upgrade_ability_rank_in_state",
    "validate_ability",
    "validate_ability_tree",
]
