/**
 * Generated by scripts/generate-api-types.mjs from openapi.json and route-owners.json; do not edit.
 */
import type { components as core } from '../../../api/generated/core';

export interface paths {
    "/api/jobs/voice-summaries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Voice Job Summaries */
        get: operations["voice_job_summaries_api_jobs_voice_summaries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stt/authorityz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Authority */
        get: operations["authority_api_stt_authorityz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stt/transcribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transcribe */
        post: operations["transcribe_api_stt_transcribe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tts/runtime/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_tts_runtime_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tts/runtime/unload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unload */
        post: operations["unload_api_tts_runtime_unload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tts/runtime/warmup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Warmup */
        post: operations["warmup_api_tts_runtime_warmup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voice-library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Voice Library */
        get: operations["voice_library_api_voice_library_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountResponse */
        AccountResponse: core["schemas"]["AccountResponse"];
        /** AssetContentResponse */
        AssetContentResponse: core["schemas"]["AssetContentResponse"];
        /** AssetLegacyRootScan */
        AssetLegacyRootScan: core["schemas"]["AssetLegacyRootScan"];
        /**
         * AssetType
         * @enum {string}
         */
        AssetType: core["schemas"]["AssetType"];
        /**
         * AssistantToolAction
         * @description Backend-owned action definition for an assistant tool.
         */
        AssistantToolAction: core["schemas"]["AssistantToolAction"];
        /**
         * AssistantToolRegistryPayload
         * @description Serializable backend mirror of assistant tools and actions.
         */
        AssistantToolRegistryPayload: core["schemas"]["AssistantToolRegistryPayload"];
        /**
         * AssistantToolSpec
         * @description Backend-owned assistant tool metadata and actions.
         */
        AssistantToolSpec: core["schemas"]["AssistantToolSpec"];
        /**
         * AuthOptionsResponse
         * @description How someone may sign in here; the sign-in page shows only these.
         */
        AuthOptionsResponse: core["schemas"]["AuthOptionsResponse"];
        /** AuthSessionListResponse */
        AuthSessionListResponse: core["schemas"]["AuthSessionListResponse"];
        /** AuthSessionResponse */
        AuthSessionResponse: core["schemas"]["AuthSessionResponse"];
        /** AuthSessionSummary */
        AuthSessionSummary: core["schemas"]["AuthSessionSummary"];
        /** CancelJobRequest */
        CancelJobRequest: core["schemas"]["CancelJobRequest"];
        /** CancelState */
        CancelState: core["schemas"]["CancelState"];
        /** ChatMessage */
        ChatMessage: core["schemas"]["ChatMessage"];
        /** ChatSession */
        ChatSession: core["schemas"]["ChatSession"];
        /** ChatSessionListResponse */
        ChatSessionListResponse: core["schemas"]["ChatSessionListResponse"];
        /** ChatSessionSummary */
        ChatSessionSummary: core["schemas"]["ChatSessionSummary"];
        /**
         * ChatTextAttachment
         * @description A small, UTF-8 text file attached to a chat turn.
         *
         *     Binary files are deliberately not accepted through the JSON chat API.  The
         *     browser reads supported text documents before sending them, which keeps the
         *     stored transcript and every provider prompt self-contained.
         */
        ChatTextAttachment: core["schemas"]["ChatTextAttachment"];
        /**
         * CheckpointBundleRequest
         * @description Extensible state bundle with explicit checkpoint control fields.
         */
        CheckpointBundleRequest: core["schemas"]["CheckpointBundleRequest"];
        /** CheckpointEnvelope */
        CheckpointEnvelope: core["schemas"]["CheckpointEnvelope"];
        /** ClaimJobRequest */
        ClaimJobRequest: core["schemas"]["ClaimJobRequest"];
        /** ClaimJobResponse */
        ClaimJobResponse: core["schemas"]["ClaimJobResponse"];
        /** ClientErrorAccepted */
        ClientErrorAccepted: core["schemas"]["ClientErrorAccepted"];
        /** ClientErrorReport */
        ClientErrorReport: core["schemas"]["ClientErrorReport"];
        /** CodexAuthStatus */
        CodexAuthStatus: core["schemas"]["CodexAuthStatus"];
        /** CoinMarketCapCredentialStatus */
        CoinMarketCapCredentialStatus: core["schemas"]["CoinMarketCapCredentialStatus"];
        /** CoinMarketCapCredentialUpdate */
        CoinMarketCapCredentialUpdate: core["schemas"]["CoinMarketCapCredentialUpdate"];
        /** CompatibilityHandoffPayload */
        CompatibilityHandoffPayload: core["schemas"]["CompatibilityHandoffPayload"];
        /** CompleteJobRequest */
        CompleteJobRequest: core["schemas"]["CompleteJobRequest"];
        /**
         * CreateChatSessionRequest
         * @description Client selection; trusted identity/profile content is intentionally absent.
         */
        CreateChatSessionRequest: core["schemas"]["CreateChatSessionRequest"];
        /** CreateJobRequest */
        CreateJobRequest: core["schemas"]["CreateJobRequest"];
        /** DeleteChatSessionResponse */
        DeleteChatSessionResponse: core["schemas"]["DeleteChatSessionResponse"];
        /** DiagnosticsPayload */
        DiagnosticsPayload: core["schemas"]["DiagnosticsPayload"];
        /** EmailChangeRequest */
        EmailChangeRequest: core["schemas"]["EmailChangeRequest"];
        /**
         * EventReaderDiagnostics
         * @description Live job events in this process (WP-5.4).
         */
        EventReaderDiagnostics: core["schemas"]["EventReaderDiagnostics"];
        /** FailJobRequest */
        FailJobRequest: core["schemas"]["FailJobRequest"];
        /** GatewayHealth */
        GatewayHealth: core["schemas"]["GatewayHealth"];
        /**
         * GatewayReadinessPayload
         * @description Stable readiness fields plus deployment-specific diagnostic fields.
         */
        GatewayReadinessPayload: core["schemas"]["GatewayReadinessPayload"];
        /** GpuResidencyPolicy */
        GpuResidencyPolicy: core["schemas"]["GpuResidencyPolicy"];
        /** GuestUpgradeRequest */
        GuestUpgradeRequest: core["schemas"]["GuestUpgradeRequest"];
        /** HTTPValidationError */
        HTTPValidationError: core["schemas"]["HTTPValidationError"];
        /** HermesDiagnosticsPaths */
        HermesDiagnosticsPaths: core["schemas"]["HermesDiagnosticsPaths"];
        /**
         * HermesStatusResponse
         * @description Sidecar reachability and the runtime configuration that reaches it.
         */
        HermesStatusResponse: core["schemas"]["HermesStatusResponse"];
        /** IbkrSettingsPayload */
        IbkrSettingsPayload: core["schemas"]["IbkrSettingsPayload"];
        /** IbkrSettingsStatus */
        IbkrSettingsStatus: core["schemas"]["IbkrSettingsStatus"];
        /** IbkrSettingsUpdate */
        IbkrSettingsUpdate: core["schemas"]["IbkrSettingsUpdate"];
        /** InviteCheckResponse */
        InviteCheckResponse: core["schemas"]["InviteCheckResponse"];
        /** InviteListResponse */
        InviteListResponse: core["schemas"]["InviteListResponse"];
        /** InviteRequest */
        InviteRequest: core["schemas"]["InviteRequest"];
        /** InviteResponse */
        InviteResponse: core["schemas"]["InviteResponse"];
        /** InviteSummaryResponse */
        InviteSummaryResponse: core["schemas"]["InviteSummaryResponse"];
        /** JobError */
        JobError: core["schemas"]["JobError"];
        /** JobError */
        "JobError-Input": core["schemas"]["JobError-Input"];
        /** JobLease */
        JobLease: core["schemas"]["JobLease"];
        /**
         * JobListResponse
         * @description A page of jobs, newest first (WP-5.5).
         */
        JobListResponse: core["schemas"]["JobListResponse"];
        /** JobProgress */
        JobProgress: core["schemas"]["JobProgress"];
        /** JobProgress */
        "JobProgress-Input": core["schemas"]["JobProgress-Input"];
        /** JobRecord */
        JobRecord: core["schemas"]["JobRecord"];
        /** JobStage */
        JobStage: core["schemas"]["JobStage"];
        /** JobStage */
        "JobStage-Input": core["schemas"]["JobStage-Input"];
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: core["schemas"]["JobStatus"];
        /** LegacyGenerateTitleRequest */
        LegacyGenerateTitleRequest: core["schemas"]["LegacyGenerateTitleRequest"];
        /** LegacyGenerateTitleResponse */
        LegacyGenerateTitleResponse: core["schemas"]["LegacyGenerateTitleResponse"];
        /** LegacySessionCreateResponse */
        LegacySessionCreateResponse: core["schemas"]["LegacySessionCreateResponse"];
        /** LegacySessionListItem */
        LegacySessionListItem: core["schemas"]["LegacySessionListItem"];
        /** LegacySessionListResponse */
        LegacySessionListResponse: core["schemas"]["LegacySessionListResponse"];
        /** LegacySessionResponse */
        LegacySessionResponse: core["schemas"]["LegacySessionResponse"];
        /** LegacySessionUpdateRequest */
        LegacySessionUpdateRequest: core["schemas"]["LegacySessionUpdateRequest"];
        /** LegacySuccessResponse */
        LegacySuccessResponse: core["schemas"]["LegacySuccessResponse"];
        /** LocalLoginRequest */
        LocalLoginRequest: core["schemas"]["LocalLoginRequest"];
        /** ModelResidencyDiagnostics */
        ModelResidencyDiagnostics: core["schemas"]["ModelResidencyDiagnostics"];
        /** ModelResidencyRecord */
        ModelResidencyRecord: core["schemas"]["ModelResidencyRecord"];
        /** ModelResidencyRecord */
        "ModelResidencyRecord-Input": core["schemas"]["ModelResidencyRecord-Input"];
        /**
         * ModelResidencyStatus
         * @enum {string}
         */
        ModelResidencyStatus: core["schemas"]["ModelResidencyStatus"];
        /** ModelSummary */
        ModelSummary: core["schemas"]["ModelSummary"];
        /** PasswordChangeRequest */
        PasswordChangeRequest: core["schemas"]["PasswordChangeRequest"];
        /** PasswordChangeResponse */
        PasswordChangeResponse: core["schemas"]["PasswordChangeResponse"];
        /** PasswordLoginRequest */
        PasswordLoginRequest: core["schemas"]["PasswordLoginRequest"];
        /** PersistenceInventory */
        PersistenceInventory: core["schemas"]["PersistenceInventory"];
        /** PromptRenderRequest */
        PromptRenderRequest: core["schemas"]["PromptRenderRequest"];
        /** PromptTemplate */
        PromptTemplate: core["schemas"]["PromptTemplate"];
        /**
         * ProviderCapability
         * @enum {string}
         */
        ProviderCapability: core["schemas"]["ProviderCapability"];
        /** ProviderFacadePayload */
        ProviderFacadePayload: core["schemas"]["ProviderFacadePayload"];
        /**
         * ProviderKeyStatus
         * @description An API key's status for providers configured by one key (FRED, TVP-10.5): never the key itself.
         */
        ProviderKeyStatus: core["schemas"]["ProviderKeyStatus"];
        /** ProviderModelCacheEntry */
        ProviderModelCacheEntry: core["schemas"]["ProviderModelCacheEntry"];
        /** ProviderModelCachePayload */
        ProviderModelCachePayload: core["schemas"]["ProviderModelCachePayload"];
        /** ProviderModelRefreshRequest */
        ProviderModelRefreshRequest: core["schemas"]["ProviderModelRefreshRequest"];
        /** ProviderSummary */
        ProviderSummary: core["schemas"]["ProviderSummary"];
        /** PublicAssetLegacyImportDryRun */
        PublicAssetLegacyImportDryRun: core["schemas"]["PublicAssetLegacyImportDryRun"];
        /**
         * PublicAssetListResponse
         * @description ``AssetListResponse`` as the API returns it.
         */
        PublicAssetListResponse: core["schemas"]["PublicAssetListResponse"];
        /** PublicAssetMigrationPreview */
        PublicAssetMigrationPreview: core["schemas"]["PublicAssetMigrationPreview"];
        /**
         * PublicAssetRecord
         * @description An asset as the API returns it: ids and URLs, never where its bytes are
         *     stored (WP-4.10). Built from an ``AssetRecord``: the storage path and key
         *     and the legacy ``compat`` block are left out, absolute paths in metadata
         *     become file names.
         */
        PublicAssetRecord: core["schemas"]["PublicAssetRecord"];
        /** RedirectUrlResponse */
        RedirectUrlResponse: core["schemas"]["RedirectUrlResponse"];
        /** RegisterRequest */
        RegisterRequest: core["schemas"]["RegisterRequest"];
        /** RenderedPrompt */
        RenderedPrompt: core["schemas"]["RenderedPrompt"];
        /** ReplayPrimitive */
        ReplayPrimitive: core["schemas"]["ReplayPrimitive"];
        /** ReplayPrimitiveList */
        ReplayPrimitiveList: core["schemas"]["ReplayPrimitiveList"];
        /** ReportArtifact */
        ReportArtifact: core["schemas"]["ReportArtifact"];
        /** ReportListResponse */
        ReportListResponse: core["schemas"]["ReportListResponse"];
        /** ResearchBudgetStatus */
        ResearchBudgetStatus: core["schemas"]["ResearchBudgetStatus"];
        /** ResearchCompatibilityStatus */
        ResearchCompatibilityStatus: core["schemas"]["ResearchCompatibilityStatus"];
        /** ResearchCredentialUpdate */
        ResearchCredentialUpdate: core["schemas"]["ResearchCredentialUpdate"];
        /** ResearchProviderStatus */
        ResearchProviderStatus: core["schemas"]["ResearchProviderStatus"];
        /** ResearchReleaseAvailability */
        ResearchReleaseAvailability: core["schemas"]["ResearchReleaseAvailability"];
        /** ResearchReleaseStatus */
        ResearchReleaseStatus: core["schemas"]["ResearchReleaseStatus"];
        /** ResearchRetentionStatus */
        ResearchRetentionStatus: core["schemas"]["ResearchRetentionStatus"];
        /** ResearchRuntimeStatus */
        ResearchRuntimeStatus: core["schemas"]["ResearchRuntimeStatus"];
        /**
         * ResourceClass
         * @enum {string}
         */
        ResourceClass: core["schemas"]["ResourceClass"];
        /**
         * RetentionRunDiagnostics
         * @description The newest retention run; the error is reported by class only.
         */
        RetentionRunDiagnostics: core["schemas"]["RetentionRunDiagnostics"];
        /** RetiredWorkerProtocolResponse */
        RetiredWorkerProtocolResponse: core["schemas"]["RetiredWorkerProtocolResponse"];
        /** RetryState */
        RetryState: core["schemas"]["RetryState"];
        /** RetryState */
        "RetryState-Input": core["schemas"]["RetryState-Input"];
        /** RevokeSessionsRequest */
        RevokeSessionsRequest: core["schemas"]["RevokeSessionsRequest"];
        /** RevokeSessionsResponse */
        RevokeSessionsResponse: core["schemas"]["RevokeSessionsResponse"];
        /**
         * RuntimeDiagnostics
         * @description One process's runtime view (WP-10.9); sections are documented in docs/operations/DIAGNOSTICS.md.
         */
        RuntimeDiagnostics: core["schemas"]["RuntimeDiagnostics"];
        /** RuntimeStatusPayload */
        RuntimeStatusPayload: core["schemas"]["RuntimeStatusPayload"];
        /**
         * STTProxyResponse
         * @description Known fields in the configured STT service response, with forward compatibility.
         */
        STTProxyResponse: {
            /** Duration */
            duration: number | null;
            /** Eligible */
            eligible: boolean | null;
            /** Inference Ms */
            inference_ms: number | null;
            /** Mode */
            mode: string | null;
            /** Ok */
            ok: boolean | null;
            /** Provider */
            provider: string | null;
            /** Reasons */
            reasons: string[] | null;
            /** Segments */
            segments: {
                [key: string]: unknown;
            }[] | null;
            /** Success */
            success: boolean | null;
            /** Text */
            text: string | null;
        } & {
            [key: string]: unknown;
        };
        /** SendChatMessageRequest */
        SendChatMessageRequest: core["schemas"]["SendChatMessageRequest"];
        /** SendChatMessageResponse */
        SendChatMessageResponse: core["schemas"]["SendChatMessageResponse"];
        /** SettingsPatch */
        SettingsPatch: core["schemas"]["SettingsPatch"];
        /** SettingsPayload */
        SettingsPayload: core["schemas"]["SettingsPayload"];
        /**
         * SettingsProfileSaveRequest
         * @description A Settings Control Center save: a profile patch plus the provider sections it changed.
         *
         *     ``base_revision`` is the profile revision the patch was made against; a
         *     newer profile refuses the save. Provider sections are merged into the
         *     stored settings, and an ``api_key`` in them goes to the secret store
         *     (a masked ``***`` value leaves the stored key unchanged).
         */
        SettingsProfileSaveRequest: core["schemas"]["SettingsProfileSaveRequest"];
        /** SettingsSaveResponse */
        SettingsSaveResponse: core["schemas"]["SettingsSaveResponse"];
        /** StateHashRequest */
        StateHashRequest: core["schemas"]["StateHashRequest"];
        /** StateHashResponse */
        StateHashResponse: core["schemas"]["StateHashResponse"];
        /** ValidationError */
        ValidationError: core["schemas"]["ValidationError"];
        /** VersionDiagnostics */
        VersionDiagnostics: core["schemas"]["VersionDiagnostics"];
        /** WorkerHealth */
        WorkerHealth: core["schemas"]["WorkerHealth"];
        /** WorkerHealthPayload */
        WorkerHealthPayload: core["schemas"]["WorkerHealthPayload"];
        /** WorkerHealthSummary */
        WorkerHealthSummary: core["schemas"]["WorkerHealthSummary"];
        /** WorkerPayloadPolicy */
        WorkerPayloadPolicy: core["schemas"]["WorkerPayloadPolicy"];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    voice_job_summaries_api_jobs_voice_summaries_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    authority_api_stt_authorityz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["STTProxyResponse"];
                };
            };
        };
    };
    transcribe_api_stt_transcribe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["STTProxyResponse"];
                };
            };
        };
    };
    status_api_tts_runtime_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    unload_api_tts_runtime_unload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    warmup_api_tts_runtime_warmup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    voice_library_api_voice_library_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicAssetListResponse"];
                };
            };
        };
    };
}
