"""Continuous Companion Activity Runtime."""

from .authority import (
    ActivityAuthoritySource,
    ActivityFieldPolicy,
    DEFAULT_ACTIVITY_FIELD_POLICIES,
    activity_field_policy,
    authority_source_for,
)
from .channels import ChannelAction, ChannelPlan, CompanionChannelCoordinator
from .cognition import (
    CognitionResult,
    CompanionCognition,
    DeliveryIntent,
    DeliveryIntentKind,
    MemoryCandidate,
    OpenLoopEffect,
    StateEffects,
)
from .contracts import (
    EvidenceInheritedPolicy,
    EvidenceLink,
    EvidenceProposition,
    EvidenceRelation,
    EvidenceSourceKind,
    TRUST_BEARING_RELATIONS,
    derive_proposition,
    inherit_evidence_policy,
)
from .delivery_quality import (
    CompanionDeliveryQualityMetrics,
    CompanionDeliveryQualityScorer,
    DeliveryQualityFeatures,
    DeliveryQualityMetricsSnapshot,
    DeliveryQualityOutcome,
    DeliveryQualityScore,
)
from .embodiment import (
    CompanionEmbodimentMapper,
    EmbodimentPlan,
    RendererCapabilities,
    SemanticEmbodimentCue,
    SemanticEmbodimentState,
)
from .evaluation import (
    CompanionReleaseEvidence,
    CompanionReleaseGate,
    CompanionReleaseGatePolicy,
    CompanionReleaseGateReport,
    CompanionReplayEvaluator,
    ReplayExpectation,
    ReplayScenario,
    ReplayScenarioResult,
    ReplayStep,
    ReplayViolation,
)
from .initiative import (
    CompanionInitiativeAuthority,
    InitiativeAcquireRequest,
    InitiativeChannel,
    InitiativeDecision,
    InitiativeInterruptibility,
    InitiativeLease,
    InitiativeSnapshot,
    InitiativeUrgency,
    default_companion_initiative_authority,
)
from .integrations import (
    CompanionIntegrationEvidenceAdapter,
    IntegrationEvidenceInput,
    IntegrationKind,
)
from .persistence import (
    ActivityCheckpointReason,
    CheckpointDecision,
    CompanionActivityCheckpoint,
    CompanionActivityRecovery,
    CompanionCheckpointPolicy,
    InMemoryCompanionActivityCheckpointStore,
    PostgresCompanionActivityCheckpointStore,
    build_activity_checkpoint,
)
from .presence import (
    CompanionPresenceDecision,
    CompanionPresenceInput,
    CompanionPresencePolicy,
    PresenceMode,
)
from .progress import ActivityProgressReducer, PROGRESS_PREDICATES
from .reducer import ActivityReducer
from .runtime import ActivityRuntimeResult, CompanionActivityRuntime
from .state import (
    ActivityField,
    ActivityMeaningfulEvent,
    ActivityOpenLoop,
    ActivityProgressMarker,
    ActivityReductionResult,
    ActivityStateChange,
    ActivityStrategyChange,
    ActivityTransitionCandidate,
    CompanionActivityState,
    OpenLoopStatus,
    empty_activity_state,
)

__all__ = [
    "ActivityAuthoritySource",
    "ActivityCheckpointReason",
    "ActivityField",
    "ActivityFieldPolicy",
    "ActivityMeaningfulEvent",
    "ActivityOpenLoop",
    "ActivityProgressMarker",
    "ActivityProgressReducer",
    "ActivityReducer",
    "ActivityReductionResult",
    "ActivityRuntimeResult",
    "ActivityStateChange",
    "ActivityStrategyChange",
    "ActivityTransitionCandidate",
    "ChannelAction",
    "ChannelPlan",
    "CheckpointDecision",
    "CognitionResult",
    "CompanionActivityCheckpoint",
    "CompanionActivityRecovery",
    "CompanionActivityRuntime",
    "CompanionActivityState",
    "CompanionChannelCoordinator",
    "CompanionCheckpointPolicy",
    "CompanionCognition",
    "CompanionDeliveryQualityMetrics",
    "CompanionDeliveryQualityScorer",
    "CompanionEmbodimentMapper",
    "CompanionInitiativeAuthority",
    "CompanionIntegrationEvidenceAdapter",
    "CompanionPresenceDecision",
    "CompanionPresenceInput",
    "CompanionPresencePolicy",
    "CompanionReleaseEvidence",
    "CompanionReleaseGate",
    "CompanionReleaseGatePolicy",
    "CompanionReleaseGateReport",
    "CompanionReplayEvaluator",
    "DEFAULT_ACTIVITY_FIELD_POLICIES",
    "DeliveryIntent",
    "DeliveryIntentKind",
    "DeliveryQualityFeatures",
    "DeliveryQualityMetricsSnapshot",
    "DeliveryQualityOutcome",
    "DeliveryQualityScore",
    "EmbodimentPlan",
    "EvidenceInheritedPolicy",
    "EvidenceLink",
    "EvidenceProposition",
    "EvidenceRelation",
    "EvidenceSourceKind",
    "InMemoryCompanionActivityCheckpointStore",
    "InitiativeAcquireRequest",
    "InitiativeChannel",
    "InitiativeDecision",
    "InitiativeInterruptibility",
    "InitiativeLease",
    "InitiativeSnapshot",
    "InitiativeUrgency",
    "IntegrationEvidenceInput",
    "IntegrationKind",
    "MemoryCandidate",
    "OpenLoopEffect",
    "OpenLoopStatus",
    "PROGRESS_PREDICATES",
    "PostgresCompanionActivityCheckpointStore",
    "PresenceMode",
    "RendererCapabilities",
    "ReplayExpectation",
    "ReplayScenario",
    "ReplayScenarioResult",
    "ReplayStep",
    "ReplayViolation",
    "SemanticEmbodimentCue",
    "SemanticEmbodimentState",
    "StateEffects",
    "TRUST_BEARING_RELATIONS",
    "activity_field_policy",
    "authority_source_for",
    "build_activity_checkpoint",
    "default_companion_initiative_authority",
    "derive_proposition",
    "empty_activity_state",
    "inherit_evidence_policy",
]
