"""Continuous Companion Activity Runtime."""

from .authority import (
    ActivityAuthoritySource,
    ActivityFieldPolicy,
    DEFAULT_ACTIVITY_FIELD_POLICIES,
    activity_field_policy,
    authority_source_for,
)
from .channels import ChannelAction, ChannelPlan, CompanionChannelCoordinator
from .cognition import (
    CognitionResult,
    CompanionCognition,
    DeliveryIntent,
    DeliveryIntentKind,
    MemoryCandidate,
    OpenLoopEffect,
    StateEffects,
)
from .contracts import (
    EvidenceInheritedPolicy,
    EvidenceLink,
    EvidenceProposition,
    EvidenceRelation,
    EvidenceSourceKind,
    TRUST_BEARING_RELATIONS,
    derive_proposition,
    inherit_evidence_policy,
)
from .initiative import (
    CompanionInitiativeAuthority,
    InitiativeAcquireRequest,
    InitiativeChannel,
    InitiativeDecision,
    InitiativeInterruptibility,
    InitiativeLease,
    InitiativeSnapshot,
    InitiativeUrgency,
    default_companion_initiative_authority,
)
from .presence import (
    CompanionPresenceDecision,
    CompanionPresenceInput,
    CompanionPresencePolicy,
    PresenceMode,
)
from .progress import ActivityProgressReducer, PROGRESS_PREDICATES
from .reducer import ActivityReducer
from .runtime import ActivityRuntimeResult, CompanionActivityRuntime
from .state import (
    ActivityField,
    ActivityMeaningfulEvent,
    ActivityOpenLoop,
    ActivityProgressMarker,
    ActivityReductionResult,
    ActivityStateChange,
    ActivityStrategyChange,
    ActivityTransitionCandidate,
    CompanionActivityState,
    OpenLoopStatus,
    empty_activity_state,
)

__all__ = [
    "ActivityAuthoritySource",
    "ActivityField",
    "ActivityFieldPolicy",
    "ActivityMeaningfulEvent",
    "ActivityOpenLoop",
    "ActivityProgressMarker",
    "ActivityProgressReducer",
    "ActivityReducer",
    "ActivityReductionResult",
    "ActivityRuntimeResult",
    "ActivityStateChange",
    "ActivityStrategyChange",
    "ActivityTransitionCandidate",
    "ChannelAction",
    "ChannelPlan",
    "CognitionResult",
    "CompanionActivityRuntime",
    "CompanionActivityState",
    "CompanionChannelCoordinator",
    "CompanionCognition",
    "CompanionInitiativeAuthority",
    "CompanionPresenceDecision",
    "CompanionPresenceInput",
    "CompanionPresencePolicy",
    "DEFAULT_ACTIVITY_FIELD_POLICIES",
    "DeliveryIntent",
    "DeliveryIntentKind",
    "EvidenceInheritedPolicy",
    "EvidenceLink",
    "EvidenceProposition",
    "EvidenceRelation",
    "EvidenceSourceKind",
    "InitiativeAcquireRequest",
    "InitiativeChannel",
    "InitiativeDecision",
    "InitiativeInterruptibility",
    "InitiativeLease",
    "InitiativeSnapshot",
    "InitiativeUrgency",
    "MemoryCandidate",
    "OpenLoopEffect",
    "OpenLoopStatus",
    "PROGRESS_PREDICATES",
    "PresenceMode",
    "StateEffects",
    "TRUST_BEARING_RELATIONS",
    "activity_field_policy",
    "authority_source_for",
    "default_companion_initiative_authority",
    "derive_proposition",
    "empty_activity_state",
    "inherit_evidence_policy",
]
