"""Phase 10 presentation API router aggregator."""
from __future__ import annotations

from fastapi import APIRouter

from app.rpg.api.rpg_presentation_core_routes import (
    router as core_router,
    presentation_scene,
    presentation_dialogue,
    presentation_speakers,
    presentation_setup_flow,
    presentation_session_bootstrap,
    presentation_intro_scene,
    presentation_save_load_ux,
    presentation_narrative_recap,
    presentation_character_ui,
    presentation_character_inspector,
    presentation_character_inspector_detail,
    presentation_world_inspector,
)
from app.rpg.api.rpg_presentation_visual_request_routes import (
    router as visual_request_router,
    request_character_portrait,
    complete_character_portrait,
    request_scene_illustration,
    complete_scene_illustration,
    presentation_visual_assets,
    process_rpg_visual_requests,
)
from app.rpg.api.rpg_presentation_session_routes import (
    router as session_router,
    import_character_card,
    export_character_card,
    presentation_gm_trace,
    export_rpg_package,
    import_rpg_package,
    list_rpg_packs,
    preview_rpg_pack,
    apply_rpg_pack,
    bootstrap_rpg_pack,
    start_rpg_from_pack,
    validate_rpg_pack_draft,
    preview_rpg_pack_draft,
    export_rpg_pack_draft,
    build_rpg_template,
    start_rpg_template,
    list_rpg_templates,
    preview_rpg_wizard,
    build_rpg_wizard_setup,
    save_rpg_session,
    list_rpg_sessions,
    load_rpg_session,
    archive_rpg_session,
    get_rpg_memory,
    add_rpg_memory,
    get_rpg_memory_dialogue_context,
    memory_decay,
    export_session_as_package_route,
    import_package_as_session,
)
from app.rpg.api.rpg_presentation_visual_provider_routes import (
    router as visual_provider_router,
    queue_visual_job_route,
    run_visual_queue_once_route,
    visual_queue_stats_route,
    prune_visual_queue_route,
    normalize_visual_queue_route,
    run_one_queued_job_route,
    get_visual_provider_settings_route,
    update_visual_provider_settings_route,
    download_flux_klein_route,
    download_flux_klein_status_route,
    download_visual_provider_model_route,
    load_visual_provider_route,
    unload_visual_provider_route,
    visual_provider_status_route,
    preload_visual_provider_route,
    switch_visual_provider_route,
    cleanup_visual_assets_route,
    visual_inspector,
    memory_inspector,
    gm_tooling,
    reinforce_memory,
    integrity_inspect,
)

rpg_presentation_bp = APIRouter()
rpg_presentation_bp.include_router(core_router)
rpg_presentation_bp.include_router(visual_request_router)
rpg_presentation_bp.include_router(session_router)
rpg_presentation_bp.include_router(visual_provider_router)

__all__ = [
    "rpg_presentation_bp",
    "presentation_scene",
    "presentation_dialogue",
    "presentation_speakers",
    "presentation_setup_flow",
    "presentation_session_bootstrap",
    "presentation_intro_scene",
    "presentation_save_load_ux",
    "presentation_narrative_recap",
    "presentation_character_ui",
    "presentation_character_inspector",
    "presentation_character_inspector_detail",
    "presentation_world_inspector",
    "request_character_portrait",
    "complete_character_portrait",
    "request_scene_illustration",
    "complete_scene_illustration",
    "presentation_visual_assets",
    "process_rpg_visual_requests",
    "import_character_card",
    "export_character_card",
    "presentation_gm_trace",
    "export_rpg_package",
    "import_rpg_package",
    "list_rpg_packs",
    "preview_rpg_pack",
    "apply_rpg_pack",
    "bootstrap_rpg_pack",
    "start_rpg_from_pack",
    "validate_rpg_pack_draft",
    "preview_rpg_pack_draft",
    "export_rpg_pack_draft",
    "build_rpg_template",
    "start_rpg_template",
    "list_rpg_templates",
    "preview_rpg_wizard",
    "build_rpg_wizard_setup",
    "save_rpg_session",
    "list_rpg_sessions",
    "load_rpg_session",
    "archive_rpg_session",
    "get_rpg_memory",
    "add_rpg_memory",
    "get_rpg_memory_dialogue_context",
    "memory_decay",
    "export_session_as_package_route",
    "import_package_as_session",
    "queue_visual_job_route",
    "run_visual_queue_once_route",
    "visual_queue_stats_route",
    "prune_visual_queue_route",
    "normalize_visual_queue_route",
    "run_one_queued_job_route",
    "get_visual_provider_settings_route",
    "update_visual_provider_settings_route",
    "download_flux_klein_route",
    "download_flux_klein_status_route",
    "download_visual_provider_model_route",
    "load_visual_provider_route",
    "unload_visual_provider_route",
    "visual_provider_status_route",
    "preload_visual_provider_route",
    "switch_visual_provider_route",
    "cleanup_visual_assets_route",
    "visual_inspector",
    "memory_inspector",
    "gm_tooling",
    "reinforce_memory",
    "integrity_inspect",
]
