"""Background execution for shared image generation jobs."""
from __future__ import annotations

import os
import threading
from collections.abc import Callable
from typing import Any

from pydantic import ValidationError

from .image_contracts import ImageGenerateInput, image_title_from_prompt
from .models import CompleteJobRequest, FailJobRequest, JobRecord

IMAGE_JOB_TYPE = "image.generate"
IMAGE_EXECUTOR_ENV = "OMNIX_INLINE_IMAGE_JOB_EXECUTOR"


def install_image_job_execution(sqlite_job_store_cls: Any) -> None:
    """Patch job creation once so image jobs execute off the request thread."""

    if getattr(sqlite_job_store_cls, "_omnix_image_jobs_installed", False):
        return

    original_create_job = sqlite_job_store_cls.create_job

    def create_job_with_image_execution(self: Any, request: Any) -> JobRecord:
        job = original_create_job(self, request)
        if job.type == IMAGE_JOB_TYPE and _executor_enabled():
            _start_image_job(self, job)
        return job

    sqlite_job_store_cls.create_job = create_job_with_image_execution
    sqlite_job_store_cls._omnix_image_jobs_installed = True


def _executor_enabled() -> bool:
    return os.environ.get(IMAGE_EXECUTOR_ENV, "1").strip().lower() not in {"0", "false", "off", "disabled"}


def _start_image_job(job_store: Any, job: JobRecord) -> None:
    thread = threading.Thread(
        target=execute_image_job,
        args=(job_store, job),
        name=f"omnix-image-{job.id.removeprefix('job:')[:8]}",
        daemon=True,
    )
    thread.start()


def execute_image_job(
    job_store: Any,
    job: JobRecord,
    *,
    generate_fn: Callable[[dict[str, Any]], Any] | None = None,
) -> JobRecord:
    """Run one image job and persist its terminal shared-job state."""

    job_store.mark_running(job.id)
    try:
        request = ImageGenerateInput.model_validate(job.input_payload or {})
    except ValidationError as exc:
        return _fail(job_store, job, "image_invalid_request", str(exc), retryable=False)
    except ValueError as exc:
        return _fail(job_store, job, "image_provider_unavailable", str(exc), retryable=False)

    if generate_fn is None:
        from app.image.service import generate_image

        generate_fn = generate_image

    try:
        result = generate_fn(request.provider_payload())
    except Exception as exc:
        return _fail(job_store, job, "image_generation_failed", str(exc) or "Image generation failed", retryable=True)

    if not bool(getattr(result, "ok", False)):
        message = str(getattr(result, "error", "") or "Image generation failed")
        return _fail(
            job_store,
            job,
            "image_generation_failed",
            message,
            retryable=True,
            details={"provider": getattr(result, "provider", ""), "status": getattr(result, "status", "")},
        )

    local_path = str(getattr(result, "local_path", "") or "").strip()
    asset_url = str(getattr(result, "asset_url", "") or "").strip()
    if not local_path and not asset_url:
        return _fail(
            job_store,
            job,
            "image_output_missing",
            "Image provider completed without a file or asset URL",
            retryable=True,
        )

    output_ref = {
        "type": "image",
        "title": image_title_from_prompt(request.prompt),
        "provider_id": request.provider_id,
        "provider": str(getattr(result, "provider", "") or request.provider_key()),
        "mime_type": str(getattr(result, "mime_type", "") or "image/png"),
        "width": int(getattr(result, "width", 0) or request.width),
        "height": int(getattr(result, "height", 0) or request.height),
        "seed": getattr(result, "seed", request.seed),
        "storage_path": local_path,
        "asset_url": asset_url,
        "metadata": dict(getattr(result, "metadata", {}) or {}),
    }
    completed = job_store.complete_job(
        job.id,
        CompleteJobRequest(
            output_refs=[output_ref],
            logs=[{"level": "info", "message": "Image generated by configured provider"}],
        ),
    )
    return completed or job


def _fail(
    job_store: Any,
    job: JobRecord,
    code: str,
    message: str,
    *,
    retryable: bool,
    details: dict[str, Any] | None = None,
) -> JobRecord:
    failed = job_store.fail_job(
        job.id,
        FailJobRequest(
            code=code,
            message=message,
            retryable=retryable,
            details={"job_type": job.type, "module": job.module, **(details or {})},
        ),
    )
    return failed or job
