"""Inline local-first execution for feature jobs submitted directly by the web UI."""
from __future__ import annotations

from typing import Any, Callable

from .models import CompleteJobRequest, FailJobRequest, JobRecord

INLINE_FEATURE_JOB_TYPES = {"story.generate", "podcast.generate", "rpg.turn"}


def install_inline_feature_job_execution(sqlite_job_store_cls: Any) -> None:
    """Patch ``SQLiteJobStore.create_job`` once with local-first feature execution.

    The shared job queue remains worker-compatible. This wrapper only handles the
    feature jobs that the React UI creates directly and that otherwise have no
    local worker attached in the current gateway runtime.
    """

    if getattr(sqlite_job_store_cls, "_omnix_inline_feature_jobs_installed", False):
        return

    original_create_job: Callable[..., JobRecord] = sqlite_job_store_cls.create_job

    def create_job_with_inline_execution(self: Any, request: Any) -> JobRecord:
        job = original_create_job(self, request)
        if job.type not in INLINE_FEATURE_JOB_TYPES:
            return job
        return _execute_feature_job(self, job)

    sqlite_job_store_cls.create_job = create_job_with_inline_execution
    sqlite_job_store_cls._omnix_inline_feature_jobs_installed = True


def _execute_feature_job(job_store: Any, job: JobRecord) -> JobRecord:
    job_store.mark_running(job.id)
    try:
        result = _render_job(job)
    except Exception as exc:  # pragma: no cover - route-level tests cover this path
        failed = job_store.fail_job(
            job.id,
            FailJobRequest(
                code="inline_job_failed",
                message=str(exc) or "Inline feature job failed",
                retryable=True,
                details={"job_type": job.type, "module": job.module},
            ),
        )
        return failed or job

    completed = job_store.complete_job(
        job.id,
        CompleteJobRequest(
            output_refs=[
                {
                    "type": result["artifact_type"],
                    "module": job.module,
                    "title": result["title"],
                    "content": result["content"],
                    "provider_id": result.get("provider_id"),
                    "model_id": result.get("model_id"),
                    "resolved_model": result.get("resolved_model"),
                }
            ],
            logs=[
                {
                    "level": "info",
                    "message": result["log_message"],
                    "content": result["content"],
                }
            ],
        ),
    )
    return completed or job


def _render_job(job: JobRecord) -> dict[str, Any]:
    payload = job.input_payload or {}
    provider_id = _text(payload.get("provider_id"))
    model_id = _text(payload.get("model_id"))

    if job.type == "story.generate":
        requested_title = _text(payload.get("title"))
        generate_title = _bool(payload.get("generate_title")) or requested_title is None
        premise = _require_text(payload.get("premise"), "Story premise is required")
        action = _text(payload.get("action")) or "draft"
        interaction_mode = _text(payload.get("interaction_mode")) or "writing"
        source_text = _text(payload.get("source_text"))
        user_response = _text(payload.get("user_response"))
        prompt_lines = [
            "Write a polished long-form story draft.",
            (
                "Generate an evocative, concise title for this story. Start the response with a "
                "level-1 Markdown heading containing only the generated title."
            )
            if generate_title
            else f"Title: {requested_title}",
            f"Premise: {premise}",
            f"Action: {action}",
            f"Interaction mode: {interaction_mode}",
        ]
        if source_text:
            prompt_lines.extend(["Story context:", source_text])
        if user_response and user_response not in (source_text or ""):
            prompt_lines.extend(["Player response:", user_response])
        prompt_lines.append(
            "Return Markdown with the generated title as the first line, then the story text."
            if generate_title
            else "Return the story text only."
        )
        prompt = "\n".join(prompt_lines)
        content, resolved_model = _call_chat_provider(prompt, provider_id=provider_id, model_id=model_id)
        title = requested_title or _extract_markdown_title(content) or "Untitled story"
        return {
            "artifact_type": "story",
            "title": title,
            "content": content,
            "log_message": "Story generated by local provider",
            "provider_id": provider_id,
            "model_id": model_id,
            "resolved_model": resolved_model,
        }

    if job.type == "podcast.generate":
        title = _text(payload.get("title")) or "Untitled episode"
        brief = _require_text(payload.get("brief"), "Podcast brief is required")
        speakers = payload.get("speakers") or ["Host", "Guest"]
        if not isinstance(speakers, list):
            speakers = ["Host", "Guest"]
        speaker_line = ", ".join(str(speaker) for speaker in speakers if str(speaker).strip()) or "Host, Guest"
        prompt = (
            "Write a podcast episode script.\n"
            f"Title: {title}\n"
            f"Speakers: {speaker_line}\n"
            f"Brief: {brief}\n"
            "Return a production-ready script with speaker labels."
        )
        content, resolved_model = _call_chat_provider(prompt, provider_id=provider_id, model_id=model_id)
        return {
            "artifact_type": "podcast_script",
            "title": title,
            "content": content,
            "log_message": "Podcast script generated by local provider",
            "provider_id": provider_id,
            "model_id": model_id,
            "resolved_model": resolved_model,
        }

    if job.type == "rpg.turn":
        command = _require_text(payload.get("command"), "RPG command is required")
        session_id = None
        if isinstance(job.input_ref, dict):
            session_id = _text(job.input_ref.get("session_id"))
        prompt = (
            "Resolve this RPG player command as a concise game-master response.\n"
            f"Session: {session_id or 'new/current'}\n"
            f"Command: {command}\n"
            "Return the visible RPG response only."
        )
        content, resolved_model = _call_chat_provider(prompt, provider_id=provider_id, model_id=model_id)
        return {
            "artifact_type": "rpg_turn_response",
            "title": command[:80] or "RPG turn",
            "content": content,
            "log_message": "RPG turn response generated by local provider",
            "provider_id": provider_id,
            "model_id": model_id,
            "resolved_model": resolved_model,
        }

    raise RuntimeError(f"Unsupported inline job type: {job.type}")


def _call_chat_provider(prompt: str, *, provider_id: str | None, model_id: str | None) -> tuple[str, str | None]:
    from app import shared  # type: ignore[import-not-found]
    from app.providers import ChatMessage as ProviderMessage  # type: ignore[import-not-found]

    provider_name = _provider_key(provider_id)
    provider = shared.get_provider(provider_name)
    if provider is None:
        raise RuntimeError("LLM provider is not available")

    messages = [
        ProviderMessage(role="system", content=shared.get_global_system_prompt()),
        ProviderMessage(role="user", content=prompt),
    ]
    model_name = _model_key(model_id)
    response = provider.chat_completion(messages=messages, model=model_name, stream=False)
    content = (getattr(response, "content", "") or "").strip()
    if not content:
        raise RuntimeError("LLM response was empty")
    resolved_model = getattr(response, "model", None) or model_name
    return content, resolved_model


def _provider_key(value: str | None) -> str | None:
    text = _text(value)
    if not text:
        return None
    return text.split(":", 1)[1] if text.startswith("llm:") else text


def _model_key(value: str | None) -> str | None:
    text = _text(value)
    if not text:
        return None
    parts = text.split(":", 2)
    if len(parts) == 3 and parts[0] == "llm":
        return parts[2] or None
    return text


def _text(value: object) -> str | None:
    if value is None:
        return None
    text = str(value).strip()
    return text or None


def _bool(value: object) -> bool:
    if isinstance(value, bool):
        return value
    if value is None:
        return False
    return str(value).strip().lower() in {"1", "true", "yes", "on"}


def _extract_markdown_title(content: str) -> str | None:
    for line in content.splitlines():
        text = line.strip()
        if text.startswith("# "):
            title = text.removeprefix("# ").strip()
            return title or None
    return None


def _require_text(value: object, message: str) -> str:
    text = _text(value)
    if not text:
        raise ValueError(message)
    return text
