import { TradingChartPanelProps } from './tradingChartPanelModel';
import { useChartPanelState } from './useTradingChartPanelState';
import { useChartIndicatorScheduling, useChartPanelData } from './useTradingChartPanelData';
import { useChartLifecycle } from './useTradingChartPanelLifecycle';
import { useChartSync } from './useTradingChartPanelSync';
import { useChartView } from './useTradingChartPanelView';
import { useChartIndicatorActions, useChartRangeActions } from './useTradingChartPanelActions';
import { useChartReplayActions } from './useTradingChartPanelReplay';
import { useChartWorkflow } from './useTradingChartPanelWorkflow';

/** One chart panel's state, data, effects and actions, composed from its hooks (WP-9.5). */
export function useTradingChartPanel(props: TradingChartPanelProps) {
  const { sessionId, chartId, chartNumber, instrumentId, bindingId, interval, chartType, indicators, comparisons, active, chartFocusMode, onActivate, onChartFocusChange, onOpenSymbolSearch, onChangeInterval, onChangeChartType, onToggleIndicator, onClearIndicators, onToggleIndicatorVisibility, onUpdateIndicator, onMoveIndicator, onUpdateComparisons, onOpenPineScript, onOpenMarketDataSettings, synchronization, paperAccountId } = props;
  const state = useChartPanelState({ sessionId, chartId, chartNumber, instrumentId, bindingId, interval, chartType, indicators, comparisons, active, chartFocusMode, onActivate, onChartFocusChange, onOpenSymbolSearch, onChangeInterval, onChangeChartType, onToggleIndicator, onClearIndicators, onToggleIndicatorVisibility, onUpdateIndicator, onMoveIndicator, onUpdateComparisons, onOpenPineScript, onOpenMarketDataSettings, synchronization, paperAccountId });
  const scheduling = useChartIndicatorScheduling({ sessionId, chartId, chartNumber, instrumentId, bindingId, interval, chartType, indicators, comparisons, active, chartFocusMode, onActivate, onChartFocusChange, onOpenSymbolSearch, onChangeInterval, onChangeChartType, onToggleIndicator, onClearIndicators, onToggleIndicatorVisibility, onUpdateIndicator, onMoveIndicator, onUpdateComparisons, onOpenPineScript, onOpenMarketDataSettings, synchronization, paperAccountId, ...state });
  const data = useChartPanelData({ sessionId, chartId, chartNumber, instrumentId, bindingId, interval, chartType, indicators, comparisons, active, chartFocusMode, onActivate, onChartFocusChange, onOpenSymbolSearch, onChangeInterval, onChangeChartType, onToggleIndicator, onClearIndicators, onToggleIndicatorVisibility, onUpdateIndicator, onMoveIndicator, onUpdateComparisons, onOpenPineScript, onOpenMarketDataSettings, synchronization, paperAccountId, ...state, ...scheduling });
  const lifecycle = useChartLifecycle({ sessionId, chartId, chartNumber, instrumentId, bindingId, interval, chartType, indicators, comparisons, active, chartFocusMode, onActivate, onChartFocusChange, onOpenSymbolSearch, onChangeInterval, onChangeChartType, onToggleIndicator, onClearIndicators, onToggleIndicatorVisibility, onUpdateIndicator, onMoveIndicator, onUpdateComparisons, onOpenPineScript, onOpenMarketDataSettings, synchronization, paperAccountId, ...state, ...scheduling, ...data });
  const sync = useChartSync({ sessionId, chartId, chartNumber, instrumentId, bindingId, interval, chartType, indicators, comparisons, active, chartFocusMode, onActivate, onChartFocusChange, onOpenSymbolSearch, onChangeInterval, onChangeChartType, onToggleIndicator, onClearIndicators, onToggleIndicatorVisibility, onUpdateIndicator, onMoveIndicator, onUpdateComparisons, onOpenPineScript, onOpenMarketDataSettings, synchronization, paperAccountId, ...state, ...scheduling, ...data, ...lifecycle });
  const view = useChartView({ sessionId, chartId, chartNumber, instrumentId, bindingId, interval, chartType, indicators, comparisons, active, chartFocusMode, onActivate, onChartFocusChange, onOpenSymbolSearch, onChangeInterval, onChangeChartType, onToggleIndicator, onClearIndicators, onToggleIndicatorVisibility, onUpdateIndicator, onMoveIndicator, onUpdateComparisons, onOpenPineScript, onOpenMarketDataSettings, synchronization, paperAccountId, ...state, ...scheduling, ...data, ...lifecycle, ...sync });
  const indicatorActions = useChartIndicatorActions({ sessionId, chartId, chartNumber, instrumentId, bindingId, interval, chartType, indicators, comparisons, active, chartFocusMode, onActivate, onChartFocusChange, onOpenSymbolSearch, onChangeInterval, onChangeChartType, onToggleIndicator, onClearIndicators, onToggleIndicatorVisibility, onUpdateIndicator, onMoveIndicator, onUpdateComparisons, onOpenPineScript, onOpenMarketDataSettings, synchronization, paperAccountId, ...state, ...scheduling, ...data, ...lifecycle, ...sync, ...view });
  const rangeActions = useChartRangeActions({ sessionId, chartId, chartNumber, instrumentId, bindingId, interval, chartType, indicators, comparisons, active, chartFocusMode, onActivate, onChartFocusChange, onOpenSymbolSearch, onChangeInterval, onChangeChartType, onToggleIndicator, onClearIndicators, onToggleIndicatorVisibility, onUpdateIndicator, onMoveIndicator, onUpdateComparisons, onOpenPineScript, onOpenMarketDataSettings, synchronization, paperAccountId, ...state, ...scheduling, ...data, ...lifecycle, ...sync, ...view, ...indicatorActions });
  const replayActions = useChartReplayActions({ sessionId, chartId, chartNumber, instrumentId, bindingId, interval, chartType, indicators, comparisons, active, chartFocusMode, onActivate, onChartFocusChange, onOpenSymbolSearch, onChangeInterval, onChangeChartType, onToggleIndicator, onClearIndicators, onToggleIndicatorVisibility, onUpdateIndicator, onMoveIndicator, onUpdateComparisons, onOpenPineScript, onOpenMarketDataSettings, synchronization, paperAccountId, ...state, ...scheduling, ...data, ...lifecycle, ...sync, ...view, ...indicatorActions, ...rangeActions });
  const workflow = useChartWorkflow({ sessionId, chartId, chartNumber, instrumentId, bindingId, interval, chartType, indicators, comparisons, active, chartFocusMode, onActivate, onChartFocusChange, onOpenSymbolSearch, onChangeInterval, onChangeChartType, onToggleIndicator, onClearIndicators, onToggleIndicatorVisibility, onUpdateIndicator, onMoveIndicator, onUpdateComparisons, onOpenPineScript, onOpenMarketDataSettings, synchronization, paperAccountId, ...state, ...scheduling, ...data, ...lifecycle, ...sync, ...view, ...indicatorActions, ...rangeActions, ...replayActions });
  return { sessionId, chartId, chartNumber, instrumentId, bindingId, interval, chartType, indicators, comparisons, active, chartFocusMode, onActivate, onChartFocusChange, onOpenSymbolSearch, onChangeInterval, onChangeChartType, onToggleIndicator, onClearIndicators, onToggleIndicatorVisibility, onUpdateIndicator, onMoveIndicator, onUpdateComparisons, onOpenPineScript, onOpenMarketDataSettings, synchronization, paperAccountId, ...state, ...scheduling, ...data, ...lifecycle, ...sync, ...view, ...indicatorActions, ...rangeActions, ...replayActions, ...workflow };
}

export type TradingChartPanelModel = ReturnType<typeof useTradingChartPanel>;
