from __future__ import annotations

OBJECTIVE_QUEST_IDS: dict[str, str] = {
    "objective:warn_garran": "quest:warn_wagon",
    "objective:travel_to_wagon_yard": "quest:warn_wagon",
    "objective:choose_safe_route": "quest:warn_wagon",
    "objective:leave_by_quarry_road": "quest:quarry_road_ambush",
    "objective:scout_quarry_road": "quest:quarry_road_ambush",
    "objective:spot_bridge_watchers": "quest:quarry_road_ambush",
    "objective:choose_ambush_response": "quest:quarry_road_ambush",
    "objective:protect_wagon": "quest:quarry_road_ambush",
    "objective:find_witness": "quest:witness_search",
    "objective:ask_mira": "quest:witness_search",
    "objective:inspect_side_door": "quest:witness_search",
    "objective:identify_bandit_employer": "quest:mill_ruins_lead",
    "objective:find_mill_proof": "quest:mill_ruins_lead",
    "objective:inspect_mill_cellar": "quest:mill_ruins_lead",
    "objective:reach_north_road_shrine": "quest:north_road_shrine_contact",
    "objective:inspect_shrine_tracks": "quest:north_road_shrine_contact",
    "objective:watch_for_contact_signal": "quest:north_road_shrine_contact",
    "objective:eavesdrop_tollhouse_meeting": "quest:north_road_shrine_contact",
    "objective:plan_against_voss": "quest:captain_voss_consequence",
    "objective:identify_voss_allies": "quest:captain_voss_consequence",
    "objective:seek_magistrate_hearing": "quest:captain_voss_consequence",
    "objective:present_manifest": "quest:captain_voss_consequence",
    "objective:secure_public_witnesses": "quest:captain_voss_consequence",
    "objective:counter_voss_intimidation": "quest:captain_voss_consequence",
    "objective:attend_public_hearing": "quest:captain_voss_consequence",
    "objective:choose_voss_outcome": "quest:captain_voss_consequence",
    "objective:review_voss_backer_leads": "quest:voss_backers_investigation",
    "objective:trace_voss_payment_marks": "quest:voss_backers_investigation",
    "objective:identify_silver_crow": "quest:voss_backers_investigation",
    "objective:reach_abandoned_cooperage": "quest:voss_backers_investigation",
    "objective:inspect_cooperage_cellar": "quest:voss_backers_investigation",
    "objective:plan_against_sable_chain": "quest:sable_chain_countermove",
    "objective:secure_sable_chain_evidence": "quest:sable_chain_countermove",
    "objective:detect_safehouse_watchers": "quest:sable_chain_countermove",
    "objective:reach_river_gate_warehouses": "quest:sable_chain_countermove",
    "objective:inspect_warehouse_marks": "quest:sable_chain_countermove",
    "objective:prepare_safehouse_defense": "quest:sable_chain_countermove",
    "objective:review_handler_orders": "quest:sable_chain_handler_route_pressure",
    "objective:decode_handler_route_cipher": "quest:sable_chain_handler_route_pressure",
    "objective:warn_east_road_teamsters": "quest:sable_chain_handler_route_pressure",
    "objective:scout_east_road_pressure_points": "quest:sable_chain_handler_route_pressure",
    "objective:disable_false_toll_markers": "quest:sable_chain_handler_route_pressure",
    "objective:reach_black_ford": "quest:sable_chain_handler_route_pressure",
    "objective:secure_black_ford_crossing": "quest:sable_chain_handler_route_pressure",
    "objective:plan_pursuit_of_veska": "quest:handler_veska_leadership_pursuit",
    "objective:trace_veska_courier_route": "quest:handler_veska_leadership_pursuit",
    "objective:reach_old_north_watchpost": "quest:handler_veska_leadership_pursuit",
    "objective:inspect_watchpost_courier_signs": "quest:handler_veska_leadership_pursuit",
    "objective:decode_veska_message": "quest:handler_veska_leadership_pursuit",
    "objective:reach_ridge_hideout": "quest:handler_veska_leadership_pursuit",
    "objective:scout_ridge_hideout": "quest:handler_veska_leadership_pursuit",
    "objective:review_veska_ledgers": "quest:sable_chain_endgame_opener",
    "objective:identify_hidden_paymaster": "quest:sable_chain_endgame_opener",
    "objective:trace_red_lantern_payments": "quest:sable_chain_endgame_opener",
    "objective:reach_old_counting_house": "quest:sable_chain_endgame_opener",
    "objective:inspect_counting_house_records": "quest:sable_chain_endgame_opener",
}


def infer_objective_quest_id(objective_id: str) -> str:
    return OBJECTIVE_QUEST_IDS.get(str(objective_id or ""), "")
