"""Story and podcast durable job contracts and execution."""
from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict, Field

from app.jobs.models import CompleteJobRequest, FailJobRequest, JobRecord


class StoryGenerateInput(BaseModel):
    model_config = ConfigDict(extra="allow")
    premise: str
    title: str | None = None
    generate_title: bool = False
    provider_id: str | None = None
    model_id: str | None = None
    source_text: str | None = None
    user_response: str | None = None
    action: str = "draft"
    interaction_mode: str = "writing"


class PodcastGenerateInput(BaseModel):
    model_config = ConfigDict(extra="allow")
    brief: str
    title: str | None = None
    speakers: list[str] = Field(default_factory=lambda: ["Host", "Guest"])
    provider_id: str | None = None
    model_id: str | None = None


def execute_story_job(job_store: Any, job: JobRecord) -> JobRecord:
    job_store.mark_running(job.id)
    try:
        result = _render_job(job)
    except Exception as exc:
        failed = job_store.fail_job(
            job.id,
            FailJobRequest(
                code="story_job_failed",
                message=str(exc) or "Story job failed",
                retryable=True,
                details={"job_type": job.type, "module": job.module},
            ),
        )
        return failed or job

    completed = job_store.complete_job(
        job.id,
        CompleteJobRequest(
            output_refs=[{
                "type": result["artifact_type"],
                "module": job.module,
                "title": result["title"],
                "content": result["content"],
                "provider_id": result.get("provider_id"),
                "model_id": result.get("model_id"),
                "resolved_model": result.get("resolved_model"),
            }],
            logs=[{
                "level": "info",
                "message": result["log_message"],
                "content": result["content"],
            }],
        ),
    )
    return completed or job


def _render_job(job: JobRecord) -> dict[str, Any]:
    payload = job.input_payload or {}
    provider_id = _text(payload.get("provider_id"))
    model_id = _text(payload.get("model_id"))

    if job.type == "story.generate":
        requested_title = _text(payload.get("title"))
        generate_title = bool(payload.get("generate_title")) or requested_title is None
        premise = _require_text(payload.get("premise"), "Story premise is required")
        action = _text(payload.get("action")) or "draft"
        interaction_mode = _text(payload.get("interaction_mode")) or "writing"
        source_text = _text(payload.get("source_text"))
        user_response = _text(payload.get("user_response"))
        prompt_lines = [
            "Write a polished long-form story draft.",
            (
                "Generate an evocative, concise title for this story. Start the response with "
                "a level-1 Markdown heading containing only the generated title."
            )
            if generate_title
            else f"Title: {requested_title}",
            f"Premise: {premise}",
            f"Action: {action}",
            f"Interaction mode: {interaction_mode}",
        ]
        if source_text:
            prompt_lines.extend(["Story context:", source_text])
        if user_response and user_response not in (source_text or ""):
            prompt_lines.extend(["Player response:", user_response])
        prompt_lines.append(
            "Return Markdown with the generated title as the first line, then the story text."
            if generate_title
            else "Return the story text only."
        )
        content, resolved_model = _call_chat_provider(
            "\n".join(prompt_lines),
            provider_id=provider_id,
            model_id=model_id,
        )
        title = requested_title or _extract_markdown_title(content) or "Untitled story"
        return {
            "artifact_type": "story",
            "title": title,
            "content": content,
            "log_message": "Story generated by local provider",
            "provider_id": provider_id,
            "model_id": model_id,
            "resolved_model": resolved_model,
        }

    if job.type == "podcast.generate":
        title = _text(payload.get("title")) or "Untitled episode"
        brief = _require_text(payload.get("brief"), "Podcast brief is required")
        speakers = payload.get("speakers") or ["Host", "Guest"]
        if not isinstance(speakers, list):
            speakers = ["Host", "Guest"]
        speaker_line = ", ".join(str(speaker) for speaker in speakers if str(speaker).strip()) or "Host, Guest"
        prompt = (
            "Write a podcast episode script.\n"
            f"Title: {title}\n"
            f"Speakers: {speaker_line}\n"
            f"Brief: {brief}\n"
            "Return a production-ready script with speaker labels."
        )
        content, resolved_model = _call_chat_provider(
            prompt,
            provider_id=provider_id,
            model_id=model_id,
        )
        return {
            "artifact_type": "podcast_script",
            "title": title,
            "content": content,
            "log_message": "Podcast script generated by local provider",
            "provider_id": provider_id,
            "model_id": model_id,
            "resolved_model": resolved_model,
        }

    raise RuntimeError(f"Unsupported story job type: {job.type}")


def _call_chat_provider(
    prompt: str,
    *,
    provider_id: str | None,
    model_id: str | None,
) -> tuple[str, str | None]:
    from app.providers import ChatMessage
    from app.providers.service import chat_completion

    provider_name = _provider_key(provider_id)
    response = chat_completion(
        messages=[
            ChatMessage(role="system", content="You are a helpful AI assistant."),
            ChatMessage(role="user", content=prompt),
        ],
        provider_name=provider_name,
        model=_model_key(model_id),
        stream=False,
    )
    content = (getattr(response, "content", "") or "").strip()
    if not content:
        raise RuntimeError("LLM response was empty")
    return content, getattr(response, "model", None) or _model_key(model_id)


def _provider_key(value: str | None) -> str | None:
    text = _text(value)
    return text.split(":", 1)[1] if text and text.startswith("llm:") else text


def _model_key(value: str | None) -> str | None:
    text = _text(value)
    if not text:
        return None
    parts = text.split(":", 2)
    if len(parts) == 3 and parts[0] == "llm":
        return parts[2] or None
    return text


def _extract_markdown_title(content: str) -> str | None:
    for line in content.splitlines():
        text = line.strip()
        if text.startswith("# "):
            return text.removeprefix("# ").strip() or None
    return None


def _require_text(value: object, message: str) -> str:
    text = _text(value)
    if not text:
        raise ValueError(message)
    return text


def _text(value: object) -> str | None:
    if value is None:
        return None
    text = str(value).strip()
    return text or None
