"""Small platform summary services for gateway contracts."""
from .diagnostics import DiagnosticsPayload, get_diagnostics_payload
from .legacy_sessions import (
    LegacyGenerateTitleRequest,
    LegacyGenerateTitleResponse,
    LegacySessionCreateResponse,
    LegacySessionListResponse,
    LegacySessionResponse,
    LegacySessionUpdateRequest,
    LegacySuccessResponse,
    create_legacy_session,
    delete_legacy_session,
    generate_legacy_session_title,
    get_legacy_session,
    list_legacy_sessions,
    update_legacy_session,
)
from .reports import ReportListResponse, list_report_artifacts
from .rpg_adventure_compat import (
    adventure_simulation_state_payload,
    compare_adventure_entity_payload,
    compare_adventure_world_payload,
    inspect_adventure_world_payload,
    inspect_adventure_world_snapshot_payload,
    list_adventure_templates_payload,
    preview_adventure_payload,
    simulate_adventure_step_payload,
    validate_adventure_payload,
)
from .rpg_inspection_compat import (
    inspect_npc_reasoning_payload,
    inspect_tick_diff_payload,
    inspect_timeline_payload,
    inspect_timeline_tick_payload,
    inspect_world_events_payload,
)
from .rpg_player_compat import (
    player_codex_payload,
    player_encounter_payload,
    player_journal_payload,
    player_objectives_payload,
    player_state_payload,
)
from .rpg_session_compat import get_rpg_session_payload, list_rpg_sessions_payload
from .settings import SettingsPayload, SettingsSaveResponse, get_settings_payload, save_settings_payload

__all__ = [
    "DiagnosticsPayload",
    "LegacyGenerateTitleRequest",
    "LegacyGenerateTitleResponse",
    "LegacySessionCreateResponse",
    "LegacySessionListResponse",
    "LegacySessionResponse",
    "LegacySessionUpdateRequest",
    "LegacySuccessResponse",
    "ReportListResponse",
    "SettingsPayload",
    "SettingsSaveResponse",
    "adventure_simulation_state_payload",
    "compare_adventure_entity_payload",
    "compare_adventure_world_payload",
    "create_legacy_session",
    "delete_legacy_session",
    "generate_legacy_session_title",
    "get_diagnostics_payload",
    "get_legacy_session",
    "get_rpg_session_payload",
    "get_settings_payload",
    "inspect_npc_reasoning_payload",
    "inspect_tick_diff_payload",
    "inspect_timeline_payload",
    "inspect_timeline_tick_payload",
    "inspect_adventure_world_payload",
    "inspect_adventure_world_snapshot_payload",
    "inspect_world_events_payload",
    "list_adventure_templates_payload",
    "list_legacy_sessions",
    "list_report_artifacts",
    "list_rpg_sessions_payload",
    "player_codex_payload",
    "player_encounter_payload",
    "player_journal_payload",
    "player_objectives_payload",
    "player_state_payload",
    "preview_adventure_payload",
    "save_settings_payload",
    "simulate_adventure_step_payload",
    "update_legacy_session",
    "validate_adventure_payload",
]
