"""Render docs/security/PERMISSIONS.md from app.security.permissions (WP-4.3)."""
from __future__ import annotations

import argparse
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
TARGET = ROOT / "docs/security/PERMISSIONS.md"


def render() -> str:
    from app.security.permissions import (
        CATALOG,
        DEFAULT_ROLE_PERMISSIONS,
        FEATURE_DEFAULTS,
        KERNEL_DEFAULTS,
        ROUTE_PERMISSIONS,
        WEBSOCKET_PERMISSIONS,
    )

    roles = ["owner", *sorted(DEFAULT_ROLE_PERMISSIONS)]
    lines = [
        "# Permissions",
        "",
        "Generated by `scripts/generate_permissions_doc.py` from",
        "`src/app/security/permissions.py`. Do not edit by hand.",
        "",
        "Every gateway route is authorized against the request's roles:",
        "",
        "1. A route's own permission (`openapi_extra=requires(...)` or the",
        "   per-route table below).",
        "2. Otherwise its feature's default: read permission for GET/HEAD, write",
        "   permission for other methods and WebSockets.",
        "",
        "`owner` holds every permission. With sign-in off, the local user is",
        "`owner`. Override role mappings with `OMNIX_ROLE_PERMISSIONS` (JSON:",
        "role to permission list; `owner` cannot be changed).",
        "",
        "## Catalog",
        "",
        "| Permission | Meaning | " + " | ".join(roles) + " |",
        "|---|---|" + "---|" * len(roles),
    ]
    for name, meaning in sorted(CATALOG.items()):
        cells = ["yes" if role == "owner" or name in DEFAULT_ROLE_PERMISSIONS.get(role, ()) else "" for role in roles]
        lines.append(f"| `{name}` | {meaning} | " + " | ".join(cells) + " |")
    lines += ["", "## Feature defaults", "", "| Feature | Read | Write |", "|---|---|---|"]
    for feature, (read, write) in sorted(FEATURE_DEFAULTS.items()):
        lines.append(f"| {feature} | `{read}` | `{write}` |")
    lines += ["", "## Kernel routes", "", "| Path prefix | Read | Write |", "|---|---|---|"]
    for prefix, pair in KERNEL_DEFAULTS:
        read, write = pair if pair else ("public", "public")
        lines.append(f"| `{prefix}` | {read if read == 'public' else f'`{read}`'} | {write if write == 'public' else f'`{write}`'} |")
    lines += ["", "## Per-route permissions", "", "| Method | Route | Permission |", "|---|---|---|"]
    for (method, path), permission in sorted(ROUTE_PERMISSIONS.items(), key=lambda item: (item[0][1], item[0][0])):
        lines.append(f"| {method} | `{path}` | `{permission}` |")
    lines += ["", "## WebSockets with read-only permissions", "", "| Route | Permission |", "|---|---|"]
    for path, permission in sorted(WEBSOCKET_PERMISSIONS.items()):
        lines.append(f"| `{path}` | `{permission}` |")
    lines += [
        "",
        "Agent and task-graph `approve`/`reject` commands also require",
        "`agent:approve`, and `steer` requires `agent:steer` (checked from the",
        "command payload).",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != expected:
            parser.error("docs/security/PERMISSIONS.md is stale; run scripts/generate_permissions_doc.py")
        return 0
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
