"""Render the supported Nginx example from the shared gateway routing policy."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]


def render(policy: dict) -> str:
    chat = policy['chat_pattern']
    reads = policy['read_pattern'][1:]
    speech = '|'.join(re.escape(path) for path in policy['speech_paths'])
    methods = '|'.join(policy['read_methods'])
    return f'''# Generated by scripts/render_gateway_ingress.py; install inside Nginx http {{}}.
# Replace addresses and the static web root for your deployment.
upstream omnix_worker {{ server 127.0.0.1:8000; keepalive 32; }}
upstream omnix_api {{
    least_conn;
    server 127.0.0.1:8001;
    server 127.0.0.1:8002;
    keepalive 64;
}}
map $http_upgrade $omnix_connection {{ default upgrade; '' ''; }}
# Change to 1 only when EVERY API process uses the shared remote TTS service.
map $host $omnix_speech_on_api {{ default 0; }}
map $uri $omnix_chat_target {{
    default omnix_worker;
    ~{chat} omnix_api;
}}
map "$request_method:$uri" $omnix_read_target {{
    default $omnix_chat_target;
    ~^(?:{methods}):{reads} omnix_api;
}}
map "$omnix_speech_on_api:$uri" $omnix_speech_target {{
    default $omnix_read_target;
    ~^1:(?:{speech})$ omnix_api;
}}
map $http_x_omnix_gateway_affinity $omnix_target {{
    default $omnix_speech_target;
    worker omnix_worker;
}}
server {{
    listen 8080;
    root /srv/omnix/web;
    location ~ ^/(?:api(?:/|$)|events$|health$|ready$) {{
        proxy_pass http://$omnix_target;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $omnix_connection;
        # Preserve one upstream for the whole stream and never replay a write.
        proxy_next_upstream off;
        proxy_buffering off;
        proxy_request_buffering off;
        proxy_read_timeout 3600s;
        add_header X-Omnix-Gateway-Route $omnix_target always;
    }}
    location / {{ try_files $uri $uri/ /index.html; }}
}}
'''


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    expected = render(json.loads((ROOT / 'deploy/gateway-route-policy.json').read_text(encoding='utf-8')))
    target = ROOT / 'deploy/nginx/omnix.conf'
    if args.check:
        if not target.exists() or target.read_text(encoding='utf-8') != expected:
            parser.error('Ingress differs from routing policy; run scripts/render_gateway_ingress.py')
    else:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(expected, encoding='utf-8')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
