import { useQueryClient } from '@tanstack/react-query';
import { audiobookApi } from './audiobookApi';
import { WorkspaceAsset, base, formatAssetCreationDate, formatAssetSize, formatDuration, reclassifyAudiobook, sourceAccept } from './audiobookWorkspaceModel';
import type { AudiobookWorkspaceModel } from './useAudiobookWorkspace';

/** Review sections: books, chapters, assets, documents, characters, voices and pronunciations. */
export function AudiobookReviewPanels({ ws }: { ws: AudiobookWorkspaceModel }) {
  const queryClient = useQueryClient();
  const {
    action, aliasNames, assetFilter, assetSearch, assetSort, assignedVoiceCount, bookSearch, busy, castLabel,
    castableSpeakers, chapterStatus, chapterStatusFilter, chapterView, classificationBlockedReason,
    classificationRules, confirmProposedSpeaker, documentSearch, documentTypeFilter, documentView, extractionRunning,
    findSpeakerSpan, getInstalledModelRevision, importProjectFile, librarySection, navigateLibrary,
    openDocument, openSourceUpload, project, pronunciationSearch, proposedSpeakers, queueChapterPreview,
    reclassificationRunning, rejectProposedSpeaker, rulesNeedExtraction, selectedAssetId, selectedChapter,
    selectedDocumentId, selectedVoiceId, setAliasNames, setAssetFilter, setAssetSearch, setAssetSort, setBookSearch,
    setChapterId, setChapterStatusFilter, setChapterView, setDocumentDetailTab, setDocumentSearch,
    setDocumentTypeFilter, setDocumentView, setPronunciationSearch, setSelectedAssetId, setSelectedDocumentId,
    setSelectedSpanId, setSelectedVoiceId, setSourceTerm, setSpeakerName, setSpokenTerm, setVoiceTargetSpeakerId,
    sourceTerm, speakerName, spokenTerm, startChapter, submitPronunciation, submitSpeaker, voiceTargetSpeakerId, voicesQuery, workspaceAssetList, workspaceDocumentList, workspaceMode,
  } = ws;
  if (!project) return null;
  return (
    <>
      {workspaceMode === 'review' && librarySection === 'books' && <section className="audiobook-card audiobook-books-panel">
        <div className="audiobook-section-title"><div><p className="eyebrow">Library</p><h2>Books &amp; chapters</h2><p className="audiobook-subtitle">Open a chapter to review its manuscript, cast, and audio.</p></div><label className="audiobook-search-field">Search books or chapters<input aria-label="Search books or chapters" value={bookSearch} onChange={(event) => setBookSearch(event.target.value)} placeholder="Search books or chapters…" /></label></div>
        <div className="audiobook-book-grid">
          {project.chapters.filter((chapter) => chapter.title.toLowerCase().includes(bookSearch.toLowerCase())).map((chapter) => {
            const render = project.render_jobs.find((job) => job.chapter_id === chapter.id);
            return <article className="audiobook-book-card" key={chapter.id}>
              {project.cover_asset_id ? <img src={`${base}/projects/${encodeURIComponent(project.id)}/cover`} alt="" /> : <div className="audiobook-chapter-placeholder">{chapter.ordinal + 1}</div>}
              <div className="audiobook-book-card-copy"><small>CHAPTER {chapter.ordinal + 1}</small><h3>{chapter.title}</h3><span>{chapter.character_count.toLocaleString()} characters · {render?.status ?? 'Draft'}</span>
                <div><button type="button" onClick={() => { setChapterId(chapter.id); navigateLibrary('projects'); }}>Continue</button><button type="button" disabled={busy} onClick={() => void action(async () => { const modelRevision = await getInstalledModelRevision(); const detail = chapter.id === selectedChapter?.id ? selectedChapter : await queryClient.fetchQuery({ queryKey: ['audiobook', 'chapter', project.id, chapter.id], queryFn: () => audiobookApi.chapter(project.id, chapter.id) }); const span = detail.spans[0]; if (!span) throw new Error('This chapter has no speech spans yet.'); await audiobookApi.preview(project.id, { chapter_id: chapter.id, span_id: span.id, model_revision: modelRevision.trim() }); setChapterId(chapter.id); setSelectedSpanId(span.id); navigateLibrary('projects'); }, 'Chapter preview queued.')}>Play</button></div>
              </div>
            </article>;
          })}
        </div>
        {project.chapters.length === 0 && <p>Upload a source book to extract chapters.</p>}
        {project.chapters.length > 0 && !project.chapters.some((chapter) => chapter.title.toLowerCase().includes(bookSearch.toLowerCase())) && <p>No chapters match “{bookSearch}”.</p>}
      </section>}
      {workspaceMode === 'review' && librarySection === 'chapters' && (() => {
        const chapters = project.chapters.filter((chapter) => {
          const matchesSearch = `${chapter.title} ${chapter.ordinal + 1}`.toLowerCase().includes(bookSearch.toLowerCase());
          return matchesSearch && (chapterStatusFilter === 'all' || chapterStatus(chapter) === chapterStatusFilter);
        });
        return <section className="audiobook-card audiobook-chapters-panel">
          <div className="audiobook-section-title"><div><p className="eyebrow">Audiobook project</p><h2>Chapters</h2><p className="audiobook-subtitle">Manage chapters, track production progress, and organize your audiobook.</p></div><button type="button" className="audiobook-primary-action" onClick={() => openSourceUpload(project.id)}>Replace source</button></div>
          <div className="audiobook-table-toolbar"><label className="audiobook-search-field">Search chapters by title, content, or tags<input aria-label="Search chapters" value={bookSearch} onChange={(event) => setBookSearch(event.target.value)} placeholder="Search chapters by title, content, or tags…" /></label><label>Status<select aria-label="Chapter status" value={chapterStatusFilter} onChange={(event) => setChapterStatusFilter(event.target.value)}><option value="all">All statuses</option><option value="Draft">Draft</option><option value="In Review">In Review</option><option value="In Progress">In Progress</option><option value="Queued">Queued</option><option value="Rendered">Rendered</option><option value="Needs attention">Needs attention</option></select></label><button type="button" className={chapterView === 'list' ? 'selected' : ''} aria-label="List view" onClick={() => setChapterView('list')}>☷</button><button type="button" className={chapterView === 'grid' ? 'selected' : ''} aria-label="Grid view" onClick={() => setChapterView('grid')}>▦</button></div>
          {chapterView === 'list' ? <div className="audiobook-chapter-table" role="table" aria-label="Audiobook chapters"><div className="audiobook-chapter-table-head" role="row"><span>#</span><span>Chapter title</span><span>Status</span><span>Spans</span><span>Words</span><span>Est. runtime</span><span>Cast / voices</span><span>Review</span><span>Actions</span></div>{chapters.map((chapter) => { const status = chapterStatus(chapter); const issues = project.review_issues.filter((issue) => issue.chapter_id === chapter.id); return <div className="audiobook-chapter-table-row" role="row" key={chapter.id}><span className="chapter-number">{chapter.ordinal + 1}</span><button type="button" className="chapter-title-button" onClick={() => startChapter(chapter)}><strong>{chapter.title}</strong><small>{chapter.character_count.toLocaleString()} characters</small></button><span className={`audiobook-status-pill status-${status.toLowerCase().replaceAll(' ', '-')}`}>{status}</span><span>{chapter.span_count ?? '—'}</span><span>{chapter.word_count?.toLocaleString() ?? '—'}</span><span>{formatDuration(chapter.estimated_runtime_seconds)}</span><span>{castLabel}<small>{assignedVoiceCount}/{project.speakers.length} voices assigned</small></span><span className={issues.length ? 'review-pending' : 'review-approved'}>{issues.length ? `${issues.length} open` : ['ready_to_render', 'rendering', 'mastering', 'ready_to_export', 'exported'].includes(project.state) ? 'Approved' : 'Pending'}</span><div className="audiobook-row-actions"><button type="button" aria-label={`Preview first span of ${chapter.title}`} disabled={busy} onClick={() => void action(() => queueChapterPreview(chapter), 'Chapter preview queued.')}>▶</button></div></div>; })}</div> : <div className="audiobook-chapter-grid">{chapters.map((chapter) => <article className="audiobook-chapter-grid-card" key={chapter.id}><div className="audiobook-chapter-grid-cover">{project.cover_asset_id && <img src={`${base}/projects/${encodeURIComponent(project.id)}/cover`} alt="" />}<b>{chapter.ordinal + 1}</b></div><div><span className="audiobook-status-pill">{chapterStatus(chapter)}</span><h3>{chapter.title}</h3><p>{chapter.character_count.toLocaleString()} characters · {`Est. ${formatDuration(chapter.estimated_runtime_seconds)}`}</p><button type="button" onClick={() => startChapter(chapter)}>Open in editor</button></div></article>)}</div>}
          {chapters.length === 0 && <p className="audiobook-empty-state">No chapters match the current filters.</p>}
        </section>;
      })()}
      {workspaceMode === 'review' && librarySection === 'assets' && (() => {
        const allAssets = workspaceAssetList();
        const assets = allAssets.map((asset, index) => ({ asset, index })).filter(({ asset }) => {
          const matchesSearch = `${asset.name} ${asset.type} ${asset.detail} ${asset.format ?? ''} ${asset.chapters ?? ''}`.toLowerCase().includes(assetSearch.toLowerCase());
          const matchesFilter = assetFilter === 'all' || (assetFilter === 'audio' && asset.type === 'Audio') || (assetFilter === 'images' && (asset.type === 'Cover Art' || asset.type === 'Chapter Thumbnail')) || (assetFilter === 'documents' && asset.type === 'Document') || (assetFilter === 'references' && asset.type === 'Reference');
          return matchesSearch && matchesFilter;
        }).sort((left, right) => {
          if (assetSort === 'name') return left.asset.name.localeCompare(right.asset.name, undefined, { sensitivity: 'base' });
          if (assetSort === 'type') return left.asset.type.localeCompare(right.asset.type) || left.asset.name.localeCompare(right.asset.name);
          const leftDate = left.asset.createdAt ? Date.parse(left.asset.createdAt) : Number.NaN;
          const rightDate = right.asset.createdAt ? Date.parse(right.asset.createdAt) : Number.NaN;
          const leftHasDate = Number.isFinite(leftDate);
          const rightHasDate = Number.isFinite(rightDate);
          if (leftHasDate && rightHasDate && leftDate !== rightDate) return rightDate - leftDate;
          if (leftHasDate !== rightHasDate) return leftHasDate ? -1 : 1;
          return left.index - right.index;
        }).map(({ asset }) => asset);
        const categories: [string, string, (asset: WorkspaceAsset) => boolean][] = [
          ['all', 'All Assets', () => true],
          ['audio', 'Audio', (asset) => asset.type === 'Audio'],
          ['images', 'Images', (asset) => asset.type === 'Cover Art' || asset.type === 'Chapter Thumbnail'],
          ['documents', 'Documents', (asset) => asset.type === 'Document'],
          ['references', 'References', (asset) => asset.type === 'Reference'],
        ];
        return <section className="audiobook-card audiobook-assets-panel">
          <div className="audiobook-section-title"><div><p className="eyebrow">Audiobook project</p><h2>Project Assets</h2><p className="audiobook-subtitle">View the stored source, cover, and finished exports. Uploading a new source replaces the current manuscript.</p></div><div className="audiobook-section-actions"><label className="audiobook-search-field">Search assets by name or type<input aria-label="Search assets" value={assetSearch} onChange={(event) => setAssetSearch(event.target.value)} placeholder="Search assets by name, tag, or type…" /></label><label className="audiobook-file-button">Upload source or cover<input id="audiobook-asset-import" type="file" accept={`${sourceAccept},image/jpeg,image/png`} onChange={(event) => { const file = event.currentTarget.files?.[0]; if (file) importProjectFile(file); event.currentTarget.value = ''; }} /></label></div></div>
          <div className="audiobook-assets-toolbar">
            <div className="audiobook-filter-row" role="group" aria-label="Filter project assets">{categories.map(([key, label, matches]) => <button type="button" key={key} className={assetFilter === key ? 'selected' : ''} aria-pressed={assetFilter === key} onClick={() => setAssetFilter(key)}><span className="asset-filter-icon" aria-hidden="true">{key === 'all' ? '▣' : key === 'audio' ? '◖' : key === 'images' ? '▧' : key === 'documents' ? '▤' : '↗'}</span>{label}<span className="asset-filter-count">{allAssets.filter(matches).length}</span></button>)}</div>
            <label className="audiobook-asset-sort">Sort by<select aria-label="Sort assets" value={assetSort} onChange={(event) => setAssetSort(event.target.value as typeof assetSort)}><option value="recent">Recently Added</option><option value="name">Name</option><option value="type">Type</option></select></label>
          </div>
          <p className="audiobook-asset-result-count">Showing {assets.length} of {allAssets.length} assets</p>
          <div className="audiobook-asset-grid">{assets.map((asset) => {
            const isSelected = selectedAssetId === asset.id || (!selectedAssetId && allAssets[0]?.id === asset.id);
            const typeIcon = asset.type === 'Audio' ? '◖' : asset.type === 'Document' ? '▤' : asset.type === 'Reference' ? '↗' : '▧';
            const assetSize = formatAssetSize(asset.sizeBytes);
            return <article className={`audiobook-asset-card${isSelected ? ' selected' : ''}`} key={asset.id}>
              <div className={`audiobook-asset-preview asset-${asset.type.toLowerCase().replaceAll(' ', '-')}`}>
                {asset.image && project.cover_asset_id ? <img src={`${base}/projects/${encodeURIComponent(project.id)}/cover`} alt="" /> : <span className="asset-preview-placeholder" aria-hidden="true">{typeIcon}</span>}
                <span role="img" className="asset-preview-type" title={asset.type} aria-label={asset.type}>{typeIcon}</span>
              </div>
              <button type="button" className="asset-name-button" aria-pressed={isSelected} onClick={() => setSelectedAssetId(asset.id)}><strong>{asset.name}</strong></button>
              <small className="asset-detail-line">{asset.detail}</small>
              <small className="asset-file-meta">{assetSize && <span>{assetSize}</span>}<time dateTime={asset.createdAt ?? undefined}>{formatAssetCreationDate(asset.createdAt)}</time></small>
              <div className="asset-usage-line"><em className={`asset-status asset-${asset.status.toLowerCase()}`}><span aria-hidden="true">●</span> {asset.status}</em><small>{asset.chapters ?? 'Not linked'}</small></div>
            </article>;
          })}</div>
          {assets.length === 0 && <p className="audiobook-empty-state">No assets match the current search and filters.</p>}
        </section>;
      })()}
      {workspaceMode === 'review' && librarySection === 'documents' && (() => {
        const documents = workspaceDocumentList();
        const filteredDocuments = documents.filter((document) => `${document.title} ${document.type} ${document.author}`.toLowerCase().includes(documentSearch.toLowerCase()) && (documentTypeFilter === 'all' || document.type === documentTypeFilter));
        const selectedDocument = documents.find((document) => document.id === selectedDocumentId) ?? documents[0];
        return <section className="audiobook-card audiobook-documents-panel">
          <div className="audiobook-section-title"><div><p className="eyebrow">Audiobook project</p><h2>Project Documents</h2><p className="audiobook-subtitle">Inspect the current manuscript and completed export reports. Uploading a source replaces the current manuscript.</p></div><div className="audiobook-section-actions"><label className="audiobook-file-button">Replace manuscript<input id="audiobook-document-import" type="file" accept={sourceAccept} onChange={(event) => { const file = event.currentTarget.files?.[0]; if (file) importProjectFile(file); event.currentTarget.value = ''; }} /></label></div></div>
          <div className="audiobook-document-categories">{([['all', 'All Documents'], ['Manuscript', 'Manuscript'], ['Export Notes', 'Export Reports']] as [string, string][]).map(([key, label]) => <button type="button" key={key} className={documentTypeFilter === key || (key === 'all' && documentTypeFilter === 'all') ? 'selected' : ''} onClick={() => setDocumentTypeFilter(key)}>{label}<span>{key === 'all' ? documents.length : documents.filter((document) => document.type === key).length}</span></button>)}</div>
          <div className="audiobook-document-toolbar"><label className="audiobook-search-field">Search documents<input aria-label="Search documents" value={documentSearch} onChange={(event) => setDocumentSearch(event.target.value)} placeholder="Search documents…" /></label><label>Type<select aria-label="Document type" value={documentTypeFilter} onChange={(event) => setDocumentTypeFilter(event.target.value)}><option value="all">All types</option>{Array.from(new Set(documents.map((document) => document.type))).map((type) => <option key={type} value={type}>{type}</option>)}</select></label><button type="button" className={documentView === 'list' ? 'selected' : ''} aria-label="Document list view" onClick={() => setDocumentView('list')}>☷</button><button type="button" className={documentView === 'grid' ? 'selected' : ''} aria-label="Document grid view" onClick={() => setDocumentView('grid')}>▦</button></div>
          <div className={`audiobook-document-layout ${documentView === 'grid' ? 'document-grid-view' : ''}`}><div className="audiobook-document-list" role="table" aria-label="Project documents"><div className="audiobook-document-list-head"><span>Title</span><span>Type</span><span>Last edited</span><span>Author / source</span><span>Linked</span><span>Status</span><span>Actions</span></div>{filteredDocuments.map((document) => <div className={`audiobook-document-row${selectedDocument?.id === document.id ? ' selected' : ''}`} key={document.id} onClick={() => setSelectedDocumentId(document.id)}><button type="button" onClick={() => setSelectedDocumentId(document.id)}><strong>{document.title}</strong><small>{document.type}</small></button><span>{document.type}</span><span>{document.lastEdited}</span><span>{document.author}</span><span>{document.linked}</span><span className={`audiobook-status-pill status-${document.status.toLowerCase().replaceAll(' ', '-')}`}>{document.status}</span><div className="audiobook-row-actions"><button type="button" onClick={() => { setSelectedDocumentId(document.id); setDocumentDetailTab('preview'); }}>…</button></div></div>)}</div><aside className="audiobook-document-inline-details"><p className="eyebrow">Document details</p><h3>{selectedDocument?.title ?? 'No document selected'}</h3><p>{selectedDocument?.preview ?? 'Select a document to preview it.'}</p><div className="audiobook-card-actions"><button type="button" className="audiobook-primary-action" disabled={!selectedDocument} onClick={() => { if (selectedDocument) openDocument(selectedDocument); }}>↗ Open section</button>{selectedDocument?.href && <a className="audiobook-button-link" href={selectedDocument.href}>{selectedDocument.id === 'manuscript' ? 'Download source' : 'View report'}</a>}</div></aside></div>
        </section>;
      })()}
      {workspaceMode === 'review' && librarySection === 'characters' && <section className="audiobook-card audiobook-characters-panel" id="audiobook-cast-main">
        <div className="audiobook-section-title"><div><p className="eyebrow">Cast and direct</p><h2>Character-to-voice mapping</h2><p className="audiobook-subtitle">Assign voices, add aliases, and audition the cast against real manuscript spans.</p></div><form className="audiobook-inline audiobook-add-inline" onSubmit={submitSpeaker}><label>New speaker<input aria-label="New speaker" value={speakerName} onChange={(event) => setSpeakerName(event.target.value)} placeholder="Character or narrator" /></label><button disabled={busy || !speakerName.trim()}>＋ Add character</button></form></div>
        <div className="audiobook-card-actions">
          <p className="audiobook-subtitle">Review the quote spans first, then classify text to assign each passage to a speaker. Your voice selections remain saved.</p>
          <button type="button" disabled={busy || extractionRunning || reclassificationRunning || rulesNeedExtraction || !project.current_source_revision_id}
            onClick={() => void action(() => reclassifyAudiobook(project.id, classificationRules[project.id] ?? project.classification_rules ?? ''), 'Text classification queued.')}>
            {reclassificationRunning ? 'Classifying…' : 'Classify text'}
          </button>
          {classificationBlockedReason && <p className="audiobook-hint">{classificationBlockedReason}</p>}
        </div>
        <div className="audiobook-cast-grid">{project.speakers.map((speaker) => <article className="audiobook-cast-card" key={speaker.id}><div><p className="audiobook-avatar">{speaker.canonical_name.slice(0, 1).toUpperCase()}</p><h3>{speaker.canonical_name}</h3><small>{speaker.kind} · {speaker.status === 'proposed' ? 'Detected · assign a voice to confirm' : speaker.casting ? 'Voice assigned' : 'Needs a voice'}</small>{speaker.analysis_metadata && (speaker.analysis_metadata.role || speaker.analysis_metadata.estimated_age || speaker.analysis_metadata.gender_presentation || speaker.analysis_metadata.traits?.length) && <p className="audiobook-hint"><strong>AI profile · </strong>{[speaker.analysis_metadata.role, speaker.analysis_metadata.estimated_age, speaker.analysis_metadata.gender_presentation, ...(speaker.analysis_metadata.traits ?? []).slice(0, 3)].filter(Boolean).join(' · ')}</p>}{speaker.proposed_aliases?.length ? <div className="audiobook-proposed-aliases"><small>Suggested aliases</small>{speaker.proposed_aliases.map((alias) => <button type="button" key={alias} disabled={busy} aria-label={`Confirm alias ${alias} for ${speaker.canonical_name}`} onClick={() => void action(() => audiobookApi.addAlias(project.id, speaker.id, alias), `Alias ${alias} confirmed for ${speaker.canonical_name}.`)}>{alias} · confirm</button>)}</div> : null}</div>
          <label>Assigned voice<select value={speaker.casting?.voice_profile_id ?? ''} disabled={busy} aria-label={`Main voice for ${speaker.canonical_name}`} onChange={(event) => { const voice_profile_id = event.currentTarget.value; if (voice_profile_id) void action(() => audiobookApi.assignVoice(project.id, speaker.id, voice_profile_id), `Voice assigned to ${speaker.canonical_name}.`); }}><option value="">{speaker.status === 'proposed' ? 'Choose voice · confirms character' : 'Choose voice'}</option>{voicesQuery.data?.voices.map((voice) => <option key={voice.id} value={voice.id}>{voice.name}{voice.language ? ` · ${voice.language}` : ''}</option>)}</select></label>
          <div className="audiobook-card-actions"><button type="button" disabled={busy} onClick={() => void action(async () => { const location = await findSpeakerSpan(speaker.id); setChapterId(location.chapterId); setSelectedSpanId(location.spanId); navigateLibrary('projects'); }, `Located ${speaker.canonical_name}.`)}>Find span</button><button type="button" disabled={busy || !speaker.casting} onClick={() => void action(async () => { const modelRevision = await getInstalledModelRevision(); const location = await findSpeakerSpan(speaker.id); await audiobookApi.preview(project.id, { chapter_id: location.chapterId, span_id: location.spanId, model_revision: modelRevision.trim() }); }, `Audition queued for ${speaker.canonical_name}.`)}>Audition</button>{speaker.status === 'proposed' && <button type="button" disabled={busy || Boolean(speaker.occurrence_count)} title={speaker.occurrence_count ? 'Resolve or reassign this character’s spans before dismissing it.' : 'Dismiss this detected character'} onClick={() => rejectProposedSpeaker(speaker)}>Dismiss detection</button>}</div>
          <div className="audiobook-alias-controls"><input aria-label={`Main alias for ${speaker.canonical_name}`} placeholder="Add alias" value={aliasNames[speaker.id] ?? ''} onChange={(event) => setAliasNames((previous) => ({ ...previous, [speaker.id]: event.target.value }))} /><button type="button" disabled={busy || !aliasNames[speaker.id]?.trim()} onClick={() => void action(async () => { await audiobookApi.addAlias(project.id, speaker.id, aliasNames[speaker.id].trim()); setAliasNames((previous) => ({ ...previous, [speaker.id]: '' })); }, 'Speaker alias confirmed.')}>Add alias</button></div>
        </article>)}</div>
        {proposedSpeakers.length > 0 && <div className="audiobook-message" role="status"><strong>{proposedSpeakers.length} detected speaker{proposedSpeakers.length === 1 ? '' : 's'} awaiting confirmation.</strong> Assigning a voice confirms a detected character automatically, or confirm one now without casting.<div className="audiobook-card-actions">{proposedSpeakers.map((speaker) => <button type="button" key={speaker.id} disabled={busy} onClick={() => confirmProposedSpeaker(speaker)}>Confirm {speaker.canonical_name}{speaker.occurrence_count ? ` (${speaker.occurrence_count} spans)` : ''}</button>)}</div></div>}
        {project.review_issues.length > 0 && <div className="audiobook-message" role="status"><strong>Human review required · {project.review_issues.length} open issue{project.review_issues.length === 1 ? '' : 's'}</strong><p>Resolve low-confidence, ambiguous, or contradictory span interpretations before rendering.</p><button type="button" onClick={() => navigateLibrary('projects')}>Open human review queue</button></div>}
        {project.speakers.length === 0 && <p>No speakers have been detected yet. Upload a source book or add one above.</p>}
      </section>}
      {workspaceMode === 'review' && librarySection === 'voices' && <section className="audiobook-card audiobook-voices-panel">
        <div className="audiobook-section-title"><div><p className="eyebrow">Voice library</p><h2>Choose a voice</h2><p className="audiobook-subtitle">Use installed voice profiles and preview them against a cast member.</p></div><label>Assign to speaker<select aria-label="Voice assignment target" value={voiceTargetSpeakerId} onChange={(event) => setVoiceTargetSpeakerId(event.target.value)}><option value="">Choose speaker</option>{castableSpeakers.map((speaker) => <option key={speaker.id} value={speaker.id}>{speaker.canonical_name}{speaker.status === 'proposed' ? ' · detected' : ''}</option>)}</select></label></div>
        <div className="audiobook-voice-grid">{voicesQuery.data?.voices.map((voice) => <article className={`audiobook-voice-card${voice.id === selectedVoiceId ? ' selected' : ''}`} key={voice.id} onClick={() => setSelectedVoiceId(voice.id)}><div className="audiobook-voice-icon">◉</div><div><h3>{voice.name}</h3><p>{voice.language || 'Language unspecified'}</p></div><div className="audiobook-card-actions"><button type="button" disabled={busy || !voiceTargetSpeakerId} onClick={() => { setSelectedVoiceId(voice.id); void action(() => audiobookApi.assignVoice(project.id, voiceTargetSpeakerId, voice.id), 'Voice assigned.'); }}>Use voice</button><button type="button" disabled={busy || !voiceTargetSpeakerId} onClick={() => void action(async () => { const modelRevision = await getInstalledModelRevision(); const location = await findSpeakerSpan(voiceTargetSpeakerId); await audiobookApi.preview(project.id, { chapter_id: location.chapterId, span_id: location.spanId, voice_profile_id: voice.id, model_revision: modelRevision.trim() }); }, 'Voice preview queued.')}>Preview</button></div></article>)}</div>
        {voicesQuery.data?.voices.length === 0 && <p className="audiobook-hint">No local voices are installed. Add a voice profile in Voice Cloning to cast speakers.</p>}
      </section>}
      {workspaceMode === 'review' && librarySection === 'pronunciations' && <section className="audiobook-card audiobook-pronunciations-panel" id="audiobook-pronunciations-main">
        <div className="audiobook-section-title"><div><p className="eyebrow">Speech plan</p><h2>Pronunciations</h2><p className="audiobook-subtitle">Keep names, places, and unique terms consistent across the audiobook.</p></div><label className="audiobook-search-field">Search pronunciations<input aria-label="Search pronunciations" value={pronunciationSearch} onChange={(event) => setPronunciationSearch(event.target.value)} placeholder="Search names, places, terms…" /></label></div>
        <form className="audiobook-pronunciation-form" onSubmit={submitPronunciation}><label>Source term<input value={sourceTerm} onChange={(event) => setSourceTerm(event.target.value)} maxLength={128} placeholder="Hollow Bay" /></label><label>Spoken term<input value={spokenTerm} onChange={(event) => setSpokenTerm(event.target.value)} maxLength={256} placeholder="Hollow Bay" /></label><button disabled={busy || !sourceTerm.trim() || !spokenTerm.trim()}>＋ Add pronunciation</button></form>
        <div className="audiobook-pronunciation-table"><div className="audiobook-pronunciation-table-head"><span>Source term</span><span>Spoken term</span><span>Revision</span><span>Status</span></div>{project.pronunciations?.filter((entry) => `${entry.source_term} ${entry.spoken_term}`.toLowerCase().includes(pronunciationSearch.toLowerCase())).map((entry) => <div className="audiobook-pronunciation-table-row" key={entry.source_term}><strong>{entry.source_term}</strong><span>{entry.spoken_term}</span><span>v{entry.revision}</span><em>● Verified</em></div>)}</div>
        {project.pronunciations?.length === 0 && <p>No pronunciations saved yet.</p>}
      </section>}
    </>
  );
}
