import { SETTINGS_SCHEMA_VERSION, type SettingsDocument } from './settingsDocumentTypes';

export const DEFAULT_SETTINGS_DOCUMENT: SettingsDocument = {
  schemaVersion: SETTINGS_SCHEMA_VERSION,
  revision: 'default',
  global: {
    providers: { llm: 'lmstudio', tts: 'faster-qwen3-tts', stt: 'parakeet', image: 'image:flux_klein', voiceCloning: '' },
    models: { chat: '', fast: '', quality: '', background: '', embedding: '', imagePrompt: '' },
    routing: { fallbackBehavior: 'next-available', taskOverrides: {} },
  },
  providerConfigs: {
    lmstudio: { baseUrl: 'http://localhost:1234', model: '', direct: false },
    openrouter: { apiKey: '', model: 'openai/gpt-4o-mini', contextSize: 128000, thinkingBudget: 0 },
    cerebras: { apiKey: '', model: 'llama-3.3-70b-versatile' },
    llamacpp: { baseUrl: 'http://localhost:8080', model: '', downloadLocation: 'server', autoStart: false },
    fasterQwen3Tts: { modelName: 'Qwen/Qwen3-TTS-12Hz-0.6B-Base', modelDir: '', device: 'cuda', dtype: 'bfloat16', chunkSize: 12, nonStreamingMode: true },
    parakeet: { baseUrl: 'http://127.0.0.1:5201' },
    fluxKlein: { enabled: false, repoId: 'black-forest-labs/FLUX.2-klein-4B', localDir: '', device: 'cuda', torchDtype: 'bfloat16', preferLocalFiles: true, allowRepoFallback: false },
  },
  appearance: { mode: 'system', theme: 'aurora', density: 'comfortable', textScale: 100, reduceMotion: false, liveCaptions: true },
  assistant: {
    personalityId: 'omnix-default',
    customPersonality: '',
    voiceId: '',
    autoSpeakReplies: false,
    speechLanguage: 'en-US',
    streamingAudio: true,
    researchDefaultMode: 'disabled',
    researchProvider: 'duckduckgo',
    researchMaxResults: 5,
    researchMaxSteps: 6,
    researchMaxQueries: 5,
    researchMaxSources: 12,
    researchMaxExtracts: 8,
    researchSearchCacheTtlSeconds: 300,
    researchExtractionCacheTtlSeconds: 3600,
    researchRawRetentionDays: 7,
    researchManifestRetentionDays: 30,
    researchShowDiagnostics: true,
    researchDeepEnabled: false,
    researchHermesPlannerEnabled: false,
    desktopCompanionEnabled: false,
    desktopCompanionRolloutStage: 'disabled',
    desktopCompanionVisionModelId: '',
    desktopCompanionRemoteVisionAllowed: false,
    desktopCompanionShowDiagnostics: false,
    desktopCompanionBackgroundCallsPerMinute: 6,
    desktopCompanionMinimumObservationIntervalMs: 8_000,
    desktopCompanionObservationTimeoutMs: 10_000,
    desktopCompanionObservationTtlMs: 12_000,
    desktopCompanionCommentaryCooldownMs: 25_000,
    desktopCompanionMinimumChangeConfidence: 0.55,
  },
  voice: { language: 'English', stability: 0.75, similarity: 0.8, style: 0.35, speed: 1, pitch: 0, volume: 0, effects: [], streaming: true, cloningLanguage: 'English', cloningQuality: 'High' },
  storyteller: { providerId: '', modelId: '', tone: 'Cozy', writingStyle: 'Lyrical & Descriptive', readSpeed: 1, pauseParagraphMs: 500, pauseChapterMs: 1200, readChapterTitles: true, readStylePreset: 'Dramatic audiobook', pronunciation: {} },
  podcast: { providerId: '', modelId: '', format: 'interview', durationMinutes: 5, tone: 'Professional', language: 'English (US)', generationStyle: 'automatic', autoplay: false, playbackRate: 1, stability: 0.72, similarity: 0.78, effects: ['Compression', 'De-esser'] },
  rpg: { difficulty: 'normal', worldActivity: 'standard', economyPressure: 'normal', combatLethality: 'normal', companions: true, permadeath: false, autosave: true, validator: true, backgroundSoftAudit: true, llmNarration: true, imageGeneration: false, tts: false, stt: false, campaignDefaults: {}, hermesAssistMode: 'review_each_step' },
  image: { width: 768, height: 768, aspectRatio: '1:1', portraitPreset: '', scenePreset: '', unloadAfterGeneration: false },
  stt: { language: '', alignment: true, saveTranscript: true, microphoneDeviceId: '', noiseSuppression: true, echoCancellation: true },
  storage: { saveOutputByDefault: true, retentionDays: 30, temporaryAssetCleanup: true },
};