//@version=5
indicator("Trend Follower (manual ATR bands)", overlay=true)
src = input.source(hl2, "Source")
periods = input.int(10, "ATR Period")
multiplier = input.float(3.0, "ATR Multiplier", step=0.1)
useBuiltin = input.bool(true, "Use built-in ATR")
atr2 = ta.sma(ta.tr, periods)
atr = useBuiltin ? ta.atr(periods) : atr2
up = src - (multiplier * atr)
up1 = nz(up[1], up)
up := close[1] > up1 ? math.max(up, up1) : up
dn = src + (multiplier * atr)
dn1 = nz(dn[1], dn)
dn := close[1] < dn1 ? math.min(dn, dn1) : dn
var int trend = 1
trend := trend == -1 and close > dn1 ? 1 : trend == 1 and close < up1 ? -1 : trend
plot(trend == 1 ? up : na, "Up Trend", style=plot.style_linebr, linewidth=2, color=color.green)
buySignal = trend == 1 and trend[1] == -1
plotshape(buySignal ? up : na, "UpTrend Begins", location=location.absolute, style=shape.circle, size=size.tiny, color=color.green)
plot(trend == 1 ? na : dn, "Down Trend", style=plot.style_linebr, linewidth=2, color=color.red)
sellSignal = trend == -1 and trend[1] == 1
plotshape(sellSignal ? dn : na, "DownTrend Begins", location=location.absolute, style=shape.circle, size=size.tiny, color=color.red)
alertcondition(buySignal, title="Buy", message="Trend turned up")
alertcondition(sellSignal, title="Sell", message="Trend turned down")
