"""Character Mode contracts, persistence, and server-side resolution."""
from .interaction import (
    CharacterInteractionError,
    CharacterModeDisabledError,
    CharacterResolutionError,
    character_hermes_sync_enabled,
    character_memory_enabled,
    character_mode_enabled,
    character_shared_memory_enabled,
    neutralize_legacy_system_prompt,
    resolve_interaction_context,
    resolve_system_session_identity,
)
from .models import (
    DEFAULT_CHARACTER_IDENTITY_POLICY,
    DEFAULT_CHARACTER_SHARED_MEMORY_POLICY,
    SYSTEM_ASSISTANT_ID,
    SYSTEM_ASSISTANT_IDENTITY,
    SYSTEM_ASSISTANT_NAME,
    ArchiveCharacterResponse,
    CharacterListResponse,
    CharacterProfile,
    CharacterProfileSnapshot,
    CharacterProfileVersion,
    CharacterStatus,
    CharacterVersionListResponse,
    ConversationSegment,
    CreateCharacterRequest,
    InteractionMode,
    InteractionSelection,
    ResolvedInteractionContext,
    SharedMemoryAccess,
    TranscriptPolicy,
    UpdateCharacterRequest,
)
from .repository import (
    CharacterConflictError,
    CharacterNotFoundError,
    CharacterRepository,
    default_character_db_path,
)
from .service import CharacterService, CharacterVoiceAssetError, default_character_service
from .session_models import SetSessionInteractionRequest

__all__ = [
    "ArchiveCharacterResponse",
    "CharacterConflictError",
    "CharacterInteractionError",
    "CharacterListResponse",
    "CharacterModeDisabledError",
    "CharacterNotFoundError",
    "CharacterProfile",
    "CharacterProfileSnapshot",
    "CharacterProfileVersion",
    "CharacterRepository",
    "CharacterResolutionError",
    "CharacterService",
    "CharacterStatus",
    "CharacterVersionListResponse",
    "CharacterVoiceAssetError",
    "ConversationSegment",
    "CreateCharacterRequest",
    "DEFAULT_CHARACTER_IDENTITY_POLICY",
    "DEFAULT_CHARACTER_SHARED_MEMORY_POLICY",
    "InteractionMode",
    "InteractionSelection",
    "ResolvedInteractionContext",
    "SYSTEM_ASSISTANT_ID",
    "SYSTEM_ASSISTANT_IDENTITY",
    "SYSTEM_ASSISTANT_NAME",
    "SetSessionInteractionRequest",
    "SharedMemoryAccess",
    "TranscriptPolicy",
    "UpdateCharacterRequest",
    "character_hermes_sync_enabled",
    "character_memory_enabled",
    "character_mode_enabled",
    "character_shared_memory_enabled",
    "default_character_db_path",
    "default_character_service",
    "neutralize_legacy_system_prompt",
    "resolve_interaction_context",
    "resolve_system_session_identity",
]
