from __future__ import annotations

from typing import Any, Dict

COMBAT_K1_K9_SCENARIOS: Dict[str, Dict[str, Any]] = {
    "combat_defend_reduces_next_incoming_attack": {
        "currency": {"gold": 0, "silver": 0, "copper": 0},
        "conversation_settings": {
            "enabled": True,
            "autonomous_ticks_enabled": False,
            "frequency": "never",
            "conversation_chance_percent": 0,
            "allow_player_invited": False,
            "player_inclusion_chance_percent": 0,
            "npc_file_profiles_enabled": True,
            "npc_evolution_enabled": True,
            "min_ticks_between_conversations": 0,
            "thread_cooldown_ticks": 0
        },
        "setup_interaction_state": {
            "scene_items": [],
            "scene_objects": [],
            "player_location_id": "loc_tavern_road",
            "player_hp": 20,
            "player_max_hp": 20,
            "player_inventory": {"items": [], "equipment": {}, "carry_capacity": 50.0},
            "party_state": {"max_size": 4, "companions": []}
        },
        "turns": [
            "I attack the bandit.",
            "__manual_force_player_combat_turn__",
            "I defend."
        ]
    },
    "combat_use_item_consumes_turn_and_applies_effect": {
        "currency": {"gold": 0, "silver": 0, "copper": 0},
        "conversation_settings": {
            "enabled": True,
            "autonomous_ticks_enabled": False,
            "frequency": "never",
            "conversation_chance_percent": 0,
            "allow_player_invited": False,
            "player_inclusion_chance_percent": 0,
            "npc_file_profiles_enabled": True,
            "npc_evolution_enabled": True,
            "min_ticks_between_conversations": 0,
            "thread_cooldown_ticks": 0
        },
        "setup_interaction_state": {
            "scene_items": [],
            "scene_objects": [],
            "player_location_id": "loc_tavern_road",
            "player_hp": 5,
            "player_max_hp": 20,
            "player_inventory": {
                "items": [
                    {
                        "item_id": "item:minor_healing_potion",
                        "definition_id": "item:minor_healing_potion",
                        "name": "minor healing potion",
                        "aliases": ["potion", "healing potion"],
                        "qty": 1,
                        "quantity": 1
                    }
                ],
                "equipment": {},
                "carry_capacity": 50.0
            },
            "party_state": {"max_size": 4, "companions": []}
        },
        "turns": [
            "I attack the bandit.",
            "__manual_force_player_combat_turn__",
            "I drink the healing potion."
        ]
    },
    "combat_flee_success_or_failure_is_authoritative": {
        "currency": {"gold": 0, "silver": 0, "copper": 0},
        "conversation_settings": {
            "enabled": True,
            "autonomous_ticks_enabled": False,
            "frequency": "never",
            "conversation_chance_percent": 0,
            "allow_player_invited": False,
            "player_inclusion_chance_percent": 0,
            "npc_file_profiles_enabled": True,
            "npc_evolution_enabled": True,
            "min_ticks_between_conversations": 0,
            "thread_cooldown_ticks": 0
        },
        "setup_interaction_state": {
            "scene_items": [],
            "scene_objects": [],
            "player_location_id": "loc_tavern_road",
            "player_hp": 20,
            "player_max_hp": 20,
            "player_inventory": {"items": [], "equipment": {}, "carry_capacity": 50.0},
            "party_state": {"max_size": 4, "companions": []}
        },
        "turns": [
            "I attack the bandit.",
            "__manual_force_player_combat_turn__",
            "I flee."
        ]
    },
    "combat_critical_hit_applies_bleeding": {
        "currency": {"gold": 0, "silver": 0, "copper": 0},
        "conversation_settings": {
            "enabled": True,
            "autonomous_ticks_enabled": False,
            "frequency": "never",
            "conversation_chance_percent": 0,
            "allow_player_invited": False,
            "player_inclusion_chance_percent": 0,
        },
        "setup_interaction_state": {
            "player_location_id": "loc_tavern_road",
            "player_hp": 20,
            "player_max_hp": 20,
            "player_inventory": {"items": [], "equipment": {}, "carry_capacity": 50.0},
            "party_state": {"max_size": 4, "companions": []},
            "combat_state": {
                "active": True,
                "round": 1,
                "turn_index": 0,
                "current_actor_id": "player",
                "force_next_attack_roll": 20,
                "initiative_order": [
                    {"actor_id": "player", "initiative": 20, "roll": 20, "bonus": 0},
                    {"actor_id": "enemy:bandit_1", "initiative": 1, "roll": 1, "bonus": 0},
                ],
                "participants": {
                    "player": {
                        "actor_id": "player",
                        "side": "party",
                        "name": "You",
                        "hp": 20,
                        "max_hp": 20,
                        "status": "active",
                    },
                    "enemy:bandit_1": {
                        "actor_id": "enemy:bandit_1",
                        "side": "enemy",
                        "name": "Bandit",
                        "hp": 12,
                        "max_hp": 12,
                        "defense": 10,
                        "armor": 0,
                        "status": "active",
                    },
                },
                "combat_log": [],
                "source": "manual_condition_test",
            },
        },
        "turns": ["I attack the bandit."],
    },
    "combat_heavy_hit_applies_stunned": {
        "currency": {"gold": 0, "silver": 0, "copper": 0},
        "conversation_settings": {
            "enabled": True,
            "autonomous_ticks_enabled": False,
            "frequency": "never",
            "conversation_chance_percent": 0,
            "allow_player_invited": False,
            "player_inclusion_chance_percent": 0,
        },
        "setup_interaction_state": {
            "player_location_id": "loc_tavern_road",
            "player_hp": 20,
            "player_max_hp": 20,
            "player_inventory": {"items": [], "equipment": {}, "carry_capacity": 50.0},
            "party_state": {"max_size": 4, "companions": []},
            "combat_state": {
                "active": True,
                "round": 1,
                "turn_index": 0,
                "current_actor_id": "player",
                "force_next_damage": 6,
                "initiative_order": [
                    {"actor_id": "player", "initiative": 20, "roll": 20, "bonus": 0},
                    {"actor_id": "enemy:bandit_1", "initiative": 1, "roll": 1, "bonus": 0},
                ],
                "participants": {
                    "player": {
                        "actor_id": "player",
                        "side": "party",
                        "name": "You",
                        "hp": 20,
                        "max_hp": 20,
                        "status": "active",
                    },
                    "enemy:bandit_1": {
                        "actor_id": "enemy:bandit_1",
                        "side": "enemy",
                        "name": "Bandit",
                        "hp": 12,
                        "max_hp": 12,
                        "defense": 10,
                        "armor": 0,
                        "status": "active",
                    },
                },
                "combat_log": [],
                "source": "manual_condition_test",
            },
        },
        "turns": ["I attack the bandit."],
    },
    "combat_bleeding_ticks_damage": {
        "currency": {"gold": 0, "silver": 0, "copper": 0},
        "conversation_settings": {
            "enabled": True,
            "autonomous_ticks_enabled": False,
            "frequency": "never",
            "conversation_chance_percent": 0,
            "allow_player_invited": False,
            "player_inclusion_chance_percent": 0,
        },
        "setup_interaction_state": {
            "player_location_id": "loc_tavern_road",
            "player_hp": 20,
            "player_max_hp": 20,
            "player_inventory": {"items": [], "equipment": {}, "carry_capacity": 50.0},
            "party_state": {"max_size": 4, "companions": []},
            "combat_state": {
                "active": True,
                "round": 1,
                "turn_index": 0,
                "current_actor_id": "enemy:bandit_1",
                "initiative_order": [
                    {"actor_id": "enemy:bandit_1", "initiative": 20, "roll": 20, "bonus": 0},
                    {"actor_id": "player", "initiative": 1, "roll": 1, "bonus": 0},
                ],
                "participants": {
                    "player": {
                        "actor_id": "player",
                        "side": "party",
                        "name": "You",
                        "hp": 20,
                        "max_hp": 20,
                        "status": "active",
                    },
                    "enemy:bandit_1": {
                        "actor_id": "enemy:bandit_1",
                        "side": "enemy",
                        "name": "Bandit",
                        "hp": 8,
                        "max_hp": 12,
                        "status": "active",
                        "status_effects": [
                            {
                                "effect_id": "effect:bleeding:enemy:bandit_1:test",
                                "kind": "bleeding",
                                "source": "combat",
                                "source_actor_id": "player",
                                "target_actor_id": "enemy:bandit_1",
                                "duration_turns": 2,
                                "stacks": 1,
                                "magnitude": 1,
                                "tick_timing": "start_of_turn",
                            }
                        ],
                    },
                },
                "combat_log": [],
                "source": "manual_condition_test",
            },
        },
        "turns": ["__manual_resolve_current_combat_actor__"],
    },
    "combat_stabilize_downed_companion": {
        "currency": {"gold": 0, "silver": 0, "copper": 0},
        "conversation_settings": {
            "enabled": True,
            "autonomous_ticks_enabled": False,
            "frequency": "never",
            "conversation_chance_percent": 0,
            "allow_player_invited": False,
            "player_inclusion_chance_percent": 0,
        },
        "setup_interaction_state": {
            "player_location_id": "loc_tavern_road",
            "player_hp": 20,
            "player_max_hp": 20,
            "player_inventory": {"items": [], "equipment": {}, "carry_capacity": 50.0},
            "party_state": {
                "max_size": 4,
                "companions": [{"npc_id": "npc:bran", "name": "Bran"}],
            },
            "combat_state": {
                "active": True,
                "round": 1,
                "turn_index": 0,
                "current_actor_id": "player",
                "initiative_order": [
                    {"actor_id": "player", "initiative": 20, "roll": 20, "bonus": 0},
                    {"actor_id": "npc:bran", "initiative": 10, "roll": 10, "bonus": 0},
                ],
                "participants": {
                    "player": {
                        "actor_id": "player",
                        "side": "party",
                        "name": "You",
                        "hp": 20,
                        "max_hp": 20,
                        "status": "active",
                    },
                    "npc:bran": {
                        "actor_id": "npc:bran",
                        "side": "party",
                        "name": "Bran",
                        "hp": 0,
                        "max_hp": 14,
                        "status": "downed",
                        "status_effects": [
                            {
                                "effect_id": "effect:downed:npc:bran:test",
                                "kind": "downed",
                                "source": "combat",
                                "source_actor_id": "enemy:bandit_1",
                                "target_actor_id": "npc:bran",
                                "duration_turns": 999,
                                "stacks": 1,
                                "magnitude": 1,
                                "tick_timing": "none",
                            }
                        ],
                    },
                },
                "combat_log": [],
                "source": "manual_recovery_test",
            },
        },
        "turns": ["I stabilize Bran."],
    },
    "combat_heal_downed_companion_revives": {
        "currency": {"gold": 0, "silver": 0, "copper": 0},
        "conversation_settings": {
            "enabled": True,
            "autonomous_ticks_enabled": False,
            "frequency": "never",
            "conversation_chance_percent": 0,
            "allow_player_invited": False,
            "player_inclusion_chance_percent": 0,
        },
        "setup_interaction_state": {
            "player_location_id": "loc_tavern_road",
            "player_hp": 20,
            "player_max_hp": 20,
            "player_inventory": {
                "items": [
                    {
                        "item_id": "item:minor_healing_potion",
                        "definition_id": "item:minor_healing_potion",
                        "name": "minor healing potion",
                        "aliases": ["potion", "healing potion"],
                        "qty": 1,
                        "quantity": 1,
                    }
                ],
                "equipment": {},
                "carry_capacity": 50.0,
            },
            "party_state": {
                "max_size": 4,
                "companions": [{"npc_id": "npc:bran", "name": "Bran"}],
            },
            "combat_state": {
                "active": True,
                "round": 1,
                "turn_index": 0,
                "current_actor_id": "player",
                "initiative_order": [
                    {"actor_id": "player", "initiative": 20, "roll": 20, "bonus": 0},
                    {"actor_id": "npc:bran", "initiative": 10, "roll": 10, "bonus": 0},
                ],
                "participants": {
                    "player": {
                        "actor_id": "player",
                        "side": "party",
                        "name": "You",
                        "hp": 20,
                        "max_hp": 20,
                        "status": "active",
                    },
                    "npc:bran": {
                        "actor_id": "npc:bran",
                        "side": "party",
                        "name": "Bran",
                        "hp": 0,
                        "max_hp": 14,
                        "status": "downed",
                        "status_effects": [
                            {
                                "effect_id": "effect:downed:npc:bran:test",
                                "kind": "downed",
                                "source": "combat",
                                "source_actor_id": "enemy:bandit_1",
                                "target_actor_id": "npc:bran",
                                "duration_turns": 999,
                                "stacks": 1,
                                "magnitude": 1,
                                "tick_timing": "none",
                            },
                            {
                                "effect_id": "effect:unconscious:npc:bran:test",
                                "kind": "unconscious",
                                "source": "combat",
                                "source_actor_id": "enemy:bandit_1",
                                "target_actor_id": "npc:bran",
                                "duration_turns": 999,
                                "stacks": 1,
                                "magnitude": 1,
                                "tick_timing": "none",
                            },
                        ],
                    },
                },
                "combat_log": [],
                "source": "manual_recovery_test",
            },
        },
        "turns": ["I use the healing potion on Bran."],
    },
    "combat_enemy_targets_low_hp_companion": {
        "currency": {"gold": 0, "silver": 0, "copper": 0},
        "conversation_settings": {
            "enabled": True,
            "autonomous_ticks_enabled": False,
            "frequency": "never",
            "conversation_chance_percent": 0,
            "allow_player_invited": False,
            "player_inclusion_chance_percent": 0,
        },
        "setup_interaction_state": {
            "player_location_id": "loc_tavern_road",
            "player_hp": 20,
            "player_max_hp": 20,
            "player_inventory": {"items": [], "equipment": {}, "carry_capacity": 50.0},
            "party_state": {
                "max_size": 4,
                "companions": [{"npc_id": "npc:bran", "name": "Bran"}],
            },
            "combat_state": {
                "active": True,
                "round": 1,
                "turn_index": 0,
                "current_actor_id": "enemy:bandit_1",
                "initiative_order": [
                    {"actor_id": "enemy:bandit_1", "initiative": 20, "roll": 20, "bonus": 0},
                    {"actor_id": "player", "initiative": 10, "roll": 10, "bonus": 0},
                    {"actor_id": "npc:bran", "initiative": 5, "roll": 5, "bonus": 0},
                ],
                "participants": {
                    "enemy:bandit_1": {
                        "actor_id": "enemy:bandit_1",
                        "side": "enemy",
                        "name": "Bandit",
                        "hp": 12,
                        "max_hp": 12,
                        "status": "active",
                        "morale_threshold": 20,
                    },
                    "player": {
                        "actor_id": "player",
                        "side": "party",
                        "name": "You",
                        "hp": 20,
                        "max_hp": 20,
                        "status": "active",
                    },
                    "npc:bran": {
                        "actor_id": "npc:bran",
                        "side": "party",
                        "name": "Bran",
                        "hp": 3,
                        "max_hp": 14,
                        "status": "active",
                    },
                },
                "combat_log": [],
                "source": "manual_enemy_ai_test",
            },
        },
        "turns": ["__manual_resolve_current_combat_actor__"],
    },
    "combat_enemy_avoids_downed_target": {
        "currency": {"gold": 0, "silver": 0, "copper": 0},
        "conversation_settings": {
            "enabled": True,
            "autonomous_ticks_enabled": False,
            "frequency": "never",
            "conversation_chance_percent": 0,
            "allow_player_invited": False,
            "player_inclusion_chance_percent": 0,
        },
        "setup_interaction_state": {
            "player_location_id": "loc_tavern_road",
            "player_hp": 20,
            "player_max_hp": 20,
            "player_inventory": {"items": [], "equipment": {}, "carry_capacity": 50.0},
            "party_state": {
                "max_size": 4,
                "companions": [{"npc_id": "npc:bran", "name": "Bran"}],
            },
            "combat_state": {
                "active": True,
                "round": 1,
                "turn_index": 0,
                "current_actor_id": "enemy:bandit_1",
                "initiative_order": [
                    {"actor_id": "enemy:bandit_1", "initiative": 20, "roll": 20, "bonus": 0},
                    {"actor_id": "npc:bran", "initiative": 10, "roll": 10, "bonus": 0},
                    {"actor_id": "player", "initiative": 5, "roll": 5, "bonus": 0},
                ],
                "participants": {
                    "enemy:bandit_1": {
                        "actor_id": "enemy:bandit_1",
                        "side": "enemy",
                        "name": "Bandit",
                        "hp": 12,
                        "max_hp": 12,
                        "status": "active",
                        "morale_threshold": 20,
                    },
                    "npc:bran": {
                        "actor_id": "npc:bran",
                        "side": "party",
                        "name": "Bran",
                        "hp": 0,
                        "max_hp": 14,
                        "status": "downed",
                        "status_effects": [
                            {
                                "effect_id": "effect:downed:npc:bran:test",
                                "kind": "downed",
                                "source": "combat",
                                "source_actor_id": "enemy:bandit_1",
                                "target_actor_id": "npc:bran",
                                "duration_turns": 999,
                                "stacks": 1,
                                "magnitude": 1,
                                "tick_timing": "none",
                            }
                        ],
                    },
                    "player": {
                        "actor_id": "player",
                        "side": "party",
                        "name": "You",
                        "hp": 20,
                        "max_hp": 20,
                        "status": "active",
                    },
                },
                "combat_log": [],
                "source": "manual_enemy_ai_test",
            },
        },
        "turns": ["__manual_resolve_current_combat_actor__"],
    },
    "combat_enemy_defends_when_low_hp_but_not_fleeing": {
        "currency": {"gold": 0, "silver": 0, "copper": 0},
        "conversation_settings": {
            "enabled": True,
            "autonomous_ticks_enabled": False,
            "frequency": "never",
            "conversation_chance_percent": 0,
            "allow_player_invited": False,
            "player_inclusion_chance_percent": 0,
        },
        "setup_interaction_state": {
            "player_location_id": "loc_tavern_road",
            "player_hp": 20,
            "player_max_hp": 20,
            "player_inventory": {"items": [], "equipment": {}, "carry_capacity": 50.0},
            "party_state": {"max_size": 4, "companions": []},
            "combat_state": {
                "active": True,
                "round": 1,
                "turn_index": 0,
                "current_actor_id": "enemy:bandit_1",
                "initiative_order": [
                    {"actor_id": "enemy:bandit_1", "initiative": 20, "roll": 20, "bonus": 0},
                    {"actor_id": "player", "initiative": 10, "roll": 10, "bonus": 0},
                ],
                "participants": {
                    "enemy:bandit_1": {
                        "actor_id": "enemy:bandit_1",
                        "side": "enemy",
                        "name": "Bandit",
                        "hp": 4,
                        "max_hp": 12,
                        "status": "active",
                        "morale_threshold": 5,
                    },
                    "player": {
                        "actor_id": "player",
                        "side": "party",
                        "name": "You",
                        "hp": 20,
                        "max_hp": 20,
                        "status": "active",
                    },
                },
                "combat_log": [],
                "source": "manual_enemy_ai_test",
            },
        },
        "turns": ["__manual_resolve_current_combat_actor__"],
    },
    "combat_enemy_flees_on_low_morale": {
        "currency": {"gold": 0, "silver": 0, "copper": 0},
        "conversation_settings": {
            "enabled": True,
            "autonomous_ticks_enabled": False,
            "frequency": "never",
            "conversation_chance_percent": 0,
            "allow_player_invited": False,
            "player_inclusion_chance_percent": 0,
        },
        "setup_interaction_state": {
            "player_location_id": "loc_tavern_road",
            "player_hp": 20,
            "player_max_hp": 20,
            "player_inventory": {"items": [], "equipment": {}, "carry_capacity": 50.0},
            "party_state": {"max_size": 4, "companions": []},
            "combat_state": {
                "active": True,
                "round": 1,
                "turn_index": 0,
                "current_actor_id": "enemy:bandit_1",
                "initiative_order": [
                    {"actor_id": "enemy:bandit_1", "initiative": 20, "roll": 20, "bonus": 0},
                    {"actor_id": "player", "initiative": 10, "roll": 10, "bonus": 0},
                ],
                "participants": {
                    "enemy:bandit_1": {
                        "actor_id": "enemy:bandit_1",
                        "side": "enemy",
                        "name": "Bandit",
                        "hp": 1,
                        "max_hp": 12,
                        "status": "active",
                        "morale_threshold": 80,
                    },
                    "player": {
                        "actor_id": "player",
                        "side": "party",
                        "name": "You",
                        "hp": 20,
                        "max_hp": 20,
                        "status": "active",
                    },
                },
                "combat_log": [],
                "source": "manual_enemy_ai_test",
            },
        },
        "turns": ["__manual_resolve_current_combat_actor__"],
    },
    "combat_enemy_stunned_skips_ai_intent": {
        "currency": {"gold": 0, "silver": 0, "copper": 0},
        "conversation_settings": {
            "enabled": True,
            "autonomous_ticks_enabled": False,
            "frequency": "never",
            "conversation_chance_percent": 0,
            "allow_player_invited": False,
            "player_inclusion_chance_percent": 0,
        },
        "setup_interaction_state": {
            "player_location_id": "loc_tavern_road",
            "player_hp": 20,
            "player_max_hp": 20,
            "player_inventory": {"items": [], "equipment": {}, "carry_capacity": 50.0},
            "party_state": {"max_size": 4, "companions": []},
            "combat_state": {
                "active": True,
                "round": 1,
                "turn_index": 0,
                "current_actor_id": "enemy:bandit_1",
                "initiative_order": [
                    {"actor_id": "enemy:bandit_1", "initiative": 20, "roll": 20, "bonus": 0},
                    {"actor_id": "player", "initiative": 10, "roll": 10, "bonus": 0},
                ],
                "participants": {
                    "enemy:bandit_1": {
                        "actor_id": "enemy:bandit_1",
                        "side": "enemy",
                        "name": "Bandit",
                        "hp": 8,
                        "max_hp": 12,
                        "status": "active",
                        "morale_threshold": 20,
                        "status_effects": [
                            {
                                "effect_id": "effect:stunned:enemy:bandit_1:test",
                                "kind": "stunned",
                                "source": "combat",
                                "source_actor_id": "player",
                                "target_actor_id": "enemy:bandit_1",
                                "duration_turns": 1,
                                "stacks": 1,
                                "magnitude": 1,
                                "tick_timing": "none",
                            }
                        ],
                    },
                    "player": {
                        "actor_id": "player",
                        "side": "party",
                        "name": "You",
                        "hp": 20,
                        "max_hp": 20,
                        "status": "active",
                    },
                },
                "combat_log": [],
                "source": "manual_enemy_ai_test",
            },
        },
        "turns": ["__manual_resolve_current_combat_actor__"],
    },
    "combat_enemy_morale_victory_when_last_enemy_flees": {
        "currency": {"gold": 0, "silver": 0, "copper": 0},
        "conversation_settings": {
            "enabled": True,
            "autonomous_ticks_enabled": False,
            "frequency": "never",
            "conversation_chance_percent": 0,
            "allow_player_invited": False,
            "player_inclusion_chance_percent": 0,
        },
        "setup_interaction_state": {
            "player_location_id": "loc_tavern_road",
            "player_hp": 20,
            "player_max_hp": 20,
            "player_inventory": {"items": [], "equipment": {}, "carry_capacity": 50.0},
            "party_state": {"max_size": 4, "companions": []},
            "combat_state": {
                "active": True,
                "round": 1,
                "turn_index": 0,
                "current_actor_id": "enemy:bandit_1",
                "initiative_order": [
                    {"actor_id": "enemy:bandit_1", "initiative": 20, "roll": 20, "bonus": 0},
                    {"actor_id": "player", "initiative": 10, "roll": 10, "bonus": 0},
                ],
                "participants": {
                    "enemy:bandit_1": {
                        "actor_id": "enemy:bandit_1",
                        "side": "enemy",
                        "name": "Bandit",
                        "hp": 1,
                        "max_hp": 12,
                        "status": "active",
                        "morale_threshold": 80,
                    },
                    "player": {
                        "actor_id": "player",
                        "side": "party",
                        "name": "You",
                        "hp": 20,
                        "max_hp": 20,
                        "status": "active",
                    },
                },
                "combat_log": [],
                "source": "manual_enemy_ai_test",
            },
        },
        "turns": ["__manual_resolve_current_combat_actor__"],
    },
}
