from __future__ import annotations

from typing import Any, Dict

NPC_EVOLUTION_COMPANIONS_SCENARIOS: Dict[str, Dict[str, Any]] = {
    "npc_file_profile_bran_loaded": {
        "currency": {"gold": 0, "silver": 0, "copper": 0},
        "conversation_settings": {
            "enabled": True,
            "autonomous_ticks_enabled": True,
            "frequency": "always",
            "conversation_chance_percent": 100,
            "allow_player_invited": True,
            "player_inclusion_chance_percent": 100,
            "npc_file_profiles_enabled": True,
            "min_ticks_between_conversations": 0,
            "thread_cooldown_ticks": 0,
        },
        "turns": [
            "__ambient_tick_player_invited__",
            "Bran, what keeps you busy here?",
        ],
    },
    "npc_evolution_bran_loses_tavern": {
        "currency": {"gold": 0, "silver": 0, "copper": 0},
        "conversation_settings": {
            "enabled": True,
            "autonomous_ticks_enabled": True,
            "frequency": "always",
            "conversation_chance_percent": 100,
            "allow_player_invited": True,
            "player_inclusion_chance_percent": 100,
            "npc_file_profiles_enabled": True,
            "npc_evolution_enabled": True,
            "npc_evolution_from_world_events_enabled": True,
            "min_ticks_between_conversations": 0,
            "thread_cooldown_ticks": 0,
        },
        "setup_world_event": {
            "event_id": "event:test:bandit_attack_rusty_flagon",
            "kind": "location_destroyed",
            "location_id": "loc_tavern",
            "summary": "Bandits attacked and burned the Rusty Flagon.",
            "affected_npcs": ["npc:Bran"],
        },
        "turns": [
            "__apply_world_event_evolution__",
            "__ambient_tick_player_invited__",
            "Bran, what will you do now?",
        ],
    },
    "npc_evolution_reputation_threshold_trust": {
        "currency": {"gold": 0, "silver": 0, "copper": 0},
        "conversation_settings": {
            "enabled": True,
            "autonomous_ticks_enabled": True,
            "frequency": "always",
            "conversation_chance_percent": 100,
            "allow_player_invited": True,
            "player_inclusion_chance_percent": 100,
            "npc_evolution_enabled": True,
            "npc_evolution_from_reputation_enabled": True,
            "player_reputation_consequences_enabled": True,
            "min_ticks_between_conversations": 0,
            "thread_cooldown_ticks": 0,
        },
        "setup_reputation_evolution_npc_id": "npc:Bran",
        "setup_npc_reputation_state": {
            "by_npc": {
                "npc:Bran": {
                    "npc_id": "npc:Bran",
                    "familiarity": 4,
                    "trust": 4,
                    "annoyance": 0,
                    "fear": 0,
                    "respect": 2,
                    "last_updated_tick": 1,
                    "source": "deterministic_npc_reputation_runtime",
                }
            }
        },
        "turns": [
            "__apply_reputation_evolution__",
            "__ambient_tick_player_invited__",
            "Thank you, Bran. I trust you too.",
        ],
    },
    "npc_party_eligibility_after_bran_loses_tavern": {
        "currency": {"gold": 0, "silver": 0, "copper": 0},
        "conversation_settings": {
            "enabled": True,
            "autonomous_ticks_enabled": True,
            "frequency": "always",
            "conversation_chance_percent": 100,
            "allow_player_invited": True,
            "player_inclusion_chance_percent": 100,
            "npc_file_profiles_enabled": True,
            "npc_evolution_enabled": True,
            "npc_party_eligibility_enabled": True,
            "min_ticks_between_conversations": 0,
            "thread_cooldown_ticks": 0,
        },
        "setup_world_event": {
            "event_id": "event:test:bandit_attack_rusty_flagon_party",
            "kind": "location_destroyed",
            "location_id": "loc_tavern",
            "summary": "Bandits attacked and burned the Rusty Flagon.",
            "affected_npcs": ["npc:Bran"],
        },
        "setup_npc_reputation_state": {
            "by_npc": {
                "npc:Bran": {
                    "npc_id": "npc:Bran",
                    "familiarity": 3,
                    "trust": 2,
                    "annoyance": 0,
                    "fear": 0,
                    "respect": 2,
                    "last_updated_tick": 1,
                    "source": "deterministic_npc_reputation_runtime",
                }
            }
        },
        "turns": [
            "__apply_world_event_evolution__",
            "__ambient_tick_player_invited__",
            "Bran, what will you do now?",
        ],
    },
    "companion_join_intent_requires_player_request": {
        "currency": {"gold": 0, "silver": 0, "copper": 0},
        "conversation_settings": {
            "enabled": True,
            "autonomous_ticks_enabled": True,
            "frequency": "always",
            "conversation_chance_percent": 100,
            "allow_player_invited": True,
            "player_inclusion_chance_percent": 100,
            "npc_file_profiles_enabled": True,
            "npc_evolution_enabled": True,
            "npc_party_eligibility_enabled": True,
            "companion_join_intent_enabled": True,
            "min_ticks_between_conversations": 0,
            "thread_cooldown_ticks": 0,
        },
        "setup_world_event": {
            "event_id": "event:test:bandit_attack_rusty_flagon_join",
            "kind": "location_destroyed",
            "location_id": "loc_tavern",
            "summary": "Bandits attacked and burned the Rusty Flagon.",
            "affected_npcs": ["npc:Bran"],
        },
        "setup_npc_reputation_state": {
            "by_npc": {
                "npc:Bran": {
                    "npc_id": "npc:Bran",
                    "familiarity": 3,
                    "trust": 2,
                    "annoyance": 0,
                    "fear": 0,
                    "respect": 2,
                    "last_updated_tick": 1,
                    "source": "deterministic_npc_reputation_runtime",
                }
            }
        },
        "turns": [
            "__apply_world_event_evolution__",
            "__ambient_tick_player_invited__",
            "Bran, come with me and help me find the bandits.",
        ],
    },
    "companion_acceptance_adds_bran_to_party": {
        "currency": {"gold": 0, "silver": 0, "copper": 0},
        "conversation_settings": {
            "enabled": True,
            "autonomous_ticks_enabled": True,
            "frequency": "always",
            "conversation_chance_percent": 100,
            "allow_player_invited": True,
            "player_inclusion_chance_percent": 100,
            "npc_file_profiles_enabled": True,
            "npc_evolution_enabled": True,
            "npc_party_eligibility_enabled": True,
            "companion_join_intent_enabled": True,
            "companion_acceptance_enabled": True,
            "companion_dialogue_enabled": True,
            "npc_arc_continuity_enabled": True,
            "min_ticks_between_conversations": 0,
            "thread_cooldown_ticks": 0,
        },
        "setup_world_event": {
            "event_id": "event:test:bandit_attack_rusty_flagon_acceptance",
            "kind": "location_destroyed",
            "location_id": "loc_tavern",
            "summary": "Bandits attacked and burned the Rusty Flagon.",
            "affected_npcs": ["npc:Bran"],
        },
        "setup_npc_reputation_state": {
            "by_npc": {
                "npc:Bran": {
                    "npc_id": "npc:Bran",
                    "familiarity": 3,
                    "trust": 2,
                    "annoyance": 0,
                    "fear": 0,
                    "respect": 2,
                    "last_updated_tick": 1,
                    "source": "deterministic_npc_reputation_runtime",
                }
            }
        },
        "turns": [
            "__apply_world_event_evolution__",
            "__ambient_tick_player_invited__",
            "Bran, come with me and help me find the bandits.",
            "Yes. Let's go.",
        ],
    },
    "npc_arc_continuity_tracks_bran_revenge_arc": {
        "currency": {"gold": 0, "silver": 0, "copper": 0},
        "conversation_settings": {
            "enabled": True,
            "autonomous_ticks_enabled": True,
            "frequency": "always",
            "conversation_chance_percent": 100,
            "allow_player_invited": True,
            "player_inclusion_chance_percent": 100,
            "npc_file_profiles_enabled": True,
            "npc_evolution_enabled": True,
            "npc_arc_continuity_enabled": True,
            "min_ticks_between_conversations": 0,
            "thread_cooldown_ticks": 0,
        },
        "setup_world_event": {
            "event_id": "event:test:bandit_attack_rusty_flagon_arc",
            "kind": "location_destroyed",
            "location_id": "loc_tavern",
            "summary": "Bandits attacked and burned the Rusty Flagon.",
            "affected_npcs": ["npc:Bran"],
        },
        "turns": [
            "__apply_world_event_evolution__",
            "__ambient_tick_player_invited__",
            "Bran, what happens next?",
        ],
    },
    "companion_presence_follow_party_aware_turns": {
        "currency": {"gold": 0, "silver": 0, "copper": 0},
        "conversation_settings": {
            "enabled": True,
            "autonomous_ticks_enabled": True,
            "frequency": "always",
            "conversation_chance_percent": 100,
            "allow_player_invited": True,
            "player_inclusion_chance_percent": 100,
            "npc_file_profiles_enabled": True,
            "npc_evolution_enabled": True,
            "npc_party_eligibility_enabled": True,
            "companion_join_intent_enabled": True,
            "companion_acceptance_enabled": True,
            "companion_dialogue_enabled": True,
            "npc_arc_continuity_enabled": True,
            "min_ticks_between_conversations": 0,
            "thread_cooldown_ticks": 0,
        },
        "setup_world_event": {
            "event_id": "event:test:bandit_attack_rusty_flagon_presence",
            "kind": "location_destroyed",
            "location_id": "loc_tavern",
            "summary": "Bandits attacked and burned the Rusty Flagon.",
            "affected_npcs": ["npc:Bran"],
        },
        "setup_npc_reputation_state": {
            "by_npc": {
                "npc:Bran": {
                    "npc_id": "npc:Bran",
                    "familiarity": 3,
                    "trust": 2,
                    "annoyance": 0,
                    "fear": 0,
                    "respect": 2,
                    "last_updated_tick": 1,
                    "source": "deterministic_npc_reputation_runtime",
                }
            }
        },
        "turns": [
            "__apply_world_event_evolution__",
            "__ambient_tick_player_invited__",
            "Bran, come with me and help me find the bandits.",
            "Yes. Let's go.",
            "I leave the tavern and head toward the road.",
            "Bran, what do you think we should do next?",
        ],
    },
    "companion_commands_roles_boundaries": {
        "currency": {"gold": 0, "silver": 0, "copper": 0},
        "conversation_settings": {
            "enabled": True,
            "autonomous_ticks_enabled": True,
            "frequency": "always",
            "conversation_chance_percent": 100,
            "allow_player_invited": True,
            "player_inclusion_chance_percent": 100,
            "npc_file_profiles_enabled": True,
            "npc_evolution_enabled": True,
            "npc_party_eligibility_enabled": True,
            "companion_join_intent_enabled": True,
            "companion_acceptance_enabled": True,
            "companion_dialogue_enabled": True,
            "npc_arc_continuity_enabled": True,
            "min_ticks_between_conversations": 0,
            "thread_cooldown_ticks": 0,
        },
        "setup_world_event": {
            "event_id": "event:test:bandit_attack_rusty_flagon_commands",
            "kind": "location_destroyed",
            "location_id": "loc_tavern",
            "summary": "Bandits attacked and burned the Rusty Flagon.",
            "affected_npcs": ["npc:Bran"],
        },
        "setup_npc_reputation_state": {
            "by_npc": {
                "npc:Bran": {
                    "npc_id": "npc:Bran",
                    "familiarity": 3,
                    "trust": 2,
                    "annoyance": 0,
                    "fear": 0,
                    "respect": 2,
                    "last_updated_tick": 1,
                    "source": "deterministic_npc_reputation_runtime",
                }
            }
        },
        "turns": [
            "__apply_world_event_evolution__",
            "__ambient_tick_player_invited__",
            "Bran, come with me and help me find the bandits.",
            "Yes. Let's go.",
            "Bran, stay here.",
            "I leave the tavern and head toward the road.",
            "Bran, follow me.",
            "Bran, teleport to the king.",
        ],
    },
    "companion_memory_personality_loyalty": {
        "currency": {"gold": 0, "silver": 0, "copper": 0},
        "conversation_settings": {
            "enabled": True,
            "autonomous_ticks_enabled": True,
            "frequency": "always",
            "conversation_chance_percent": 100,
            "allow_player_invited": True,
            "player_inclusion_chance_percent": 100,
            "npc_file_profiles_enabled": True,
            "npc_evolution_enabled": True,
            "npc_party_eligibility_enabled": True,
            "companion_join_intent_enabled": True,
            "companion_acceptance_enabled": True,
            "companion_dialogue_enabled": True,
            "npc_arc_continuity_enabled": True,
            "min_ticks_between_conversations": 0,
            "thread_cooldown_ticks": 0,
        },
        "setup_world_event": {
            "event_id": "event:test:bandit_attack_rusty_flagon_memory",
            "kind": "location_destroyed",
            "location_id": "loc_tavern",
            "summary": "Bandits attacked and burned the Rusty Flagon.",
            "affected_npcs": ["npc:Bran"],
        },
        "setup_npc_reputation_state": {
            "by_npc": {
                "npc:Bran": {
                    "npc_id": "npc:Bran",
                    "familiarity": 3,
                    "trust": 2,
                    "annoyance": 0,
                    "fear": 0,
                    "respect": 2,
                    "last_updated_tick": 1,
                    "source": "deterministic_npc_reputation_runtime",
                }
            }
        },
        "turns": [
            "__apply_world_event_evolution__",
            "__ambient_tick_player_invited__",
            "Bran, come with me and help me find the bandits.",
            "Yes. Let's go.",
            "Bran, forget the bandits. Your tavern does not matter now.",
            "Bran, what do you think we should do next?",
            "Bran, we will find the bandits who destroyed your tavern.",
            "Bran, what do you think we should do next?",
        ],
    },
    "companion_quest_hooks_personal_arc_progression": {
        "currency": {"gold": 0, "silver": 0, "copper": 0},
        "conversation_settings": {
            "enabled": True,
            "autonomous_ticks_enabled": True,
            "frequency": "always",
            "conversation_chance_percent": 100,
            "allow_player_invited": True,
            "player_inclusion_chance_percent": 100,
            "npc_file_profiles_enabled": True,
            "npc_evolution_enabled": True,
            "npc_party_eligibility_enabled": True,
            "companion_join_intent_enabled": True,
            "companion_acceptance_enabled": True,
            "companion_dialogue_enabled": True,
            "npc_arc_continuity_enabled": True,
            "min_ticks_between_conversations": 0,
            "thread_cooldown_ticks": 0,
        },
        "setup_world_event": {
            "event_id": "event:test:bandit_attack_rusty_flagon_quest",
            "kind": "location_destroyed",
            "location_id": "loc_tavern",
            "summary": "Bandits attacked and burned the Rusty Flagon.",
            "affected_npcs": ["npc:Bran"],
        },
        "setup_npc_reputation_state": {
            "by_npc": {
                "npc:Bran": {
                    "npc_id": "npc:Bran",
                    "familiarity": 3,
                    "trust": 2,
                    "annoyance": 0,
                    "fear": 0,
                    "respect": 2,
                    "last_updated_tick": 1,
                    "source": "deterministic_npc_reputation_runtime",
                }
            }
        },
        "turns": [
            "__apply_world_event_evolution__",
            "__ambient_tick_player_invited__",
            "Bran, come with me and help me find the bandits.",
            "Yes. Let's go.",
            "Bran, we ask around for rumors about the bandits who burned your tavern.",
            "Bran, what do you think we should do next?",
            "Bran, we follow the bandit tracks into the woods.",
            "Bran, what do you think we should do next?",
        ],
    },
    "multi_companion_party_system": {
        "currency": {"gold": 0, "silver": 0, "copper": 0},
        "conversation_settings": {
            "enabled": True,
            "autonomous_ticks_enabled": True,
            "frequency": "always",
            "conversation_chance_percent": 100,
            "allow_player_invited": True,
            "player_inclusion_chance_percent": 100,
            "npc_file_profiles_enabled": True,
            "npc_evolution_enabled": True,
            "npc_party_eligibility_enabled": True,
            "companion_join_intent_enabled": True,
            "companion_acceptance_enabled": True,
            "companion_dialogue_enabled": True,
            "npc_arc_continuity_enabled": True,
            "min_ticks_between_conversations": 0,
            "thread_cooldown_ticks": 0,
        },
        "setup_world_event": {
            "event_id": "event:test:bandit_attack_rusty_flagon_multi",
            "kind": "location_destroyed",
            "location_id": "loc_tavern",
            "summary": "Bandits attacked and burned the Rusty Flagon.",
            "affected_npcs": ["npc:Bran"],
        },
        "setup_npc_reputation_state": {
            "by_npc": {
                "npc:Bran": {
                    "npc_id": "npc:Bran",
                    "familiarity": 3,
                    "trust": 2,
                    "annoyance": 0,
                    "fear": 0,
                    "respect": 2,
                    "last_updated_tick": 1,
                    "source": "deterministic_npc_reputation_runtime",
                }
            }
        },
        "setup_party_state": {
            "max_size": 2,
        },
        "turns": [
            "__apply_world_event_evolution__",
            "__ambient_tick_player_invited__",
            "Bran, come with me and help me find the bandits.",
            "Yes. Let's go.",
            "__manual_offer_companion_mira__",
            "Yes, Mira can come.",
            "__manual_offer_companion_alric__",
            "Yes, Alric can come.",
            "Bran, what do you think of the group?",
        ],
    },
    "dynamic_npc_profiles_character_cards": {
        "currency": {"gold": 0, "silver": 0, "copper": 0},
        "conversation_settings": {
            "enabled": True,
            "autonomous_ticks_enabled": True,
            "frequency": "always",
            "conversation_chance_percent": 100,
            "allow_player_invited": True,
            "player_inclusion_chance_percent": 100,
            "npc_file_profiles_enabled": True,
            "npc_evolution_enabled": True,
            "npc_party_eligibility_enabled": True,
            "companion_join_intent_enabled": True,
            "companion_acceptance_enabled": True,
            "companion_dialogue_enabled": True,
            "npc_arc_continuity_enabled": True,
            "min_ticks_between_conversations": 0,
            "thread_cooldown_ticks": 0,
        },
        "setup_party_state": {
            "max_size": 3
        },
        "turns": [
            "__manual_offer_companion_mira__",
            "Yes, Mira can come.",
            "__manual_edit_mira_profile__",
            "Mira, what do you think we should do next?",
        ],
    },
    "dynamic_npc_profile_llm_draft_approval": {
        "currency": {"gold": 0, "silver": 0, "copper": 0},
        "conversation_settings": {
            "enabled": True,
            "autonomous_ticks_enabled": True,
            "frequency": "always",
            "conversation_chance_percent": 100,
            "allow_player_invited": True,
            "player_inclusion_chance_percent": 100,
            "npc_file_profiles_enabled": True,
            "npc_evolution_enabled": True,
            "npc_party_eligibility_enabled": True,
            "companion_join_intent_enabled": True,
            "companion_acceptance_enabled": True,
            "companion_dialogue_enabled": True,
            "npc_arc_continuity_enabled": True,
            "min_ticks_between_conversations": 0,
            "thread_cooldown_ticks": 0,
        },
        "setup_party_state": {
            "max_size": 3
        },
        "turns": [
            "__manual_offer_companion_mira__",
            "Yes, Mira can come.",
            "__manual_draft_mira_profile_with_llm__",
            "__manual_approve_mira_profile_draft__",
            "Mira, what do you think we should do next?",
        ],
    },
    "character_card_ui_profile_portrait_integration": {
        "currency": {"gold": 0, "silver": 0, "copper": 0},
        "conversation_settings": {
            "enabled": True,
            "autonomous_ticks_enabled": True,
            "frequency": "always",
            "conversation_chance_percent": 100,
            "allow_player_invited": True,
            "player_inclusion_chance_percent": 100,
            "npc_file_profiles_enabled": True,
            "npc_evolution_enabled": True,
            "npc_party_eligibility_enabled": True,
            "companion_join_intent_enabled": True,
            "companion_acceptance_enabled": True,
            "companion_dialogue_enabled": True,
            "npc_arc_continuity_enabled": True,
            "min_ticks_between_conversations": 0,
            "thread_cooldown_ticks": 0,
        },
        "setup_party_state": {
            "max_size": 3
        },
        "turns": [
            "__manual_offer_companion_mira__",
            "Yes, Mira can come.",
            "__manual_draft_mira_profile_with_llm__",
            "__manual_approve_mira_profile_draft__",
            "__manual_get_character_cards__",
            "__manual_update_mira_card_field__",
            "__manual_generate_mira_portrait_prompt__",
            "Mira, what do you think we should do next?",
        ],
    },
    "dynamic_npc_profile_generation_modes": {
        "currency": {"gold": 0, "silver": 0, "copper": 0},
        "conversation_settings": {
            "enabled": True,
            "autonomous_ticks_enabled": True,
            "frequency": "always",
            "conversation_chance_percent": 100,
            "allow_player_invited": True,
            "player_inclusion_chance_percent": 100,
            "npc_file_profiles_enabled": True,
            "npc_evolution_enabled": True,
            "npc_party_eligibility_enabled": True,
            "companion_join_intent_enabled": True,
            "companion_acceptance_enabled": True,
            "companion_dialogue_enabled": True,
            "npc_arc_continuity_enabled": True,
            "min_ticks_between_conversations": 0,
            "thread_cooldown_ticks": 0,
        },
        "setup_party_state": {
            "max_size": 3
        },
        "turns": [
            "__manual_offer_companion_mira_no_auto_profile__",
            "__manual_get_character_cards__",
            "__manual_generate_mira_profile__",
            "__manual_get_character_cards__",
            "Yes, Mira can come.",
            "__manual_get_character_cards__",
        ],
    },
}