/**
 * Generated by scripts/generate-api-types.mjs from openapi.json and route-owners.json; do not edit.
 */
import type { components as core } from '../../../api/generated/core';

export interface paths {
    "/api/audiobook/models/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audiobook Model */
        get: operations["audiobook_model_api_audiobook_models_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobook/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_audiobook_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_audiobook_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobook/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_audiobook_projects__project_id__get"];
        put?: never;
        post?: never;
        /** Delete Project */
        delete: operations["delete_project_api_audiobook_projects__project_id__delete"];
        options?: never;
        head?: never;
        /** Update Project */
        patch: operations["update_project_api_audiobook_projects__project_id__patch"];
        trace?: never;
    };
    "/api/audiobook/projects/{project_id}/assets/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Asset */
        delete: operations["delete_asset_api_audiobook_projects__project_id__assets__asset_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobook/projects/{project_id}/chapters/{chapter_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Chapter */
        get: operations["get_chapter_api_audiobook_projects__project_id__chapters__chapter_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobook/projects/{project_id}/classification-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save Classification Rules */
        post: operations["save_classification_rules_api_audiobook_projects__project_id__classification_rules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobook/projects/{project_id}/cover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Project Cover */
        get: operations["project_cover_api_audiobook_projects__project_id__cover_get"];
        put?: never;
        /** Upload Cover */
        post: operations["upload_cover_api_audiobook_projects__project_id__cover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobook/projects/{project_id}/document-overrides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Document Override */
        post: operations["set_document_override_api_audiobook_projects__project_id__document_overrides_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobook/projects/{project_id}/document-structure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document Structure */
        get: operations["get_document_structure_api_audiobook_projects__project_id__document_structure_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobook/projects/{project_id}/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Exports */
        get: operations["list_exports_api_audiobook_projects__project_id__exports_get"];
        put?: never;
        /** Start Export */
        post: operations["start_export_api_audiobook_projects__project_id__exports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobook/projects/{project_id}/exports/{export_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Export */
        get: operations["download_export_api_audiobook_projects__project_id__exports__export_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobook/projects/{project_id}/exports/{export_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Report */
        get: operations["export_report_api_audiobook_projects__project_id__exports__export_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobook/projects/{project_id}/extract-quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extract Quotes */
        post: operations["extract_quotes_api_audiobook_projects__project_id__extract_quotes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobook/projects/{project_id}/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Audiobook Job */
        post: operations["cancel_audiobook_job_api_audiobook_projects__project_id__jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobook/projects/{project_id}/jobs/{job_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause Audiobook Job */
        post: operations["pause_audiobook_job_api_audiobook_projects__project_id__jobs__job_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobook/projects/{project_id}/jobs/{job_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Audiobook Job */
        post: operations["resume_audiobook_job_api_audiobook_projects__project_id__jobs__job_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobook/projects/{project_id}/jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Audiobook Job */
        post: operations["retry_audiobook_job_api_audiobook_projects__project_id__jobs__job_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobook/projects/{project_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Preview */
        post: operations["start_preview_api_audiobook_projects__project_id__preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobook/projects/{project_id}/previews/{job_id}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview Audio */
        get: operations["preview_audio_api_audiobook_projects__project_id__previews__job_id__audio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobook/projects/{project_id}/pronunciations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Pronunciation */
        post: operations["set_pronunciation_api_audiobook_projects__project_id__pronunciations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobook/projects/{project_id}/reading-policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Set Reading Policy */
        patch: operations["set_reading_policy_api_audiobook_projects__project_id__reading_policy_patch"];
        trace?: never;
    };
    "/api/audiobook/projects/{project_id}/reclassify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reclassify Audiobook */
        post: operations["reclassify_audiobook_api_audiobook_projects__project_id__reclassify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobook/projects/{project_id}/render": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Render */
        post: operations["start_render_api_audiobook_projects__project_id__render_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobook/projects/{project_id}/render/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause Audiobook Render Queue */
        post: operations["pause_audiobook_render_queue_api_audiobook_projects__project_id__render_pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobook/projects/{project_id}/render/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Audiobook Render Queue */
        post: operations["resume_audiobook_render_queue_api_audiobook_projects__project_id__render_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobook/projects/{project_id}/render/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop Audiobook Render Queue */
        post: operations["stop_audiobook_render_queue_api_audiobook_projects__project_id__render_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobook/projects/{project_id}/review/{issue_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Issue */
        post: operations["resolve_issue_api_audiobook_projects__project_id__review__issue_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobook/projects/{project_id}/source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Source */
        post: operations["upload_source_api_audiobook_projects__project_id__source_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobook/projects/{project_id}/source/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Source */
        get: operations["download_source_api_audiobook_projects__project_id__source_download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobook/projects/{project_id}/source/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Library Source */
        post: operations["import_library_source_api_audiobook_projects__project_id__source_library_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobook/projects/{project_id}/spans/{span_id}/annotation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revise Span */
        post: operations["revise_span_api_audiobook_projects__project_id__spans__span_id__annotation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobook/projects/{project_id}/spans/{span_id}/speech-exclusions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exclude Span Text */
        post: operations["exclude_span_text_api_audiobook_projects__project_id__spans__span_id__speech_exclusions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobook/projects/{project_id}/speakers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Speaker */
        post: operations["add_speaker_api_audiobook_projects__project_id__speakers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobook/projects/{project_id}/speakers/{speaker_id}/aliases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Alias */
        post: operations["confirm_alias_api_audiobook_projects__project_id__speakers__speaker_id__aliases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobook/projects/{project_id}/speakers/{speaker_id}/casting": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assign Voice */
        post: operations["assign_voice_api_audiobook_projects__project_id__speakers__speaker_id__casting_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobook/projects/{project_id}/speakers/{speaker_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Speaker */
        post: operations["reject_speaker_api_audiobook_projects__project_id__speakers__speaker_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobook/projects/{project_id}/speech-exclusions/{exclusion_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Restore Span Text */
        delete: operations["restore_span_text_api_audiobook_projects__project_id__speech_exclusions__exclusion_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobook/source-library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Source Library */
        get: operations["source_library_api_audiobook_source_library_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobook/voices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Voices */
        get: operations["list_voices_api_audiobook_voices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssetContentResponse */
        AssetContentResponse: core["schemas"]["AssetContentResponse"];
        /** AssetLegacyRootScan */
        AssetLegacyRootScan: core["schemas"]["AssetLegacyRootScan"];
        /**
         * AssetType
         * @enum {string}
         */
        AssetType: core["schemas"]["AssetType"];
        /** AssignVoice */
        AssignVoice: {
            /** Voice Profile Id */
            voice_profile_id: string;
        };
        /**
         * AssistantToolAction
         * @description Backend-owned action definition for an assistant tool.
         */
        AssistantToolAction: core["schemas"]["AssistantToolAction"];
        /**
         * AssistantToolRegistryPayload
         * @description Serializable backend mirror of assistant tools and actions.
         */
        AssistantToolRegistryPayload: core["schemas"]["AssistantToolRegistryPayload"];
        /**
         * AssistantToolSpec
         * @description Backend-owned assistant tool metadata and actions.
         */
        AssistantToolSpec: core["schemas"]["AssistantToolSpec"];
        /** AuthSessionListResponse */
        AuthSessionListResponse: core["schemas"]["AuthSessionListResponse"];
        /** AuthSessionResponse */
        AuthSessionResponse: core["schemas"]["AuthSessionResponse"];
        /** AuthSessionSummary */
        AuthSessionSummary: core["schemas"]["AuthSessionSummary"];
        /** CancelJobRequest */
        CancelJobRequest: core["schemas"]["CancelJobRequest"];
        /** CancelState */
        CancelState: core["schemas"]["CancelState"];
        /** ChatMessage */
        ChatMessage: core["schemas"]["ChatMessage"];
        /** ChatSession */
        ChatSession: core["schemas"]["ChatSession"];
        /** ChatSessionListResponse */
        ChatSessionListResponse: core["schemas"]["ChatSessionListResponse"];
        /** ChatSessionSummary */
        ChatSessionSummary: core["schemas"]["ChatSessionSummary"];
        /**
         * ChatTextAttachment
         * @description A small, UTF-8 text file attached to a chat turn.
         *
         *     Binary files are deliberately not accepted through the JSON chat API.  The
         *     browser reads supported text documents before sending them, which keeps the
         *     stored transcript and every provider prompt self-contained.
         */
        ChatTextAttachment: core["schemas"]["ChatTextAttachment"];
        /**
         * CheckpointBundleRequest
         * @description Extensible state bundle with explicit checkpoint control fields.
         */
        CheckpointBundleRequest: core["schemas"]["CheckpointBundleRequest"];
        /** CheckpointEnvelope */
        CheckpointEnvelope: core["schemas"]["CheckpointEnvelope"];
        /** ClaimJobRequest */
        ClaimJobRequest: core["schemas"]["ClaimJobRequest"];
        /** ClaimJobResponse */
        ClaimJobResponse: core["schemas"]["ClaimJobResponse"];
        /** ClassificationRequest */
        ClassificationRequest: {
            /**
             * Custom Rules
             * @default
             */
            custom_rules?: string;
        };
        /** ClientErrorAccepted */
        ClientErrorAccepted: core["schemas"]["ClientErrorAccepted"];
        /** ClientErrorReport */
        ClientErrorReport: core["schemas"]["ClientErrorReport"];
        /** CodexAuthStatus */
        CodexAuthStatus: core["schemas"]["CodexAuthStatus"];
        /** CoinMarketCapCredentialStatus */
        CoinMarketCapCredentialStatus: core["schemas"]["CoinMarketCapCredentialStatus"];
        /** CoinMarketCapCredentialUpdate */
        CoinMarketCapCredentialUpdate: core["schemas"]["CoinMarketCapCredentialUpdate"];
        /** CompatibilityHandoffPayload */
        CompatibilityHandoffPayload: core["schemas"]["CompatibilityHandoffPayload"];
        /** CompleteJobRequest */
        CompleteJobRequest: core["schemas"]["CompleteJobRequest"];
        /** ConfirmSpeakerAlias */
        ConfirmSpeakerAlias: {
            /** Alias */
            alias: string;
        };
        /** CreateAudiobookProject */
        CreateAudiobookProject: {
            /**
             * Author
             * @default
             */
            author?: string;
            /**
             * Custom Rules
             * @default
             */
            custom_rules?: string;
            /**
             * Language
             * @default en
             */
            language?: string;
            /** Title */
            title: string;
        };
        /**
         * CreateChatSessionRequest
         * @description Client selection; trusted identity/profile content is intentionally absent.
         */
        CreateChatSessionRequest: core["schemas"]["CreateChatSessionRequest"];
        /** CreateJobRequest */
        CreateJobRequest: core["schemas"]["CreateJobRequest"];
        /** CreateSpeaker */
        CreateSpeaker: {
            /** Canonical Name */
            canonical_name: string;
        };
        /** DeleteChatSessionResponse */
        DeleteChatSessionResponse: core["schemas"]["DeleteChatSessionResponse"];
        /** DiagnosticsPayload */
        DiagnosticsPayload: core["schemas"]["DiagnosticsPayload"];
        /**
         * EventReaderDiagnostics
         * @description Live job events in this process (WP-5.4).
         */
        EventReaderDiagnostics: core["schemas"]["EventReaderDiagnostics"];
        /** ExcludeSpanText */
        ExcludeSpanText: {
            /** End Offset */
            end_offset: number;
            /** Source Text */
            source_text: string;
            /** Start Offset */
            start_offset: number;
        };
        /** FailJobRequest */
        FailJobRequest: core["schemas"]["FailJobRequest"];
        /** GatewayHealth */
        GatewayHealth: core["schemas"]["GatewayHealth"];
        /**
         * GatewayReadinessPayload
         * @description Stable readiness fields plus deployment-specific diagnostic fields.
         */
        GatewayReadinessPayload: core["schemas"]["GatewayReadinessPayload"];
        /** GpuResidencyPolicy */
        GpuResidencyPolicy: core["schemas"]["GpuResidencyPolicy"];
        /** HTTPValidationError */
        HTTPValidationError: core["schemas"]["HTTPValidationError"];
        /** HermesDiagnosticsPaths */
        HermesDiagnosticsPaths: core["schemas"]["HermesDiagnosticsPaths"];
        /**
         * HermesStatusResponse
         * @description Sidecar reachability and the runtime configuration that reaches it.
         */
        HermesStatusResponse: core["schemas"]["HermesStatusResponse"];
        /** IbkrSettingsPayload */
        IbkrSettingsPayload: core["schemas"]["IbkrSettingsPayload"];
        /** IbkrSettingsStatus */
        IbkrSettingsStatus: core["schemas"]["IbkrSettingsStatus"];
        /** IbkrSettingsUpdate */
        IbkrSettingsUpdate: core["schemas"]["IbkrSettingsUpdate"];
        /** JobError */
        JobError: core["schemas"]["JobError"];
        /** JobError */
        "JobError-Input": core["schemas"]["JobError-Input"];
        /** JobLease */
        JobLease: core["schemas"]["JobLease"];
        /**
         * JobListResponse
         * @description A page of jobs, newest first (WP-5.5).
         */
        JobListResponse: core["schemas"]["JobListResponse"];
        /** JobProgress */
        JobProgress: core["schemas"]["JobProgress"];
        /** JobProgress */
        "JobProgress-Input": core["schemas"]["JobProgress-Input"];
        /** JobRecord */
        JobRecord: core["schemas"]["JobRecord"];
        /** JobStage */
        JobStage: core["schemas"]["JobStage"];
        /** JobStage */
        "JobStage-Input": core["schemas"]["JobStage-Input"];
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: core["schemas"]["JobStatus"];
        /** LegacyGenerateTitleRequest */
        LegacyGenerateTitleRequest: core["schemas"]["LegacyGenerateTitleRequest"];
        /** LegacyGenerateTitleResponse */
        LegacyGenerateTitleResponse: core["schemas"]["LegacyGenerateTitleResponse"];
        /** LegacySessionCreateResponse */
        LegacySessionCreateResponse: core["schemas"]["LegacySessionCreateResponse"];
        /** LegacySessionListItem */
        LegacySessionListItem: core["schemas"]["LegacySessionListItem"];
        /** LegacySessionListResponse */
        LegacySessionListResponse: core["schemas"]["LegacySessionListResponse"];
        /** LegacySessionResponse */
        LegacySessionResponse: core["schemas"]["LegacySessionResponse"];
        /** LegacySessionUpdateRequest */
        LegacySessionUpdateRequest: core["schemas"]["LegacySessionUpdateRequest"];
        /** LegacySuccessResponse */
        LegacySuccessResponse: core["schemas"]["LegacySuccessResponse"];
        /** LocalLoginRequest */
        LocalLoginRequest: core["schemas"]["LocalLoginRequest"];
        /** ModelResidencyDiagnostics */
        ModelResidencyDiagnostics: core["schemas"]["ModelResidencyDiagnostics"];
        /** ModelResidencyRecord */
        ModelResidencyRecord: core["schemas"]["ModelResidencyRecord"];
        /** ModelResidencyRecord */
        "ModelResidencyRecord-Input": core["schemas"]["ModelResidencyRecord-Input"];
        /**
         * ModelResidencyStatus
         * @enum {string}
         */
        ModelResidencyStatus: core["schemas"]["ModelResidencyStatus"];
        /** ModelSummary */
        ModelSummary: core["schemas"]["ModelSummary"];
        /** PersistenceInventory */
        PersistenceInventory: core["schemas"]["PersistenceInventory"];
        /** PromptRenderRequest */
        PromptRenderRequest: core["schemas"]["PromptRenderRequest"];
        /** PromptTemplate */
        PromptTemplate: core["schemas"]["PromptTemplate"];
        /**
         * ProviderCapability
         * @enum {string}
         */
        ProviderCapability: core["schemas"]["ProviderCapability"];
        /** ProviderFacadePayload */
        ProviderFacadePayload: core["schemas"]["ProviderFacadePayload"];
        /** ProviderModelCacheEntry */
        ProviderModelCacheEntry: core["schemas"]["ProviderModelCacheEntry"];
        /** ProviderModelCachePayload */
        ProviderModelCachePayload: core["schemas"]["ProviderModelCachePayload"];
        /** ProviderModelRefreshRequest */
        ProviderModelRefreshRequest: core["schemas"]["ProviderModelRefreshRequest"];
        /** ProviderSummary */
        ProviderSummary: core["schemas"]["ProviderSummary"];
        /** PublicAssetLegacyImportDryRun */
        PublicAssetLegacyImportDryRun: core["schemas"]["PublicAssetLegacyImportDryRun"];
        /**
         * PublicAssetListResponse
         * @description ``AssetListResponse`` as the API returns it.
         */
        PublicAssetListResponse: core["schemas"]["PublicAssetListResponse"];
        /** PublicAssetMigrationPreview */
        PublicAssetMigrationPreview: core["schemas"]["PublicAssetMigrationPreview"];
        /**
         * PublicAssetRecord
         * @description An asset as the API returns it: ids and URLs, never where its bytes are
         *     stored (WP-4.10). Built from an ``AssetRecord``: the storage path and key
         *     and the legacy ``compat`` block are left out, absolute paths in metadata
         *     become file names.
         */
        PublicAssetRecord: core["schemas"]["PublicAssetRecord"];
        /** RenderedPrompt */
        RenderedPrompt: core["schemas"]["RenderedPrompt"];
        /** ReplayPrimitive */
        ReplayPrimitive: core["schemas"]["ReplayPrimitive"];
        /** ReplayPrimitiveList */
        ReplayPrimitiveList: core["schemas"]["ReplayPrimitiveList"];
        /** ReportArtifact */
        ReportArtifact: core["schemas"]["ReportArtifact"];
        /** ReportListResponse */
        ReportListResponse: core["schemas"]["ReportListResponse"];
        /** ResearchBudgetStatus */
        ResearchBudgetStatus: core["schemas"]["ResearchBudgetStatus"];
        /** ResearchCompatibilityStatus */
        ResearchCompatibilityStatus: core["schemas"]["ResearchCompatibilityStatus"];
        /** ResearchCredentialUpdate */
        ResearchCredentialUpdate: core["schemas"]["ResearchCredentialUpdate"];
        /** ResearchProviderStatus */
        ResearchProviderStatus: core["schemas"]["ResearchProviderStatus"];
        /** ResearchReleaseAvailability */
        ResearchReleaseAvailability: core["schemas"]["ResearchReleaseAvailability"];
        /** ResearchReleaseStatus */
        ResearchReleaseStatus: core["schemas"]["ResearchReleaseStatus"];
        /** ResearchRetentionStatus */
        ResearchRetentionStatus: core["schemas"]["ResearchRetentionStatus"];
        /** ResearchRuntimeStatus */
        ResearchRuntimeStatus: core["schemas"]["ResearchRuntimeStatus"];
        /** ResolveReviewIssue */
        ResolveReviewIssue: {
            /**
             * Delivery
             * @default
             */
            delivery?: string;
            /** Role */
            role: string;
            /** Speaker Id */
            speaker_id: string;
        };
        /**
         * ResourceClass
         * @enum {string}
         */
        ResourceClass: core["schemas"]["ResourceClass"];
        /**
         * RetentionRunDiagnostics
         * @description The newest retention run; the error is reported by class only.
         */
        RetentionRunDiagnostics: core["schemas"]["RetentionRunDiagnostics"];
        /** RetiredWorkerProtocolResponse */
        RetiredWorkerProtocolResponse: core["schemas"]["RetiredWorkerProtocolResponse"];
        /** RetryState */
        RetryState: core["schemas"]["RetryState"];
        /** RetryState */
        "RetryState-Input": core["schemas"]["RetryState-Input"];
        /** ReviseSpanAnnotation */
        ReviseSpanAnnotation: {
            /**
             * Delivery
             * @default
             */
            delivery?: string;
            /** Role */
            role: string;
            /** Speaker Id */
            speaker_id: string;
        };
        /** RevokeSessionsRequest */
        RevokeSessionsRequest: core["schemas"]["RevokeSessionsRequest"];
        /** RevokeSessionsResponse */
        RevokeSessionsResponse: core["schemas"]["RevokeSessionsResponse"];
        /**
         * RuntimeDiagnostics
         * @description One process's runtime view (WP-10.9); sections are documented in docs/operations/DIAGNOSTICS.md.
         */
        RuntimeDiagnostics: core["schemas"]["RuntimeDiagnostics"];
        /** RuntimeStatusPayload */
        RuntimeStatusPayload: core["schemas"]["RuntimeStatusPayload"];
        /** SendChatMessageRequest */
        SendChatMessageRequest: core["schemas"]["SendChatMessageRequest"];
        /** SendChatMessageResponse */
        SendChatMessageResponse: core["schemas"]["SendChatMessageResponse"];
        /** SetAudiobookMode */
        SetAudiobookMode: {
            /** Mode */
            mode: string;
        };
        /** SetDocumentOverride */
        SetDocumentOverride: {
            /**
             * Action
             * @default DEFAULT
             */
            action?: string;
            /** Role Override */
            role_override?: string | null;
            /** Scope */
            scope: string;
            /** Scope Key */
            scope_key: string;
        };
        /** SetPronunciation */
        SetPronunciation: {
            /** Source Term */
            source_term: string;
            /** Spoken Term */
            spoken_term: string;
        };
        /** SettingsPatch */
        SettingsPatch: core["schemas"]["SettingsPatch"];
        /** SettingsPayload */
        SettingsPayload: core["schemas"]["SettingsPayload"];
        /**
         * SettingsProfileSaveRequest
         * @description A Settings Control Center save: a profile patch plus the provider sections it changed.
         *
         *     ``base_revision`` is the profile revision the patch was made against; a
         *     newer profile refuses the save. Provider sections are merged into the
         *     stored settings, and an ``api_key`` in them goes to the secret store
         *     (a masked ``***`` value leaves the stored key unchanged).
         */
        SettingsProfileSaveRequest: core["schemas"]["SettingsProfileSaveRequest"];
        /** SettingsSaveResponse */
        SettingsSaveResponse: core["schemas"]["SettingsSaveResponse"];
        /** StartExport */
        StartExport: {
            /**
             * Format
             * @default m4b
             */
            format?: string;
        };
        /** StartPreview */
        StartPreview: {
            /** Chapter Id */
            chapter_id: string;
            /** Generation Parameters */
            generation_parameters?: {
                [key: string]: unknown;
            };
            /**
             * Model Id
             * @default Qwen3-TTS
             */
            model_id?: string;
            /** Model Revision */
            model_revision: string;
            /**
             * Provider Id
             * @default faster-qwen3-tts
             */
            provider_id?: string;
            /** Seed */
            seed?: number | null;
            /** Span Id */
            span_id: string;
            /** Voice Profile Id */
            voice_profile_id?: string | null;
        };
        /** StartRender */
        StartRender: {
            /** Generation Parameters */
            generation_parameters?: {
                [key: string]: unknown;
            };
            /**
             * Model Id
             * @default Qwen3-TTS
             */
            model_id?: string;
            /** Model Revision */
            model_revision: string;
            /**
             * Provider Id
             * @default faster-qwen3-tts
             */
            provider_id?: string;
            /** Seed */
            seed?: number | null;
        };
        /** StateHashRequest */
        StateHashRequest: core["schemas"]["StateHashRequest"];
        /** StateHashResponse */
        StateHashResponse: core["schemas"]["StateHashResponse"];
        /** UpdateAudiobookProject */
        UpdateAudiobookProject: {
            /**
             * Author
             * @default
             */
            author?: string;
            /** Title */
            title: string;
        };
        /** ValidationError */
        ValidationError: core["schemas"]["ValidationError"];
        /** VersionDiagnostics */
        VersionDiagnostics: core["schemas"]["VersionDiagnostics"];
        /** WorkerHealth */
        WorkerHealth: core["schemas"]["WorkerHealth"];
        /** WorkerHealthPayload */
        WorkerHealthPayload: core["schemas"]["WorkerHealthPayload"];
        /** WorkerHealthSummary */
        WorkerHealthSummary: core["schemas"]["WorkerHealthSummary"];
        /** WorkerPayloadPolicy */
        WorkerPayloadPolicy: core["schemas"]["WorkerPayloadPolicy"];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    audiobook_model_api_audiobook_models_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_projects_api_audiobook_projects_get: {
        parameters: {
            query?: {
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_api_audiobook_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAudiobookProject"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_audiobook_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_api_audiobook_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_api_audiobook_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAudiobookProject"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_asset_api_audiobook_projects__project_id__assets__asset_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chapter_api_audiobook_projects__project_id__chapters__chapter_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                chapter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_classification_rules_api_audiobook_projects__project_id__classification_rules_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClassificationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_cover_api_audiobook_projects__project_id__cover_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File content returned with its source media type. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                    "image/png": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_cover_api_audiobook_projects__project_id__cover_post: {
        parameters: {
            query?: {
                filename?: string;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_document_override_api_audiobook_projects__project_id__document_overrides_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetDocumentOverride"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_structure_api_audiobook_projects__project_id__document_structure_get: {
        parameters: {
            query?: {
                chapter_id?: string | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_exports_api_audiobook_projects__project_id__exports_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_export_api_audiobook_projects__project_id__exports_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartExport"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_export_api_audiobook_projects__project_id__exports__export_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                export_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File content returned with its source media type. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "audio/flac": string;
                    "audio/mp4": string;
                    "audio/mpeg": string;
                    "audio/wav": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_report_api_audiobook_projects__project_id__exports__export_id__report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                export_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_quotes_api_audiobook_projects__project_id__extract_quotes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ClassificationRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_audiobook_job_api_audiobook_projects__project_id__jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_audiobook_job_api_audiobook_projects__project_id__jobs__job_id__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_audiobook_job_api_audiobook_projects__project_id__jobs__job_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_audiobook_job_api_audiobook_projects__project_id__jobs__job_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_preview_api_audiobook_projects__project_id__preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartPreview"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_audio_api_audiobook_projects__project_id__previews__job_id__audio_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File content returned with its source media type. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "audio/wav": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_pronunciation_api_audiobook_projects__project_id__pronunciations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPronunciation"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_reading_policy_api_audiobook_projects__project_id__reading_policy_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetAudiobookMode"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reclassify_audiobook_api_audiobook_projects__project_id__reclassify_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ClassificationRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_render_api_audiobook_projects__project_id__render_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartRender"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_audiobook_render_queue_api_audiobook_projects__project_id__render_pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_audiobook_render_queue_api_audiobook_projects__project_id__render_resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_audiobook_render_queue_api_audiobook_projects__project_id__render_stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_issue_api_audiobook_projects__project_id__review__issue_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                issue_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveReviewIssue"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_source_api_audiobook_projects__project_id__source_post: {
        parameters: {
            query: {
                source_format: string;
                filename?: string;
                exclude_pages?: string | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_source_api_audiobook_projects__project_id__source_download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File content returned with its source media type. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/epub+zip": string;
                    "application/pdf": string;
                    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": string;
                    "text/html": string;
                    "text/markdown": string;
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_library_source_api_audiobook_projects__project_id__source_library_post: {
        parameters: {
            query: {
                filename: string;
                exclude_pages?: string | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revise_span_api_audiobook_projects__project_id__spans__span_id__annotation_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                span_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviseSpanAnnotation"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    exclude_span_text_api_audiobook_projects__project_id__spans__span_id__speech_exclusions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                span_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExcludeSpanText"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_speaker_api_audiobook_projects__project_id__speakers_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSpeaker"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_alias_api_audiobook_projects__project_id__speakers__speaker_id__aliases_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                speaker_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmSpeakerAlias"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_voice_api_audiobook_projects__project_id__speakers__speaker_id__casting_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                speaker_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignVoice"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_speaker_api_audiobook_projects__project_id__speakers__speaker_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                speaker_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_span_text_api_audiobook_projects__project_id__speech_exclusions__exclusion_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                exclusion_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    source_library_api_audiobook_source_library_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_voices_api_audiobook_voices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
